HIFIR: hif::Timer< Clock, RepType > Class Template Reference
hif::Timer< Clock, RepType > Class Template Reference
Utilities
C++11 standard timer implementation.
#include <Timer.hpp>
Public Types
typedef internal::ClockTrait< CLOCK >::clock_type clock_type
std clock type
typedef internal::TimePointTrait< CLOCK >::time_point time_point
time point
typedef RepType default_rep_type
representation type
Public Member Functions
void start ()
start timer
void finish ()
finish timer
template<class _RepType , ClockUnit Unit = TIMER_SECONDS>
_RepType time () const
get time report
default_rep_type time () const
get time report in seconds
default_rep_type time_milli () const
get time report in milliseconds
default_rep_type time_micro () const
get time report in microseconds
default_rep_type time_nano () const
get time report in nanoseconds
Static Public Attributes
static constexpr ClockType CLOCK = Clock
clock type
Private Attributes
time_point _start
start point
time_point _end
end point
Detailed Description
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double>
class hif::Timer< Clock, RepType >
C++11 standard timer implementation.
Template Parameters
Clock ClockType, default is TIMER_SYSTEM_CLOCK
RepType time period representation type, default is double
Note
Using the timer in a local environment is preferred
Examples:
demo_fgmres.cpp, demo_fgmres_sparsifier.cpp, demo_gmreshif.cpp, and demo_sparsifier.cpp.
Definition at line 114 of file Timer.hpp.
Member Typedef Documentation
clock_type
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> typedef internal::ClockTrait<CLOCK>::clock_type hif::Timer< Clock, RepType >::clock_type
std clock type
Definition at line 117 of file Timer.hpp.
default_rep_type
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> typedef RepType hif::Timer< Clock, RepType >::default_rep_type
representation type
Definition at line 121 of file Timer.hpp.
time_point
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> typedef internal::TimePointTrait<CLOCK>::time_point hif::Timer< Clock, RepType >::time_point
time point
Definition at line 119 of file Timer.hpp.
Member Function Documentation
finish()
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> void hif::Timer< Clock, RepType >::finish () inline
finish timer
See also
start
Examples:
demo_fgmres.cpp, and demo_gmreshif.cpp.
Definition at line 129 of file Timer.hpp.
References hif::Timer< Clock, RepType >::_end.
Referenced by hif::do_maching(), hif::do_preprocessing(), hif::HIF< ValueType, IndexType, UserDenseFactor >::factorize(), hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
start()
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> void hif::Timer< Clock, RepType >::start () inline
start timer
See also
finish
Examples:
demo_fgmres.cpp, and demo_gmreshif.cpp.
Definition at line 125 of file Timer.hpp.
References hif::Timer< Clock, RepType >::_start.
Referenced by hif::do_maching(), hif::do_preprocessing(), hif::HIF< ValueType, IndexType, UserDenseFactor >::factorize(), hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
time() [1/2]
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> template<class _RepType , ClockUnit Unit = TIMER_SECONDS> _RepType hif::Timer< Clock, RepType >::time () const inline
get time report
Template Parameters
_RepType representation type
Unit report unit type, default is TIMER_SECONDS
Returns
a time period representation in RepType and Unit
Examples:
demo_fgmres.cpp, and demo_gmreshif.cpp.
Definition at line 136 of file Timer.hpp.
References hif::Timer< Clock, RepType >::_end, and hif::Timer< Clock, RepType >::_start.
time() [2/2]
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> default_rep_type hif::Timer< Clock, RepType >::time () const inline
get time report in seconds
Definition at line 143 of file Timer.hpp.
Referenced by hif::do_maching(), hif::do_preprocessing(), hif::HIF< ValueType, IndexType, UserDenseFactor >::factorize(), hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
time_micro()
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> default_rep_type hif::Timer< Clock, RepType >::time_micro () const inline
get time report in microseconds
Definition at line 151 of file Timer.hpp.
References hif::TIMER_MICROSECONDS.
time_milli()
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> default_rep_type hif::Timer< Clock, RepType >::time_milli () const inline
get time report in milliseconds
Definition at line 146 of file Timer.hpp.
References hif::TIMER_MILLISECONDS.
time_nano()
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> default_rep_type hif::Timer< Clock, RepType >::time_nano () const inline
get time report in nanoseconds
Definition at line 156 of file Timer.hpp.
References hif::TIMER_NANOSECONDS.
Member Data Documentation
_end
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> time_point hif::Timer< Clock, RepType >::_end private
end point
Definition at line 162 of file Timer.hpp.
Referenced by hif::Timer< Clock, RepType >::finish(), and hif::Timer< Clock, RepType >::time().
_start
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> time_point hif::Timer< Clock, RepType >::_start private
start point
Definition at line 161 of file Timer.hpp.
Referenced by hif::Timer< Clock, RepType >::start(), and hif::Timer< Clock, RepType >::time().
CLOCK
template<ClockType Clock = TIMER_SYSTEM_CLOCK, class RepType = double> constexpr ClockType hif::Timer< Clock, RepType >::CLOCK = Clock static
clock type
Definition at line 116 of file Timer.hpp.
The documentation for this class was generated from the following file:
Timer.hpp