HIFIR: hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor > Class Template Reference
hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor > Class Template Reference
HIF User Interfaces
#include <builder.hpp>
Public Types
typedef ValueType value_type
value type
typedef Array< value_type > array_type
array type
typedef IndexType index_type
index type
typedef IndPtrType indptr_type
index pointer
typedef Array< index_type > iarray_type
index array
typedef Array< indptr_type > iparray_type
indptr array
typedef CRS< value_type, index_type, indptr_type > crs_type
crs type
typedef crs_type::other_type ccs_type
ccs type
typedef Precs< value_type, index_type, indptr_type, UserDenseFactor > precs_type
multilevel preconditioner type
typedef precs_type::value_type prec_type
single level prec
typedef prec_type::size_type size_type
size type
typedef value_type boost_value_type
high-precision value type
typedef Array< boost_value_type > work_array_type
work array type
Public Member Functions
bool empty () const
check empty or not
size_type levels () const
check number of levels
const precs_type & precs () const
get constant reference to preconditioners
precs_type & precs ()
get normal reference to preconditioners
size_type nnz () const
compute the overall nnz of the multilevel preconditioners
size_type rank () const
get the numerical rank
size_type schur_rank () const
get the numerical rank for last level (dense Schur complement)
size_type schur_size () const
get the Schur complement size
size_type nnz_ef () const
compute the nnz in E and F components
size_type nnz_ldu () const
compute the nnz in L, D, and U
size_type nrows () const
get number of rows
size_type ncols () const
get number of columns
size_type stats (const size_type entry) const
get the stats
const prec_type & prec (const size_type level) const
get constant reference to a specific level
void clear ()
clear internal storage
template<class CsType >
void factorize (const CsType &A, const Params &params=DEFAULT_PARAMS, const size_type m0=0u)
factorize the HIF preconditioner
template<bool IsCrs, class IndexType_ , class ValueType_ , class IndPtrType_ = std::ptrdiff_t>
void factorize (const size_type n, const IndPtrType_ *indptr, const IndexType_ *indices, const ValueType_ *vals, const Params &params=DEFAULT_PARAMS, const size_type m0=0u)
factorize the HIF preconditioner with generic interface
template<class RhsType , class SolType >
void solve (const RhsType &b, SolType &x, const bool trans=false, const size_type r=0u) const
solve
template<class RhsValueType , class SolValueType , size_type Nrhs>
void solve_mrhs (const Array< std::array< RhsValueType, Nrhs >> &b, Array< std::array< SolValueType, Nrhs >> &x, const size_type r=0u) const
solve (multiple RHS)
template<class Matrix , class RhsType , class SolType >
void hifir (const Matrix &A, const RhsType &b, const size_type N, SolType &x, const bool trans=false, const size_type r=static_cast< size_type >(-1)) const
solve with iterative refinement
template<class Matrix , class RhsType , class SolType >
std::pair< size_type, int > hifir (const Matrix &A, const RhsType &b, const size_type N, const double *betas, SolType &x, const bool trans=false, const size_type r=static_cast< size_type >(-1)) const
solve with iterative refinement and residual bounds
template<class RhsType , class SolType >
void mmultiply (const RhsType &x, SolType &y, const bool trans=false, const size_type r=0u) const
compute
Public Attributes
NspFilterPtr nsp
null space filter
NspFilterPtr nsp_tran
transpose null space filter (left null space)
Protected Member Functions
template<class CsType , class CroutStreamer >
void _factorize_kernel (const CsType &A, const size_type m0, const Params &opts, iarray_type &row_sizes, iarray_type &col_sizes, const CroutStreamer &Crout_info, const int schur_threads=1, const bool must_pivot=false)
Protected Attributes
precs_type _precs
multilevel preconditioners
work_array_type _prec_work
preconditioner work space for solving
size_type _stats [6]
statistics
size_type _nrows
number of rows from user input
size_type _ncols
number of columns from user input
IterRefine< boost_value_type > _ir
high-precision iterative refinement
Detailed Description
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver>
class hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >
Template Parameters
ValueType numerical value type, e.g. double
IndexType index type, e.g. int
IndPtrType index pionter type, default is std::ptrdiff_t
UserDenseFactor Potential user customized dense factor
This is top user interface (C++); it is designed as a preconditioner that can be easily plugin other codes. There are two core member functions, 1) factorize a multilevel ILU preconditioner and 2) solve the preconditioner system. For computing preconditioner, the input can be either CCS or CRS, for solving, the input must be Array. However, be aware that both CCS/CRS and Array can be used as external data wrappers, thus one should not worry about input data duplications.
The following is a simple workflow for Builder.
#include <hifir.hpp>
using namespace hif;
using builder_t = HIF<double, int>;
using crs_t = builder_t::crs_type;
int main() {
  const auto A = wrap_const_crs(...);
  builder_t builder;
  builder.factorize(A);
  builder.solve(...);
}
Examples:
demo_complex.cpp, demo_fgmres.cpp, demo_fgmres_sparsifier.cpp, demo_gmreshif.cpp, demo_hifir.cpp, demo_mixedprecision.cpp, demo_multiply.cpp, demo_params.cpp, demo_simple.cpp, demo_sparsifier.cpp, demo_trans.cpp, and demo_verbose.cpp.
Definition at line 109 of file builder.hpp.
Member Typedef Documentation
array_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef Array<value_type> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::array_type
array type
Definition at line 112 of file builder.hpp.
boost_value_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef value_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::boost_value_type
high-precision value type
Definition at line 128 of file builder.hpp.
ccs_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef crs_type::other_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::ccs_type
ccs type
Definition at line 118 of file builder.hpp.
crs_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef CRS<value_type, index_type, indptr_type> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::crs_type
crs type
Definition at line 117 of file builder.hpp.
iarray_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef Array<index_type> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::iarray_type
index array
Definition at line 115 of file builder.hpp.
index_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef IndexType hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::index_type
index type
Definition at line 113 of file builder.hpp.
indptr_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef IndPtrType hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::indptr_type
index pointer
Definition at line 114 of file builder.hpp.
iparray_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef Array<indptr_type> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::iparray_type
indptr array
Definition at line 116 of file builder.hpp.
prec_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef precs_type::value_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::prec_type
single level prec
Definition at line 123 of file builder.hpp.
precs_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef Precs<value_type, index_type, indptr_type, UserDenseFactor> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::precs_type
multilevel preconditioner type
Definition at line 121 of file builder.hpp.
size_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef prec_type::size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::size_type
size type
Definition at line 124 of file builder.hpp.
value_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef ValueType hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::value_type
value type
Definition at line 111 of file builder.hpp.
work_array_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> typedef Array<boost_value_type> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::work_array_type
work array type
Definition at line 131 of file builder.hpp.
Member Function Documentation
_factorize_kernel()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class CsType , class CroutStreamer > void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_factorize_kernel (const CsType & A, const size_type m0, const Params & opts, iarray_type & row_sizes, iarray_type & col_sizes, const CroutStreamer & Crout_info, const int schur_threads = 1, const bool must_pivot = false) inline protected
Definition at line 523 of file builder.hpp.
clear()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::clear () inline
clear internal storage
Definition at line 247 of file builder.hpp.
empty()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> bool hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::empty () const inline
check empty or not
Definition at line 137 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), lhfcUpdate(), lhfczUpdate(), lhfdUpdate(), lhfsdUpdate(), lhfsUpdate(), lhfzUpdate(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::mmultiply(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nnz(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nnz_ef(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::rank(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::schur_rank(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::schur_size(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve_mrhs(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::stats().
factorize() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class CsType > void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::factorize (const CsType & A, const Params & params = DEFAULT_PARAMS, const size_type m0 = 0u) inline
factorize the HIF preconditioner
Template Parameters
CsType compressed storage input, either CRS or CCS
Parameters
[in] A input matrix
[in] params control parameters, using the default values
[in] m0 leading block size, if it's zero (default), then the routine will assume an asymmetric leading block.
See also
solve
Definition at line 264 of file builder.hpp.
factorize() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<bool IsCrs, class IndexType_ , class ValueType_ , class IndPtrType_ = std::ptrdiff_t> void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::factorize (const size_type n, const IndPtrType_ * indptr, const IndexType_ * indices, const ValueType_ * vals, const Params & params = DEFAULT_PARAMS, const size_type m0 = 0u) inline
factorize the HIF preconditioner with generic interface
Template Parameters
IsCrs if true, then the input compressed structure will be assumed to be CRS format
IndexType_ integer data type, e.g., int
ValueType_ value data type, e.g., double
IndPtrType_ index pointer type, default is std::ptrdiff_t
Parameters
[in] n size of system
[in] indptr index starting position array, must be length of n+1
[in] indices index value array, must be length of indptr[n]
[in] vals value array, same length as that of indices
[in] params control parameters, using the default values.
[in] m0 leading block size, if it's zero (default), then the routine will assume an asymmetric leading block.
This interface differs from the above one is that it takes plain-old-data types as input thus flexible. Notice that the integer and floating data types don't need to align with index_type and value_type, which aims for mixed-precision computation.
Definition at line 395 of file builder.hpp.
hifir() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class Matrix , class RhsType , class SolType > void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::hifir (const Matrix & A, const RhsType & b, const size_type N, SolType & x, const bool trans = false, const size_type r = static_cast<size_type>(-1)) const inline
solve with iterative refinement
Template Parameters
Matrix matrix type
RhsType right-hand side type
SolType solution type
Parameters
[in] A matrix operator
[in] b right-hand side vector
[in] N iteration count
[out] x solution vector
[in] trans (optional) transpose/Hermitian flag, default is false
[in] r (optional) dimension for back solve for last level default is its numerical rank
Definition at line 466 of file builder.hpp.
hifir() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class Matrix , class RhsType , class SolType > std::pair<size_type, int> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::hifir (const Matrix & A, const RhsType & b, const size_type N, const double * betas, SolType & x, const bool trans = false, const size_type r = static_cast<size_type>(-1)) const inline
solve with iterative refinement and residual bounds
Template Parameters
Matrix matrix type
RhsType right-hand side type
SolType solution type
Parameters
[in] A matrix operator
[in] b right-hand side vector
[in] N iteration count
[in] betas lower and upper bound of norms of residual
[out] x solution vector
[in] trans (optional) transpose/Hermitian flag, default is false
[in] r (optional) dimension for back solve for last level default is its numerical rank
Returns
Number of refinements and flag. If flag == 0, then it converges; if flag > 0, then it diverges; otherwise, it reaches maxit bound.
Definition at line 489 of file builder.hpp.
levels()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::levels () const inline
check number of levels
Note
This function takes since C++11
Definition at line 141 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::_factorize_kernel(), lhfcGetLevels(), lhfdGetLevels(), lhfsGetLevels(), lhfzGetLevels(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::prec().
mmultiply()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class RhsType , class SolType > void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::mmultiply (const RhsType & x, SolType & y, const bool trans = false, const size_type r = 0u) const inline
compute
Template Parameters
RhsType right-hand side type
SolType solution type
Parameters
[in] x right-hand side vector
[out] y solution vector
[in] trans (optional) transpose/Hermitian flag (default is false)
[in] r (optional) dimension for back solve for last level default is its numerical rank
Definition at line 510 of file builder.hpp.
ncols()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::ncols () const inline
get number of columns
Definition at line 202 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::rank().
nnz()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nnz () const inline
compute the overall nnz of the multilevel preconditioners
Definition at line 158 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), lhfcGetNnz(), lhfdGetNnz(), lhfsGetNnz(), lhfzGetNnz(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nnz_ldu().
nnz_ef()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nnz_ef () const inline
compute the nnz in E and F components
Definition at line 187 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nnz_ldu().
nnz_ldu()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nnz_ldu () const inline
compute the nnz in L, D, and U
Definition at line 196 of file builder.hpp.
nrows()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows () const inline
get number of rows
Definition at line 199 of file builder.hpp.
Referenced by lhfcApply(), lhfcUpdate(), lhfczApply(), lhfczUpdate(), lhfdApply(), lhfdUpdate(), lhfsApply(), lhfsdApply(), lhfsdUpdate(), lhfsUpdate(), lhfzApply(), lhfzUpdate(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::rank().
prec()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> const prec_type& hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::prec (const size_type level) const inline
get constant reference to a specific level
Note
This function takes linear time complexity
Definition at line 238 of file builder.hpp.
precs() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> const precs_type& hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::precs () const inline
get constant reference to preconditioners
Definition at line 152 of file builder.hpp.
precs() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> precs_type& hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::precs () inline
get normal reference to preconditioners
Definition at line 155 of file builder.hpp.
rank()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::rank () const inline
get the numerical rank
Definition at line 167 of file builder.hpp.
schur_rank()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::schur_rank () const inline
get the numerical rank for last level (dense Schur complement)
Definition at line 175 of file builder.hpp.
Referenced by lhfcGetSchurRank(), lhfdGetSchurRank(), lhfsGetSchurRank(), and lhfzGetSchurRank().
schur_size()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::schur_size () const inline
get the Schur complement size
Definition at line 181 of file builder.hpp.
Referenced by lhfcGetSchurSize(), lhfdGetSchurSize(), lhfsGetSchurSize(), and lhfzGetSchurSize().
solve()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class RhsType , class SolType > void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::solve (const RhsType & b, SolType & x, const bool trans = false, const size_type r = 0u) const inline
solve
Template Parameters
RhsType right-hand side type
SolType solution type
Parameters
[in] b right-hand side vector
[out] x solution vector
[in] trans (optional) transpose/Hermitian flag (default is false)
[in] r (optional) dimension for back solve for last level efault is its numerical rank
Definition at line 417 of file builder.hpp.
solve_mrhs()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> template<class RhsValueType , class SolValueType , size_type Nrhs> void hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::solve_mrhs (const Array< std::array< RhsValueType, Nrhs >> & b, Array< std::array< SolValueType, Nrhs >> & x, const size_type r = 0u) const inline
solve (multiple RHS)
Template Parameters
RhsValueType right-hand-side (RHS) value type
SolValueType solution value type
Nrhs number of RHS
Parameters
[in] b right-hand side vector
[out] x solution vector
[in] r (optional) dimension for back solve for last level default is its numerical rank
Definition at line 441 of file builder.hpp.
stats()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::stats (const size_type entry) const inline
get the stats
Parameters
[in] entry statistic entry
Currently, the following stats are available:
0: total deferrals
1: dynamic deferrals
2: dynamic deferrals due to bad diagonals
3: dynamic deferrals due to bad conditioning
4: total droppings
5: droppings due to space-controling Notice that entry 0 subtract entry 1 is the static deferrals, which are due to zero diagonals that occurs when applying symmetric preprocessing.
Definition at line 217 of file builder.hpp.
Member Data Documentation
_ir
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> IterRefine<boost_value_type> hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_ir protected
high-precision iterative refinement
Definition at line 591 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::clear(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::hifir().
_ncols
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_ncols protected
number of columns from user input
Definition at line 590 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::ncols().
_nrows
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_nrows protected
number of rows from user input
Definition at line 589 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nrows().
_prec_work
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> work_array_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_prec_work mutable protected
preconditioner work space for solving
Definition at line 586 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::clear(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::mmultiply(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve_mrhs().
_precs
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> precs_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_precs protected
multilevel preconditioners
Definition at line 585 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::_factorize_kernel(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::clear(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::empty(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::levels(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::mmultiply(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nnz(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::nnz_ef(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::prec(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::precs(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve_mrhs().
_stats
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> size_type hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::_stats[6] protected
statistics
Definition at line 588 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::_factorize_kernel(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::factorize(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::stats().
nsp
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> NspFilterPtr hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nsp
null space filter
Definition at line 498 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::clear(), hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve_mrhs().
nsp_tran
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t, template< class > class UserDenseFactor = DefaultDenseSolver> NspFilterPtr hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nsp_tran
transpose null space filter (left null space)
Definition at line 499 of file builder.hpp.
Referenced by hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::clear(), and hif::HIF< std::complex< float >, LhfInt, LhfIndPtr >::solve().
The documentation for this class was generated from the following file:
builder.hpp