HIFIR: hif::amd::AMD< Int > Class Template Reference
hif::amd::AMD< Int > Class Template Reference
Preprocessing
kernels for approxmiated minimum degree orderingThis class contains only static member functions, which are extracted and template-ized from original SuiteSparse AMD implementation.
#include <amd.hpp>
Static Public Member Functions
static Int * AMD_malloc (size_t len, size_t n)
static void AMD_free (void *ptr)
static void defaults (double *Control)
template<class OStream >
static OStream & control (OStream &s, double Control[])
template<class OStream >
static OStream & info (OStream &s, double *Info)
static Int post_tree (Int root, Int k, Int *Child, const Int *Sibling, Int *Order, Int *Stack)
static void postorder (Int nn, Int *Parent, Int *Nv, Int *Fsize, Int *Order, Int *Child, Int *Sibling, Int *Stack)
static void two (Int n, Int *Pe, Int *Iw, Int *Len, Int iwlen, Int pfree, Int *Nv, Int *Next, Int *Last, Int *Head, Int *Elen, Int *Degree, Int *W, double *Control, double *Info)
static void one (Int n, const Int *Ap, const Int *Ai, Int *P, Int *Pinv, Int *Len, Int slen, Int *S, double *Control, double *Info)
static size_t aat (Int n, const Int *Ap, const Int *Ai, Int *Len, Int *Tp, double *Info)
static Int valid (Int n_row, Int n_col, const Int *Ap, const Int *Ai)
static void preprocess (Int n, const Int *Ap, const Int *Ai, Int *Rp, Int *Ri, Int *W, Int *Flag)
static Int order (Int n, const Int *Ap, const Int *Ai, Int *P, double *Control, double *Info)
Static Public Attributes
static constexpr Int EMPTY = static_cast<Int>(-1)
static constexpr Int Int_MAX = std::numeric_limits<Int>::max()
Detailed Description
template<class Int>
class hif::amd::AMD< Int >
kernels for approxmiated minimum degree ordering
This class contains only static member functions, which are extracted and template-ized from original SuiteSparse AMD implementation.
Definition at line 114 of file amd.hpp.
Member Function Documentation
aat()
template<class Int > static size_t hif::amd::AMD< Int >::aat (Int n, const Int * Ap, const Int * Ai, Int * Len, Int * Tp, double * Info) inline static
Definition at line 873 of file amd.hpp.
References hif::amd::AMD< Int >::EMPTY.
Referenced by hif::amd::AMD< Int >::order().
AMD_free()
template<class Int > static void hif::amd::AMD< Int >::AMD_free (void * ptr) inline static
Definition at line 123 of file amd.hpp.
Referenced by hif::amd::AMD< Int >::order().
AMD_malloc()
template<class Int > static Int* hif::amd::AMD< Int >::AMD_malloc (size_t len, size_t n) inline static
Definition at line 119 of file amd.hpp.
Referenced by hif::amd::AMD< Int >::order().
control()
template<class Int > template<class OStream > static OStream& hif::amd::AMD< Int >::control (OStream & s, double Control[]) inline static
Definition at line 142 of file amd.hpp.
defaults()
template<class Int > static void hif::amd::AMD< Int >::defaults (double * Control) inline static
Definition at line 127 of file amd.hpp.
info()
template<class Int > template<class OStream > static OStream& hif::amd::AMD< Int >::info (OStream & s, double * Info) inline static
Definition at line 174 of file amd.hpp.
one()
template<class Int > static void hif::amd::AMD< Int >::one (Int n, const Int * Ap, const Int * Ai, Int * P, Int * Pinv, Int * Len, Int slen, Int * S, double * Control, double * Info) inline static
Definition at line 800 of file amd.hpp.
References hif::amd::AMD< Int >::two().
Referenced by hif::amd::AMD< Int >::order().
order()
template<class Int > static Int hif::amd::AMD< Int >::order (Int n, const Int * Ap, const Int * Ai, Int * P, double * Control, double * Info) inline static
Definition at line 1022 of file amd.hpp.
References hif::amd::AMD< Int >::aat(), hif::amd::AMD< Int >::AMD_free(), hif::amd::AMD< Int >::AMD_malloc(), hif::amd::AMD< Int >::EMPTY, hif::amd::AMD< Int >::Int_MAX, hif::amd::AMD< Int >::one(), hif::amd::AMD< Int >::preprocess(), and hif::amd::AMD< Int >::valid().
post_tree()
template<class Int > static Int hif::amd::AMD< Int >::post_tree (Int root, Int k, Int * Child, const Int * Sibling, Int * Order, Int * Stack) inline static
Definition at line 257 of file amd.hpp.
References hif::amd::AMD< Int >::EMPTY.
Referenced by hif::amd::AMD< Int >::postorder().
postorder()
template<class Int > static void hif::amd::AMD< Int >::postorder (Int nn, Int * Parent, Int * Nv, Int * Fsize, Int * Order, Int * Child, Int * Sibling, Int * Stack) inline static
Definition at line 289 of file amd.hpp.
References hif::amd::AMD< Int >::EMPTY, and hif::amd::AMD< Int >::post_tree().
Referenced by hif::amd::AMD< Int >::two().
preprocess()
template<class Int > static void hif::amd::AMD< Int >::preprocess (Int n, const Int * Ap, const Int * Ai, Int * Rp, Int * Ri, Int * W, Int * Flag) inline static
Definition at line 984 of file amd.hpp.
References hif::amd::AMD< Int >::EMPTY.
Referenced by hif::amd::AMD< Int >::order().
two()
template<class Int > static void hif::amd::AMD< Int >::two (Int n, Int * Pe, Int * Iw, Int * Len, Int iwlen, Int pfree, Int * Nv, Int * Next, Int * Last, Int * Head, Int * Elen, Int * Degree, Int * W, double * Control, double * Info) inline static
Definition at line 349 of file amd.hpp.
References hif::amd::AMD< Int >::EMPTY, hif::amd::AMD< Int >::Int_MAX, and hif::amd::AMD< Int >::postorder().
Referenced by hif::amd::AMD< Int >::one().
valid()
template<class Int > static Int hif::amd::AMD< Int >::valid (Int n_row, Int n_col, const Int * Ap, const Int * Ai) inline static
Definition at line 953 of file amd.hpp.
References hif::amd::AMD< Int >::EMPTY.
Referenced by hif::amd::AMD< Int >::order().
Member Data Documentation
EMPTY
template<class Int > constexpr Int hif::amd::AMD< Int >::EMPTY = static_cast<Int>(-1) static
Definition at line 116 of file amd.hpp.
Referenced by hif::amd::AMD< Int >::aat(), hif::amd::AMD< Int >::order(), hif::amd::AMD< Int >::post_tree(), hif::amd::AMD< Int >::postorder(), hif::amd::AMD< Int >::preprocess(), hif::amd::AMD< Int >::two(), and hif::amd::AMD< Int >::valid().
Int_MAX
template<class Int > constexpr Int hif::amd::AMD< Int >::Int_MAX = std::numeric_limits<Int>::max() static
Definition at line 117 of file amd.hpp.
Referenced by hif::amd::AMD< Int >::order(), and hif::amd::AMD< Int >::two().
The documentation for this class was generated from the following file:
amd.hpp