HIFIR: hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType > Class Template Reference
hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType > Class Template Reference
Data Structures
Core of the compressed storage, including data and interfaces.
#include <CompressedStorage.hpp>
Public Types
typedef ValueType value_type
value type
typedef value_type * pointer
pointer type
typedef IndexType index_type
index type
typedef index_type * ipointer
index pointer
typedef IndPtrType indptr_type
index_pointer type
typedef indptr_type * ippointer
index_pointer pointer
typedef CompressedStorage this_type
this
typedef Array< ValueType > array_type
value array
typedef Array< IndexType > iarray_type
index array
typedef Array< IndPtrType > iparray_type
index pointer array
typedef array_type::size_type size_type
size type
typedef array_type::iterator v_iterator
value iterator
typedef array_type::const_iterator const_v_iterator
constant
typedef iarray_type::iterator i_iterator
index iterator
typedef iarray_type::const_iterator const_i_iterator
constant
typedef ValueTypeTrait< value_type >::value_type scalar_type
scalar (real) type
Public Member Functions
CompressedStorage ()
default constructor
CompressedStorage (const size_type n, ippointer ind_start, ipointer indices, pointer vals, bool wrap=false)
constructor with external data, either copy (default) or wrap
CompressedStorage (const size_type n, const size_type nnz=0u, bool reserve=true)
constructor for own data
CompressedStorage (const this_type &other, bool clone=false)
shallow copy constructor (default) or deep copy
CompressedStorage (this_type &&)=default
this_type & operator= (this_type &&)=default
this_type & operator= (const this_type &)=default
unsigned char status () const
check the status of the storage
size_type nnz () const
v_iterator val_begin (const size_type i)
v_iterator val_end (const size_type i)
const_v_iterator val_begin (const size_type i) const
const_v_iterator val_end (const size_type i) const
const_v_iterator val_cbegin (const size_type i) const
const_v_iterator val_cend (const size_type i) const
size_type nnz_in_primary (const size_type i) const
i_iterator ind_begin (const size_type i)
i_iterator ind_end (const size_type i)
const_i_iterator ind_begin (const size_type i) const
const_i_iterator ind_end (const size_type i) const
const_i_iterator ind_cbegin (const size_type i) const
const_i_iterator ind_cend (const size_type i) const
iarray_type & inds ()
const iarray_type & inds () const
iparray_type & ind_start ()
const iparray_type & ind_start () const
const size_type primary_size () const
void reserve (const size_type nnz)
reserve space for nnz
template<bool IsRow>
void check_validity (const size_type other_size) const
check the validity of a matrix
Protected Member Functions
void _begin_assemble ()
begin assemble rows
void _end_assemble ()
finish assembling process
void _push_back_primary_empty (const size_type ii)
push back an empty entry
template<class Iter , class ValueArray >
void _push_back_primary (const size_type ii, Iter first, Iter last, const ValueArray &v)
push back a SORTED index list to _indices
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void _push_back_primary (const size_type ii, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back two SORTED index lists to _indices
size_type _nnz (const size_type i) const
check local number of nonzeros
i_iterator _ind_begin (const size_type i)
i_iterator _ind_end (const size_type i)
const_i_iterator _ind_begin (const size_type i) const
const_i_iterator _ind_end (const size_type i) const
const_i_iterator _ind_cbegin (const size_type i) const
const_i_iterator _ind_cend (const size_type i) const
template<bool IsSecond>
void _split (const size_type m, const indptr_type *start, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split against secondary size
template<bool IsSecond>
void _split (const size_type m, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split against secondary size
template<bool IsSecond>
void _split_dual (const size_type m, const size_type n, const indptr_type *start, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split and store to the counterpart type
template<bool IsSecond>
void _split_dual (const size_type m, const size_type n, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split and store to the counterpart type
template<bool DoValue, bool OnlyLeading>
void _compute_perm (const iarray_type &p, const iarray_type &qt, const size_type leading, iparray_type &indptr, iarray_type &indices, array_type &vals) const
construct permutated matrix
void _extract_leading_struct (const size_type m, iparray_type &indptr, iarray_type &indices) const
extract leading block structure
void _extract_leading (const size_type m, iparray_type &indptr, iarray_type &indices, array_type &vals) const
extract leading block
void _destroy ()
destroy the memory explicitly
size_type _prune (const size_type n, scalar_type eps=0, const bool shrink=false)
filter out small values
Protected Attributes
iparray_type _ind_start
index pointer array, size of n+1
iarray_type _indices
index array, size of nnz
array_type _vals
numerical data array, size of nnz
size_type _psize
primary size
Detailed Description
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t>
class hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
Core of the compressed storage, including data and interfaces.
Template Parameters
ValueType value type, e.g. double, float, etc
IndexType index used, e.g. int, long, etc
IndPtrType index pointer used, default is std::ptrdiff_t
Definition at line 55 of file CompressedStorage.hpp.
Member Typedef Documentation
array_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef Array<ValueType> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::array_type
value array
Definition at line 64 of file CompressedStorage.hpp.
const_i_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef iarray_type::const_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::const_i_iterator
constant
Definition at line 71 of file CompressedStorage.hpp.
const_v_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef array_type::const_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::const_v_iterator
constant
Definition at line 69 of file CompressedStorage.hpp.
i_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef iarray_type::iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::i_iterator
index iterator
Definition at line 70 of file CompressedStorage.hpp.
iarray_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef Array<IndexType> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::iarray_type
index array
Definition at line 65 of file CompressedStorage.hpp.
index_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef IndexType hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::index_type
index type
Definition at line 59 of file CompressedStorage.hpp.
indptr_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef IndPtrType hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::indptr_type
index_pointer type
Definition at line 61 of file CompressedStorage.hpp.
iparray_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef Array<IndPtrType> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::iparray_type
index pointer array
Definition at line 66 of file CompressedStorage.hpp.
ipointer
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef index_type* hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ipointer
index pointer
Definition at line 60 of file CompressedStorage.hpp.
ippointer
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef indptr_type* hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ippointer
index_pointer pointer
Definition at line 62 of file CompressedStorage.hpp.
pointer
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef value_type* hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::pointer
pointer type
Definition at line 58 of file CompressedStorage.hpp.
scalar_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef ValueTypeTrait<value_type>::value_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::scalar_type
scalar (real) type
Definition at line 72 of file CompressedStorage.hpp.
size_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef array_type::size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::size_type
size type
Definition at line 67 of file CompressedStorage.hpp.
this_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef CompressedStorage hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::this_type
this
Definition at line 63 of file CompressedStorage.hpp.
v_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef array_type::iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::v_iterator
value iterator
Definition at line 68 of file CompressedStorage.hpp.
value_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef ValueType hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::value_type
value type
Definition at line 57 of file CompressedStorage.hpp.
Constructor & Destructor Documentation
CompressedStorage() [1/5]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::CompressedStorage () inline
default constructor
Definition at line 80 of file CompressedStorage.hpp.
CompressedStorage() [2/5]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::CompressedStorage (const size_type n, ippointer ind_start, ipointer indices, pointer vals, bool wrap = false) inline
constructor with external data, either copy (default) or wrap
Parameters
[in] n primary size
[in] ind_start index starting positions
[in] indices index array
[in] vals value array
[in] wrap if false (default), then do copy
Definition at line 88 of file CompressedStorage.hpp.
CompressedStorage() [3/5]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::CompressedStorage (const size_type n, const size_type nnz = 0u, bool reserve = true) inline explicit
constructor for own data
Parameters
[in] n primary direction size
[in] nnz total number of nonzeros, default is 0
[in] reserve if true (default), reserve space instead of resize
See also
Array::resize, Array::reserve
Definition at line 100 of file CompressedStorage.hpp.
CompressedStorage() [4/5]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::CompressedStorage (const this_type & other, bool clone = false) inline
shallow copy constructor (default) or deep copy
Parameters
[in] other another compressed storage
[in] clone if false (default), then perform shallow copy
Definition at line 119 of file CompressedStorage.hpp.
CompressedStorage() [5/5]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::CompressedStorage (this_type &&) default
Member Function Documentation
_begin_assemble()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_begin_assemble () inline protected
begin assemble rows
Note
HIF only requires pushing back operations
See also
_end_assemble
Definition at line 227 of file CompressedStorage.hpp.
_compute_perm()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool DoValue, bool OnlyLeading> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_compute_perm (const iarray_type & p, const iarray_type & qt, const size_type leading, iparray_type & indptr, iarray_type & indices, array_type & vals) const inline protected
construct permutated matrix
Template Parameters
DoValue if true, then also compute the values
OnlyLeading if true, then will do a submatrix of leading block
Parameters
[in] p perm to origin mapping
[in] qt origin to perm mapping
[in] leading leading block size
[out] indptr index pointer array
[out] indices index array
[out] vals numerical value array
Definition at line 547 of file CompressedStorage.hpp.
_destroy()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_destroy () inline protected
destroy the memory explicitly
Definition at line 647 of file CompressedStorage.hpp.
_end_assemble()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_end_assemble () inline protected
finish assembling process
See also
_begin_assemble
Definition at line 237 of file CompressedStorage.hpp.
_extract_leading()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_extract_leading (const size_type m, iparray_type & indptr, iarray_type & indices, array_type & vals) const inline protected
extract leading block
Parameters
[in] m leading block size
[out] indptr index pointer array
[out] indices index array
[out] vals numerical value array
Definition at line 636 of file CompressedStorage.hpp.
_extract_leading_struct()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_extract_leading_struct (const size_type m, iparray_type & indptr, iarray_type & indices) const inline protected
extract leading block structure
Parameters
[in] m leading block size
[out] indptr index pointer array
[out] indices index array
Definition at line 607 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_extract_leading().
_ind_begin() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_begin (const size_type i) inline protected
Definition at line 349 of file CompressedStorage.hpp.
_ind_begin() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_begin (const size_type i) const inline protected
Definition at line 355 of file CompressedStorage.hpp.
_ind_cbegin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_cbegin (const size_type i) const inline protected
Definition at line 361 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_compute_perm(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_cend(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::ind_begin(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::ind_cbegin().
_ind_cend()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_cend (const size_type i) const inline protected
Definition at line 364 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_compute_perm(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::ind_cend(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::ind_end().
_ind_end() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_end (const size_type i) inline protected
Definition at line 352 of file CompressedStorage.hpp.
_ind_end() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_end (const size_type i) const inline protected
Definition at line 358 of file CompressedStorage.hpp.
_nnz()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_nnz (const size_type i) const inline protected
check local number of nonzeros
Parameters
[in] i i-th entry in primary direction
Definition at line 343 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_compute_perm(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_cend(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_end(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::nnz_in_primary(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_cend(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_end().
_prune()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_prune (const size_type n, scalar_type eps = 0, const bool shrink = false) inline protected
filter out small values
Parameters
[in] n number of columns for CRS and ros for CCS
[in] eps eliminating threshold, default is 0
[in] shrink if false (default), then do not shrink memory
Returns
total elminated entries
Definition at line 659 of file CompressedStorage.hpp.
_push_back_primary() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Iter , class ValueArray > void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_push_back_primary (const size_type ii, Iter first, Iter last, const ValueArray & v) inline protected
push back a SORTED index list to _indices
Template Parameters
Iter iterator type
ValueArray dense value array
Parameters
[in] ii ii-th entry in primary direction
[in] first starting iterator
[in] last ending iterator
[in] v dense value array, the value can be queried from indices
Warning
The indices are assumed to be sorted
Definition at line 271 of file CompressedStorage.hpp.
_push_back_primary() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 > void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_push_back_primary (const size_type ii, Iter1 first1, Iter1 last1, const ValueArray1 & v1, Iter2 first2, Iter2 last2, const ValueArray2 & v2) inline protected
push back two SORTED index lists to _indices
Template Parameters
Iter1 iterator type 1
ValueArray1 dense value array 1
Iter2 iterator type 2
ValueArray2 dense value array 2
Parameters
[in] ii ii-th entry in primary direction
[in] first1 starting iterator
[in] last1 ending iterator
[in] v1 dense value array, the value can be queried from indices
[in] first2 starting iterator
[in] last2 ending iterator
[in] v2 dense value array, the value can be queried from indices
Warning
The indices are assumed to be sorted
Definition at line 308 of file CompressedStorage.hpp.
_push_back_primary_empty()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_push_back_primary_empty (const size_type ii) inline protected
push back an empty entry
Parameters
[in] ii ii-th entry in primary direction
Definition at line 255 of file CompressedStorage.hpp.
_split() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_split (const size_type m, const indptr_type * start, iparray_type & indptr, iarray_type & indices, array_type & vals) const inline protected
split against secondary size
Template Parameters
IsSecond if true, then extract the second part
Parameters
[in] m size split against to
[in] start position start array
[out] indptr index start array
[out] indices index value array
[out] vals values
Definition at line 376 of file CompressedStorage.hpp.
_split() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_split (const size_type m, iparray_type & indptr, iarray_type & indices, array_type & vals) const inline protected
split against secondary size
Template Parameters
IsSecond if true, then extract the second part
Parameters
[in] m size split against to
[out] indptr index start array
[out] indices index value array
[out] vals values
Definition at line 429 of file CompressedStorage.hpp.
_split_dual() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_split_dual (const size_type m, const size_type n, const indptr_type * start, iparray_type & indptr, iarray_type & indices, array_type & vals) const inline protected
split and store to the counterpart type
Template Parameters
IsSecond if true, then extract the second part
Parameters
[in] m size split against to
[in] n overall size of the secondary direction
[in] start position start array
[out] indptr index start array
[out] indices index value array
[out] vals values
Definition at line 455 of file CompressedStorage.hpp.
_split_dual() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_split_dual (const size_type m, const size_type n, iparray_type & indptr, iarray_type & indices, array_type & vals) const inline protected
split and store to the counterpart type
Template Parameters
IsSecond if true, then extract the second part
Parameters
[in] m size split against to
[in] n overall size of the secondary direction
[out] indptr index start array
[out] indices index value array
[out] vals values
Definition at line 525 of file CompressedStorage.hpp.
check_validity()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsRow> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::check_validity (const size_type other_size) const inline
check the validity of a matrix
Template Parameters
IsRow is row major, mainly for error message
Parameters
[in] other_size size in secondary entry, column size for CRS and row size for CCS
Definition at line 193 of file CompressedStorage.hpp.
ind_begin() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_begin (const size_type i) inline
Definition at line 160 of file CompressedStorage.hpp.
ind_begin() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_begin (const size_type i) const inline
Definition at line 162 of file CompressedStorage.hpp.
ind_cbegin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_cbegin (const size_type i) const inline
Definition at line 168 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_extract_leading_struct().
ind_cend()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_cend (const size_type i) const inline
Definition at line 171 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_extract_leading_struct().
ind_end() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_end (const size_type i) inline
Definition at line 161 of file CompressedStorage.hpp.
ind_end() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_end (const size_type i) const inline
Definition at line 165 of file CompressedStorage.hpp.
ind_start() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> iparray_type& hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_start () inline
Definition at line 176 of file CompressedStorage.hpp.
ind_start() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const iparray_type& hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::ind_start () const inline
Definition at line 177 of file CompressedStorage.hpp.
inds() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> iarray_type& hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::inds () inline
Definition at line 174 of file CompressedStorage.hpp.
inds() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const iarray_type& hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::inds () const inline
Definition at line 175 of file CompressedStorage.hpp.
nnz()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::nnz () const inline
Definition at line 135 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_prune(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity().
nnz_in_primary()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::nnz_in_primary (const size_type i) const inline
Definition at line 159 of file CompressedStorage.hpp.
operator=() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> this_type& hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::operator= (this_type &&) default
operator=() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> this_type& hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::operator= (const this_type &) default
primary_size()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::primary_size () const inline
Definition at line 178 of file CompressedStorage.hpp.
reserve()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::reserve (const size_type nnz) inline
reserve space for nnz
Parameters
[in] nnz total number of nonzeros
Note
This function only reserves spaces for _indices and _vals
Definition at line 183 of file CompressedStorage.hpp.
status()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> unsigned char hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::status () const inline
check the status of the storage
Returns
either DATA_UNDEF, DATA_WRAP, or DATA_OWN
Note
The status should be consistent for all three arrays.
Definition at line 134 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::nnz().
val_begin() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> v_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::val_begin (const size_type i) inline
Definition at line 141 of file CompressedStorage.hpp.
val_begin() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_v_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::val_begin (const size_type i) const inline
Definition at line 147 of file CompressedStorage.hpp.
val_cbegin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_v_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::val_cbegin (const size_type i) const inline
Definition at line 153 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_compute_perm(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_extract_leading(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_cend().
val_cend()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_v_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::val_cend (const size_type i) const inline
Definition at line 156 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split().
val_end() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> v_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::val_end (const size_type i) inline
Definition at line 144 of file CompressedStorage.hpp.
val_end() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_v_iterator hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::val_end (const size_type i) const inline
Definition at line 150 of file CompressedStorage.hpp.
Member Data Documentation
_ind_start
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> iparray_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_ind_start protected
index pointer array, size of n+1
Definition at line 728 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_begin_assemble(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_destroy(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_end_assemble(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_begin(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_cbegin(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_nnz(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_prune(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_push_back_primary(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_push_back_primary_empty(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::CompressedStorage(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::ind_start(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::nnz(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_begin(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_cbegin().
_indices
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> iarray_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_indices protected
index array, size of nnz
Definition at line 729 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_begin_assemble(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_destroy(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_extract_leading_struct(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_begin(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_ind_cbegin(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_prune(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_push_back_primary(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::CompressedStorage(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::inds(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::reserve(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::status().
_psize
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_psize protected
primary size
Definition at line 731 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_begin_assemble(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_compute_perm(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_destroy(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_end_assemble(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_prune(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::CompressedStorage(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::primary_size().
_vals
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> array_type hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >::_vals protected
numerical data array, size of nnz
Definition at line 730 of file CompressedStorage.hpp.
Referenced by hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_begin_assemble(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_destroy(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_prune(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_push_back_primary(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::_split_dual(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::check_validity(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::CompressedStorage(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::reserve(), hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_begin(), and hif::internal::CompressedStorage< value_type, index_type, IndPtrType >::val_cbegin().
The documentation for this class was generated from the following file:
CompressedStorage.hpp