HIFIR: hif::Array< T > Class Template Reference
hif::Array< T > Class Template Reference
Data Structures
Core data structure used in compressed storage.
#include <Array.hpp>
Public Types
typedef T value_type
value type
typedef T * pointer
corresponding pointer type
typedef T & reference
corresponding lvalue reference
typedef pointer iterator
just use pointer for iterator
typedef const T * const_pointer
pointer to constant
typedef const T & const_reference
constant reference
typedef const_pointer const_iterator
constant iterator
typedef std::size_t size_type
size type, use std::size_t
Public Member Functions
Array ()
default constructor
Array (const size_type n)
constructor with owned data
Array (const size_type n, const value_type v)
similary to Array(n) but with uniform value initialization
Array (const size_type n, pointer data, bool wrap=false)
constructor for copying or wrapping external data
template<class V >
Array (const Array< V > &other)
constructor for copying a foreign array, useful in type conversion
~Array ()
destructor, handle shallow copy and external data
Array (const Array &other, bool clone=false)
constructor for shallow or deep copy
Array (Array &&other)
move constructor (steal)
Array & operator= (const Array &other)
shallow assignment
Array & operator= (Array &&other)
move assignment
reference operator[] (const size_type i)
accessing data position i
const_reference operator[] (const size_type i) const
accessing data position i
reference at (const size_type i)
const_reference at (const size_type i) const
pointer data ()
const_pointer data () const
size_type size () const
size_type capacity () const
bool empty () const
unsigned char status () const
reference front ()
reference back ()
const_reference front () const
const_reference back () const
void swap (Array &rhs)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
void resize (const size_type n, bool presv=true)
resize an Array with new size
void reserve (const size_type n)
reserve space for Array
void push_back (const value_type v)
append a new value
template<class Iter >
void push_back (Iter first, Iter last)
append a new range
template<class Iter >
void push_back_n (Iter first, const size_type n)
append with leading position and known size
void read_mm (const char *fname)
Read data from a MatrixMarket file.
void write_mm (const char *fname) const
Write data to a MatrixMarket file.
Static Public Member Functions
static Array from_mm (const char *fname)
Read data from a MatrixMarket file.
Protected Attributes
pointer _data
data pointer
size_type _size
array size
size_type _cap
array capacity
unsigned char _status
array status, see enum above
Private Attributes
_RefCount * _counts
reference counter
Friends
template<class _T >
void steal_array_ownership (Array< _T > &arr, typename Array< _T >::pointer &data, typename Array< _T >::size_type &size, typename Array< _T >::size_type &cap)
Detailed Description
template<class T>
class hif::Array< T >
Core data structure used in compressed storage.
Template Parameters
T value type
Compared to std::vector, Array allows one to wrap external data, which is a necessary feature for this package. In addition, we allow shallow copy instead of deepcopy used in std::vector.
Definition at line 73 of file Array.hpp.
Member Typedef Documentation
const_iterator
template<class T> typedef const_pointer hif::Array< T >::const_iterator
constant iterator
Definition at line 81 of file Array.hpp.
const_pointer
template<class T> typedef const T* hif::Array< T >::const_pointer
pointer to constant
Definition at line 79 of file Array.hpp.
const_reference
template<class T> typedef const T& hif::Array< T >::const_reference
constant reference
Definition at line 80 of file Array.hpp.
iterator
template<class T> typedef pointer hif::Array< T >::iterator
just use pointer for iterator
Definition at line 78 of file Array.hpp.
pointer
template<class T> typedef T* hif::Array< T >::pointer
corresponding pointer type
Definition at line 76 of file Array.hpp.
reference
template<class T> typedef T& hif::Array< T >::reference
corresponding lvalue reference
Definition at line 77 of file Array.hpp.
size_type
template<class T> typedef std::size_t hif::Array< T >::size_type
size type, use std::size_t
Definition at line 82 of file Array.hpp.
value_type
template<class T> typedef T hif::Array< T >::value_type
value type
Definition at line 75 of file Array.hpp.
Constructor & Destructor Documentation
Array() [1/7]
template<class T> hif::Array< T >::Array () inline
default constructor
Definition at line 117 of file Array.hpp.
Array() [2/7]
template<class T> hif::Array< T >::Array (const size_type n) inline explicit
constructor with owned data
Parameters
[in] n length of the array
See also
DATA_OWN
Definition at line 127 of file Array.hpp.
Referenced by compute_error(), compute_relres(), and get_user_data().
Array() [3/7]
template<class T> hif::Array< T >::Array (const size_type n, const value_type v) inline
similary to Array(n) but with uniform value initialization
Parameters
[in] n length of the array
[in] v init value
Definition at line 144 of file Array.hpp.
Array() [4/7]
template<class T> hif::Array< T >::Array (const size_type n, pointer data, bool wrap = false) inline
constructor for copying or wrapping external data
Parameters
[in] n size of array
[in] data external data
[in] wrap flag to indicate wrapping or copying (optional)
If wrap is true, then a wrapper Array will be constructed, as a result, you cannot resize and reserve data.
Definition at line 155 of file Array.hpp.
Array() [5/7]
template<class T> template<class V > hif::Array< T >::Array (const Array< V > & other) inline explicit
constructor for copying a foreign array, useful in type conversion
Template Parameters
V foreign value type
Parameters
other another array
Definition at line 178 of file Array.hpp.
~Array()
template<class T> hif::Array< T >::~Array () inline
destructor, handle shallow copy and external data
Definition at line 193 of file Array.hpp.
Array() [6/7]
template<class T> hif::Array< T >::Array (const Array< T > & other, bool clone = false) inline
constructor for shallow or deep copy
Note
the default copy constructor is shallow
Parameters
[in] other another Array
[in] clone if true, then do deep copy, default is false
Definition at line 214 of file Array.hpp.
Array() [7/7]
template<class T> hif::Array< T >::Array (Array< T > && other) inline
move constructor (steal)
Parameters
[in] other temp Array
Definition at line 247 of file Array.hpp.
Member Function Documentation
at() [1/2]
template<class T> reference hif::Array< T >::at (const size_type i) inline
Definition at line 308 of file Array.hpp.
at() [2/2]
template<class T> const_reference hif::Array< T >::at (const size_type i) const inline
Definition at line 312 of file Array.hpp.
back() [1/2]
template<class T> reference hif::Array< T >::back () inline
Definition at line 325 of file Array.hpp.
back() [2/2]
template<class T> const_reference hif::Array< T >::back () const inline
Definition at line 327 of file Array.hpp.
begin() [1/2]
template<class T> iterator hif::Array< T >::begin () inline
Definition at line 337 of file Array.hpp.
Referenced by get_user_data().
begin() [2/2]
template<class T> const_iterator hif::Array< T >::begin () const inline
Definition at line 338 of file Array.hpp.
capacity()
template<class T> size_type hif::Array< T >::capacity () const inline
Definition at line 321 of file Array.hpp.
cbegin()
template<class T> const_iterator hif::Array< T >::cbegin () const inline
Definition at line 341 of file Array.hpp.
Referenced by lhfcReadVector(), lhfdReadVector(), lhfsReadVector(), and lhfzReadVector().
cend()
template<class T> const_iterator hif::Array< T >::cend () const inline
Definition at line 342 of file Array.hpp.
Referenced by lhfcReadVector(), lhfdReadVector(), lhfsReadVector(), and lhfzReadVector().
data() [1/2]
template<class T> pointer hif::Array< T >::data () inline
Definition at line 318 of file Array.hpp.
data() [2/2]
template<class T> const_pointer hif::Array< T >::data () const inline
Definition at line 319 of file Array.hpp.
empty()
template<class T> bool hif::Array< T >::empty () const inline
Definition at line 322 of file Array.hpp.
Referenced by hif::QRCP< ValueType >::_multiply_nt(), hif::QRCP< ValueType >::_multiply_t(), hif::QRCP< ValueType >::_solve_nt(), hif::QRCP< ValueType >::_solve_t(), hif::LUP< ValueType >::solve(), and hif::LUP< ValueType >::solve_mrhs().
end() [1/2]
template<class T> iterator hif::Array< T >::end () inline
Definition at line 339 of file Array.hpp.
Referenced by get_user_data().
end() [2/2]
template<class T> const_iterator hif::Array< T >::end () const inline
Definition at line 340 of file Array.hpp.
from_mm()
template<class T> static Array hif::Array< T >::from_mm (const char * fname) inline static
Read data from a MatrixMarket file.
Parameters
[in] fname Input file name
Definition at line 110 of file Array.hpp.
Referenced by get_input_data(), get_user_data(), lhfcReadVector(), lhfdReadVector(), lhfsReadVector(), and lhfzReadVector().
front() [1/2]
template<class T> reference hif::Array< T >::front () inline
Definition at line 324 of file Array.hpp.
front() [2/2]
template<class T> const_reference hif::Array< T >::front () const inline
Definition at line 326 of file Array.hpp.
operator=() [1/2]
template<class T> Array& hif::Array< T >::operator= (const Array< T > & other) inline
shallow assignment
Parameters
[in] other rhs Array
Returns
lvalue reference of this
Definition at line 260 of file Array.hpp.
operator=() [2/2]
template<class T> Array& hif::Array< T >::operator= (Array< T > && other) inline
move assignment
Parameters
[in] other rhs temp Array
Returns
lvalue reference of this
Definition at line 277 of file Array.hpp.
Referenced by lhfcReadVector(), lhfdReadVector(), lhfsReadVector(), and lhfzReadVector().
operator[]() [1/2]
template<class T> reference hif::Array< T >::operator[] (const size_type i) inline
accessing data position i
Parameters
[in] i i-th position
Definition at line 295 of file Array.hpp.
Referenced by compute_error(), and compute_relres().
operator[]() [2/2]
template<class T> const_reference hif::Array< T >::operator[] (const size_type i) const inline
accessing data position i
Parameters
[in] i i-th position
Definition at line 302 of file Array.hpp.
Referenced by compute_error(), and compute_relres().
push_back() [1/2]
template<class T> void hif::Array< T >::push_back (const value_type v) inline
append a new value
Parameters
[in] v value to be append
Definition at line 407 of file Array.hpp.
push_back() [2/2]
template<class T> template<class Iter > void hif::Array< T >::push_back (Iter first, Iter last) inline
append a new range
Template Parameters
Iter iterator type
Parameters
[in] first starting iterator
[in] last ending iterator
See also
push_back_n
Warning
The behavior is undefined if this and last belong to this
Definition at line 419 of file Array.hpp.
push_back_n()
template<class T> template<class Iter > void hif::Array< T >::push_back_n (Iter first, const size_type n) inline
append with leading position and known size
Template Parameters
Iter iterator type
Parameters
[in] first starting position
[in] n length to append
Warning
The behavior is undefined if first belongs to this
Definition at line 433 of file Array.hpp.
read_mm()
template<class T> void hif::Array< T >::read_mm (const char * fname) inline
Read data from a MatrixMarket file.
Parameters
[in] fname Input file name
See also
write_mm
Note
Only the first column is loaded
Definition at line 443 of file Array.hpp.
reserve()
template<class T> void hif::Array< T >::reserve (const size_type n) inline
reserve space for Array
Parameters
[in] n capacity request
Warning
This function should not be called for external data
See also
resize
Definition at line 382 of file Array.hpp.
resize()
template<class T> void hif::Array< T >::resize (const size_type n, bool presv = true) inline
resize an Array with new size
Parameters
[in] n new size
[in] presv if true (default), then values will be preserved
Warning
This function should not be called for external data
See also
reserve
Definition at line 351 of file Array.hpp.
Referenced by hif::LUP< ValueType >::factorize(), hif::SYEIG< ValueType >::factorize(), hif::QRCP< ValueType >::factorize(), hif::Array< index_type >::push_back(), and hif::Array< index_type >::push_back_n().
size()
template<class T> size_type hif::Array< T >::size () const inline
Definition at line 320 of file Array.hpp.
Referenced by hif::QRCP< ValueType >::_multiply_nt(), hif::QRCP< ValueType >::_multiply_t(), hif::QRCP< ValueType >::_solve_nt(), hif::QRCP< ValueType >::_solve_t(), compute_error(), compute_relres(), lhfcReadVector(), lhfdReadVector(), lhfsReadVector(), and lhfzReadVector().
status()
template<class T> unsigned char hif::Array< T >::status () const inline
Definition at line 323 of file Array.hpp.
swap()
template<class T> void hif::Array< T >::swap (Array< T > & rhs) inline
Definition at line 328 of file Array.hpp.
write_mm()
template<class T> void hif::Array< T >::write_mm (const char * fname) const inline
Write data to a MatrixMarket file.
Parameters
[in] fname Output file name
See also
read_mm
Definition at line 448 of file Array.hpp.
Friends And Related Function Documentation
steal_array_ownership
template<class T> template<class _T > void steal_array_ownership (Array< _T > & arr, typename Array< _T >::pointer & data, typename Array< _T >::size_type & size, typename Array< _T >::size_type & cap) friend
Member Data Documentation
_cap
template<class T> size_type hif::Array< T >::_cap protected
array capacity
Definition at line 455 of file Array.hpp.
Referenced by hif::Array< index_type >::Array(), hif::Array< index_type >::capacity(), hif::Array< index_type >::operator=(), hif::Array< index_type >::reserve(), hif::Array< index_type >::resize(), hif::Array< index_type >::swap(), and hif::Array< index_type >::~Array().
_counts
template<class T> _RefCount* hif::Array< T >::_counts private
reference counter
Definition at line 459 of file Array.hpp.
Referenced by hif::Array< index_type >::Array(), hif::Array< index_type >::operator=(), hif::Array< index_type >::reserve(), hif::Array< index_type >::resize(), hif::Array< index_type >::swap(), and hif::Array< index_type >::~Array().
_data
template<class T> pointer hif::Array< T >::_data protected
data pointer
Definition at line 453 of file Array.hpp.
Referenced by hif::Array< index_type >::Array(), hif::Array< index_type >::at(), hif::Array< index_type >::back(), hif::Array< index_type >::begin(), hif::Array< index_type >::cbegin(), hif::Array< index_type >::cend(), hif::Array< index_type >::data(), hif::Array< index_type >::end(), hif::Array< index_type >::front(), hif::Array< index_type >::operator=(), hif::Array< index_type >::operator[](), hif::Array< index_type >::push_back(), hif::Array< index_type >::push_back_n(), hif::Array< index_type >::reserve(), hif::Array< index_type >::resize(), hif::Array< index_type >::swap(), and hif::Array< index_type >::~Array().
_size
template<class T> size_type hif::Array< T >::_size protected
array size
Definition at line 454 of file Array.hpp.
Referenced by hif::Array< index_type >::Array(), hif::Array< index_type >::at(), hif::Array< index_type >::back(), hif::Array< index_type >::cend(), hif::Array< index_type >::empty(), hif::Array< index_type >::end(), hif::Array< index_type >::operator=(), hif::Array< index_type >::push_back(), hif::Array< index_type >::push_back_n(), hif::Array< index_type >::reserve(), hif::Array< index_type >::resize(), hif::Array< index_type >::size(), hif::Array< index_type >::swap(), and hif::Array< index_type >::~Array().
_status
template<class T> unsigned char hif::Array< T >::_status protected
array status, see enum above
Definition at line 456 of file Array.hpp.
Referenced by hif::Array< index_type >::Array(), hif::Array< index_type >::operator=(), hif::Array< index_type >::reserve(), hif::Array< index_type >::resize(), hif::Array< index_type >::status(), hif::Array< index_type >::swap(), and hif::Array< index_type >::~Array().
The documentation for this class was generated from the following file:
Array.hpp