HIFIR: hif::CCS< ValueType, IndexType, IndPtrType > Class Template Reference
hif::CCS< ValueType, IndexType, IndPtrType > Class Template Reference
Data Structures
Compressed Column Storage (CCS) format for sparse matrices.
#include <CompressedStorage.hpp>
Public Types
typedef ValueType value_type
value type
typedef IndexType index_type
index type
typedef IndPtrType indptr_type
index_pointer type
typedef _base::array_type array_type
value array
typedef _base::iarray_type iarray_type
index array
typedef _base::iparray_type iparray_type
indptr array
typedef _base::size_type size_type
size type
typedef _base::pointer pointer
value pointer
typedef _base::ipointer ipointer
index pointer
typedef _base::ippointer ippointer
index_pointer pointer
typedef CRS< ValueType, IndexType, IndPtrType > other_type
crs type
typedef _base::i_iterator i_iterator
index iterator
typedef _base::const_i_iterator const_i_iterator
const index iterator
typedef _base::v_iterator v_iterator
value iterator
typedef _base::const_v_iterator const_v_iterator
const value iterator
Public Types inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
typedef ValueType value_type
value type
typedef value_type * pointer
pointer type
typedef IndexType index_type
index type
typedef index_type * ipointer
index pointer
typedef IndPtrType indptr_type
index_pointer type
typedef indptr_type * ippointer
index_pointer pointer
typedef CompressedStorage this_type
this
typedef Array< ValueType > array_type
value array
typedef Array< IndexType > iarray_type
index array
typedef Array< IndPtrType > iparray_type
index pointer array
typedef array_type::size_type size_type
size type
typedef array_type::iterator v_iterator
value iterator
typedef array_type::const_iterator const_v_iterator
constant
typedef iarray_type::iterator i_iterator
index iterator
typedef iarray_type::const_iterator const_i_iterator
constant
typedef ValueTypeTrait< value_type >::value_type scalar_type
scalar (real) type
Public Member Functions
CCS ()
default constructor
CCS (const size_type nrows, const size_type ncols, ippointer col_start, ipointer row_ind, pointer vals, bool wrap=false)
external data for matrix
CCS (const size_type n, ippointer col_start, ipointer row_ind, pointer vals, bool wrap=false)
external data for squared matrix
CCS (const size_type nrows, const size_type ncols, const size_type nnz=0u, bool reserve=true)
own data for ccs matrix
CCS (const CCS &other, bool clone=false)
shallow copy constructor (default) or make a clone
CCS (const other_type &crs)
make a CCS based on CRS input
CCS (CCS &&)=default
CCS & operator= (CCS &&)=default
CCS & operator= (const CCS &)=default
iparray_type & col_start ()
iarray_type & row_ind ()
array_type & vals ()
const iparray_type & col_start () const
const iarray_type & row_ind () const
const array_type & vals () const
size_type nrows () const
get number of rows
size_type ncols () const
get number of columns
void resize_nrows (const size_type nrows)
resize rows
void resize_ncols (const size_type ncols)
resize columns
void resize (const size_type nrows, const size_type ncols)
resize
void check_validity () const
check validity
size_type nnz_in_col (const size_type i) const
get local nnz per column
i_iterator row_ind_begin (const size_type i)
i_iterator row_ind_end (const size_type i)
const_i_iterator row_ind_begin (const size_type i) const
const_i_iterator row_ind_end (const size_type i) const
const_i_iterator row_ind_cbegin (const size_type i) const
const_i_iterator row_ind_cend (const size_type i) const
void begin_assemble_cols ()
begin assemble columns
void end_assemble_cols ()
finish assemble columns
void push_back_empty_col (const size_type col)
push back an empty column
template<class Iter , class ValueArray >
void push_back_col (const size_type col, Iter first, Iter last, const ValueArray &v)
push back a new column
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void push_back_col (const size_type col, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back a new column from two lists
template<class DiagArray >
void scale_diag_left (const DiagArray &s)
scale by a diagonal matrix from left
template<class DiagArray >
void scale_diag_right (const DiagArray &t)
scale by a diagonal matrix from right
template<class LeftDiagArray , class RightDiagArray >
void scale_diags (const LeftDiagArray &s, const RightDiagArray &t)
scale by two diagonal matrices from both lh and rh sides
template<class Vx , class Vy >
void multiply_nt_low (const Vx *x, Vy *y) const
matrix vector multiplication with different value type
template<class IArray , class OArray >
void multiply_nt (const IArray &x, OArray &y) const
matrix vector multiplication
template<size_type Nrhs, class Vx , class Vy >
void multiply_mrhs_nt_low (const Vx *x, Vy *y) const
matrix vector multiplication with different value type
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs_nt (const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y) const
matrix vector multiplication
template<class Vx , class Vy >
void multiply_t_low (const Vx *x, Vy *y) const
matrix transpose vector multiplication with different type
template<class IArray , class OArray >
void multiply_t (const IArray &x, OArray &y) const
matrix transpose vector multiplication
template<size_type Nrhs, class Vx , class Vy >
void multiply_mrhs_t_low (const Vx *x, Vy *y) const
matrix transpose vector multiplication with different type
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs_t (const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y) const
transpose matrix vector multiplication
template<class IArray , class OArray >
void multiply (const IArray &x, OArray &y, bool tran=false) const
matrix vector multiplication
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs (const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y, bool tran=false) const
matrix vector multiplication with multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_lower (RhsType &y) const
Assume as a strict lower matrix and solve with forward sub.
template<class InOutType , size_type Nrhs>
void solve_as_strict_lower_mrhs (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict lower matrix and solve with forward sub for multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_lower_tran (RhsType &y) const
Assume as a strict lower matrix and solve with transpose backward.
template<class InOutType , size_type Nrhs>
void solve_as_strict_lower_mrhs_tran (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict lower matrix and solve with transpose backward for multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_upper (RhsType &y) const
Assume as a strict upper matrix and solve with backward sub.
template<class InOutType , size_type Nrhs>
void solve_as_strict_upper_mrhs (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict upper matrix and solve with backward sub for multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_upper_tran (RhsType &y) const
Assume as a strict upper matrix and solve tranpose forward.
template<class InOutType , size_type Nrhs>
void solve_as_strict_upper_mrhs_tran (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict upper matrix and solve tranpose forward for multiple right-hand sides (RHS)
size_type read_bin (const char *fname)
read a native HIF binary file
void write_bin (const char *fname, const size_type=0) const
write to a native HIF binary file
void read_mm (const char *fname)
Read data from a MatrixMarket file.
void write_mm (const char *fname) const
Write data to a MatrixMarket file.
template<bool IsSecond>
CCS split (const size_type m) const
split against row
template<bool IsSecond>
CCS split (const size_type m, const iparray_type &start) const
split against row
std::pair< CCS, CCS > split (const size_type m) const
split against row
std::pair< CCS, CCS > split (const size_type m, const iparray_type &start) const
split against row
template<bool IsSecond>
other_type split_crs (const size_type m) const
split against row and store in CRS
template<bool IsSecond>
other_type split_crs (const size_type m, const iparray_type &start) const
split against row and store in CRS
std::pair< other_type, other_type > split_crs (const size_type m) const
split against row and store in CRS
std::pair< other_type, other_type > split_crs (const size_type m, const iparray_type &start) const
split against row and store in CRS
CCS compute_perm (const iarray_type &pt, const iarray_type &q, const size_type leading=0, const bool struct_only=false) const
compute permutation CCS
CCS extract_leading (const size_type m) const
extract leading block
void destroy ()
explicit destroy the data
size_type prune (const typename _base::scalar_type eps=0.0, const bool shrink=false)
prune tiny values
Public Member Functions inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
CompressedStorage ()
default constructor
CompressedStorage (const size_type n, ippointer ind_start, ipointer indices, pointer vals, bool wrap=false)
constructor with external data, either copy (default) or wrap
CompressedStorage (const size_type n, const size_type nnz=0u, bool reserve=true)
constructor for own data
CompressedStorage (const this_type &other, bool clone=false)
shallow copy constructor (default) or deep copy
CompressedStorage (this_type &&)=default
this_type & operator= (this_type &&)=default
this_type & operator= (const this_type &)=default
unsigned char status () const
check the status of the storage
size_type nnz () const
v_iterator val_begin (const size_type i)
v_iterator val_end (const size_type i)
const_v_iterator val_begin (const size_type i) const
const_v_iterator val_end (const size_type i) const
const_v_iterator val_cbegin (const size_type i) const
const_v_iterator val_cend (const size_type i) const
size_type nnz_in_primary (const size_type i) const
i_iterator ind_begin (const size_type i)
i_iterator ind_end (const size_type i)
const_i_iterator ind_begin (const size_type i) const
const_i_iterator ind_end (const size_type i) const
const_i_iterator ind_cbegin (const size_type i) const
const_i_iterator ind_cend (const size_type i) const
iarray_type & inds ()
const iarray_type & inds () const
iparray_type & ind_start ()
const iparray_type & ind_start () const
const size_type primary_size () const
void reserve (const size_type nnz)
reserve space for nnz
template<bool IsRow>
void check_validity (const size_type other_size) const
check the validity of a matrix
Static Public Member Functions
static CCS from_bin (const char *filename, size_type *m=nullptr)
read from a native HIF binary file
static CCS from_mm (const char *filename)
read from a MatrixMarket file
Static Public Attributes
static constexpr bool ROW_MAJOR = false
column major
Protected Attributes
size_type _nrows
number of rows
Protected Attributes inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
iparray_type _ind_start
index pointer array, size of n+1
iarray_type _indices
index array, size of nnz
array_type _vals
numerical data array, size of nnz
size_type _psize
primary size
Private Types
typedef internal::CompressedStorage< ValueType, IndexType, IndPtrType > _base
Additional Inherited Members
Protected Member Functions inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
void _begin_assemble ()
begin assemble rows
void _end_assemble ()
finish assembling process
void _push_back_primary_empty (const size_type ii)
push back an empty entry
template<class Iter , class ValueArray >
void _push_back_primary (const size_type ii, Iter first, Iter last, const ValueArray &v)
push back a SORTED index list to _indices
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void _push_back_primary (const size_type ii, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back two SORTED index lists to _indices
size_type _nnz (const size_type i) const
check local number of nonzeros
i_iterator _ind_begin (const size_type i)
i_iterator _ind_end (const size_type i)
const_i_iterator _ind_begin (const size_type i) const
const_i_iterator _ind_end (const size_type i) const
const_i_iterator _ind_cbegin (const size_type i) const
const_i_iterator _ind_cend (const size_type i) const
template<bool IsSecond>
void _split (const size_type m, const indptr_type *start, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split against secondary size
template<bool IsSecond>
void _split (const size_type m, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split against secondary size
template<bool IsSecond>
void _split_dual (const size_type m, const size_type n, const indptr_type *start, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split and store to the counterpart type
template<bool IsSecond>
void _split_dual (const size_type m, const size_type n, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split and store to the counterpart type
template<bool DoValue, bool OnlyLeading>
void _compute_perm (const iarray_type &p, const iarray_type &qt, const size_type leading, iparray_type &indptr, iarray_type &indices, array_type &vals) const
construct permutated matrix
void _extract_leading_struct (const size_type m, iparray_type &indptr, iarray_type &indices) const
extract leading block structure
void _extract_leading (const size_type m, iparray_type &indptr, iarray_type &indices, array_type &vals) const
extract leading block
void _destroy ()
destroy the memory explicitly
size_type _prune (const size_type n, scalar_type eps=0, const bool shrink=false)
filter out small values
Detailed Description
template<class ValueType, class IndexType, class IndPtrType>
class hif::CCS< ValueType, IndexType, IndPtrType >
Compressed Column Storage (CCS) format for sparse matrices.
Template Parameters
ValueType numerical value type, e.g. double, float, etc
IndexType index type, e.g. int, long, etc
Definition at line 814 of file CompressedStorage.hpp.
Member Typedef Documentation
_base
template<class ValueType , class IndexType , class IndPtrType > typedef internal::CompressedStorage<ValueType, IndexType, IndPtrType> hif::CCS< ValueType, IndexType, IndPtrType >::_base private
Definition at line 1806 of file CompressedStorage.hpp.
array_type
template<class ValueType , class IndexType , class IndPtrType > typedef _base::array_type hif::CCS< ValueType, IndexType, IndPtrType >::array_type
value array
Definition at line 1812 of file CompressedStorage.hpp.
const_i_iterator
template<class ValueType , class IndexType , class IndPtrType > typedef _base::const_i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::const_i_iterator
const index iterator
Definition at line 1821 of file CompressedStorage.hpp.
const_v_iterator
template<class ValueType , class IndexType , class IndPtrType > typedef _base::const_v_iterator hif::CCS< ValueType, IndexType, IndPtrType >::const_v_iterator
const value iterator
Definition at line 1824 of file CompressedStorage.hpp.
i_iterator
template<class ValueType , class IndexType , class IndPtrType > typedef _base::i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::i_iterator
index iterator
Definition at line 1820 of file CompressedStorage.hpp.
iarray_type
template<class ValueType , class IndexType , class IndPtrType > typedef _base::iarray_type hif::CCS< ValueType, IndexType, IndPtrType >::iarray_type
index array
Definition at line 1813 of file CompressedStorage.hpp.
index_type
template<class ValueType , class IndexType , class IndPtrType > typedef IndexType hif::CCS< ValueType, IndexType, IndPtrType >::index_type
index type
Definition at line 1810 of file CompressedStorage.hpp.
indptr_type
template<class ValueType , class IndexType , class IndPtrType > typedef IndPtrType hif::CCS< ValueType, IndexType, IndPtrType >::indptr_type
index_pointer type
Definition at line 1811 of file CompressedStorage.hpp.
iparray_type
template<class ValueType , class IndexType , class IndPtrType > typedef _base::iparray_type hif::CCS< ValueType, IndexType, IndPtrType >::iparray_type
indptr array
Definition at line 1814 of file CompressedStorage.hpp.
ipointer
template<class ValueType , class IndexType , class IndPtrType > typedef _base::ipointer hif::CCS< ValueType, IndexType, IndPtrType >::ipointer
index pointer
Definition at line 1817 of file CompressedStorage.hpp.
ippointer
template<class ValueType , class IndexType , class IndPtrType > typedef _base::ippointer hif::CCS< ValueType, IndexType, IndPtrType >::ippointer
index_pointer pointer
Definition at line 1818 of file CompressedStorage.hpp.
other_type
template<class ValueType , class IndexType , class IndPtrType > typedef CRS<ValueType, IndexType, IndPtrType> hif::CCS< ValueType, IndexType, IndPtrType >::other_type
crs type
Definition at line 1819 of file CompressedStorage.hpp.
pointer
template<class ValueType , class IndexType , class IndPtrType > typedef _base::pointer hif::CCS< ValueType, IndexType, IndPtrType >::pointer
value pointer
Definition at line 1816 of file CompressedStorage.hpp.
size_type
template<class ValueType , class IndexType , class IndPtrType > typedef _base::size_type hif::CCS< ValueType, IndexType, IndPtrType >::size_type
size type
Definition at line 1815 of file CompressedStorage.hpp.
v_iterator
template<class ValueType , class IndexType , class IndPtrType > typedef _base::v_iterator hif::CCS< ValueType, IndexType, IndPtrType >::v_iterator
value iterator
Definition at line 1823 of file CompressedStorage.hpp.
value_type
template<class ValueType , class IndexType , class IndPtrType > typedef ValueType hif::CCS< ValueType, IndexType, IndPtrType >::value_type
value type
Definition at line 1809 of file CompressedStorage.hpp.
Constructor & Destructor Documentation
CCS() [1/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS () inline
default constructor
Definition at line 1849 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
CCS() [2/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS (const size_type nrows, const size_type ncols, ippointer col_start, ipointer row_ind, pointer vals, bool wrap = false) inline
external data for matrix
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] col_start column index start array
[in] row_ind row indices
[in] vals value data
[in] wrap if false (default), then do copy
Definition at line 1858 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
CCS() [3/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS (const size_type n, ippointer col_start, ipointer row_ind, pointer vals, bool wrap = false) inline
external data for squared matrix
Parameters
[in] n number of rows and columns
[in] col_start column index start array
[in] row_ind row indices
[in] vals value data
[in] wrap if false (default), then do copy
Definition at line 1868 of file CompressedStorage.hpp.
CCS() [4/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS (const size_type nrows, const size_type ncols, const size_type nnz = 0u, bool reserve = true) inline
own data for ccs matrix
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] nnz total number of nonzeros, default is 0
[in] reserve if true (default), then reserve space for nnz arrays
Definition at line 1877 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
CCS() [5/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS (const CCS< ValueType, IndexType, IndPtrType > & other, bool clone = false) inline
shallow copy constructor (default) or make a clone
Parameters
[in] other another CCS
[in] clone if false (defaut), do shallow copy
Definition at line 1884 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
CCS() [6/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS (const other_type & crs) inline explicit
make a CCS based on CRS input
Parameters
[in] crs a CRS matrix
Definition at line 1889 of file CompressedStorage.hpp.
CCS() [7/7]
template<class ValueType , class IndexType , class IndPtrType > hif::CCS< ValueType, IndexType, IndPtrType >::CCS (CCS< ValueType, IndexType, IndPtrType > &&) default
Member Function Documentation
begin_assemble_cols()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::begin_assemble_cols () inline
begin assemble columns
Definition at line 1967 of file CompressedStorage.hpp.
check_validity()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::check_validity () const inline
check validity
Definition at line 1934 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
col_start() [1/2]
template<class ValueType , class IndexType , class IndPtrType > iparray_type& hif::CCS< ValueType, IndexType, IndPtrType >::col_start () inline
Definition at line 1904 of file CompressedStorage.hpp.
col_start() [2/2]
template<class ValueType , class IndexType , class IndPtrType > const iparray_type& hif::CCS< ValueType, IndexType, IndPtrType >::col_start () const inline
Definition at line 1907 of file CompressedStorage.hpp.
compute_perm()
template<class ValueType , class IndexType , class IndPtrType > CCS hif::CCS< ValueType, IndexType, IndPtrType >::compute_perm (const iarray_type & pt, const iarray_type & q, const size_type leading = 0, const bool struct_only = false) const inline
compute permutation CCS
Parameters
[in] pt row permutation, from origin to perm
[in] q column permutation, from perm to origin
[in] leading if > 0, then extract leading block
[in] struct_only if false (default), then also compute values
Definition at line 2576 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows, and hif::CCS< ValueType, IndexType, IndPtrType >::nrows().
destroy()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::destroy () inline
explicit destroy the data
Definition at line 2615 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
end_assemble_cols()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::end_assemble_cols () inline
finish assemble columns
Definition at line 1970 of file CompressedStorage.hpp.
extract_leading()
template<class ValueType , class IndexType , class IndPtrType > CCS hif::CCS< ValueType, IndexType, IndPtrType >::extract_leading (const size_type m) const inline
extract leading block
Parameters
[in] m leading block size
Definition at line 2607 of file CompressedStorage.hpp.
from_bin()
template<class ValueType , class IndexType , class IndPtrType > static CCS hif::CCS< ValueType, IndexType, IndPtrType >::from_bin (const char * filename, size_type * m = nullptr) inline static
read from a native HIF binary file
Parameters
[in] filename file name
[out] m if given, then it will store the leading symmetric size
Returns
A CCS matrix
Definition at line 1832 of file CompressedStorage.hpp.
from_mm()
template<class ValueType , class IndexType , class IndPtrType > static CCS hif::CCS< ValueType, IndexType, IndPtrType >::from_mm (const char * filename) inline static
read from a MatrixMarket file
Parameters
[in] filename file name
Returns
A CCS matrix
Definition at line 1842 of file CompressedStorage.hpp.
multiply()
template<class ValueType , class IndexType , class IndPtrType > template<class IArray , class OArray > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply (const IArray & x, OArray & y, bool tran = false) const inline
matrix vector multiplication
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[out] y output array
[in] tran if false (default), then perform normal matrix vector
See also
multiply_t, multiply_nt
Definition at line 2238 of file CompressedStorage.hpp.
multiply_mrhs()
template<class ValueType , class IndexType , class IndPtrType > template<class InType , class OutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs (const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y, bool tran = false) const inline
matrix vector multiplication with multiple right-hand sides (RHS)
Template Parameters
InType input data type
OutType output data type
Nrhs number of right-hand sides (RHS)
Parameters
[in] tran if false (default), then perform normal matrix vector
[in] x input array
[out] y output array
Definition at line 2250 of file CompressedStorage.hpp.
multiply_mrhs_nt()
template<class ValueType , class IndexType , class IndPtrType > template<class InType , class OutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt (const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y) const inline
matrix vector multiplication
Template Parameters
InType input data type
OutType output data type
Nrhs number of right-hand sides (RHS)
Parameters
[in] x input array
[out] y output array
Definition at line 2140 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::ncols(), and hif::CCS< ValueType, IndexType, IndPtrType >::nrows().
multiply_mrhs_nt_low()
template<class ValueType , class IndexType , class IndPtrType > template<size_type Nrhs, class Vx , class Vy > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt_low (const Vx * x, Vy * y) const inline
matrix vector multiplication with different value type
Template Parameters
Nrhs number of right-hand sides (RHS)
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Definition at line 2112 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::nrows(), hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
multiply_mrhs_t()
template<class ValueType , class IndexType , class IndPtrType > template<class InType , class OutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t (const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y) const inline
transpose matrix vector multiplication
Template Parameters
InType input data type
OutType output data type
Nrhs number of right-hand sides (RHS)
Parameters
[in] x input array
[out] y output array
Definition at line 2222 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::ncols(), and hif::CCS< ValueType, IndexType, IndPtrType >::nrows().
multiply_mrhs_t_low()
template<class ValueType , class IndexType , class IndPtrType > template<size_type Nrhs, class Vx , class Vy > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t_low (const Vx * x, Vy * y) const inline
matrix transpose vector multiplication with different type
Template Parameters
Nrhs number of right-hand sides (RHS)
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Definition at line 2194 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
multiply_nt()
template<class ValueType , class IndexType , class IndPtrType > template<class IArray , class OArray > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt (const IArray & x, OArray & y) const inline
matrix vector multiplication
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[out] y output array
Note
Sizes must match
Definition at line 2099 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::ncols(), and hif::CCS< ValueType, IndexType, IndPtrType >::nrows().
multiply_nt_low()
template<class ValueType , class IndexType , class IndPtrType > template<class Vx , class Vy > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt_low (const Vx * x, Vy * y) const inline
matrix vector multiplication with different value type
Template Parameters
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Warning
User's responsibilty to ensure valid pointers
Definition at line 2073 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::nrows(), hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
multiply_t()
template<class ValueType , class IndexType , class IndPtrType > template<class IArray , class OArray > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_t (const IArray & x, OArray & y) const inline
matrix transpose vector multiplication
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[out] y output array
Note
Sizes must match
Definition at line 2181 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::ncols(), and hif::CCS< ValueType, IndexType, IndPtrType >::nrows().
multiply_t_low()
template<class ValueType , class IndexType , class IndPtrType > template<class Vx , class Vy > void hif::CCS< ValueType, IndexType, IndPtrType >::multiply_t_low (const Vx * x, Vy * y) const inline
matrix transpose vector multiplication with different type
Template Parameters
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Warning
User's responsibilty to ensure valid pointers
Definition at line 2155 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
ncols()
template<class ValueType , class IndexType , class IndPtrType > size_type hif::CCS< ValueType, IndexType, IndPtrType >::ncols () const inline
get number of columns
Definition at line 1915 of file CompressedStorage.hpp.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt(), and hif::CCS< ValueType, IndexType, IndPtrType >::multiply_t().
nnz_in_col()
template<class ValueType , class IndexType , class IndPtrType > size_type hif::CCS< ValueType, IndexType, IndPtrType >::nnz_in_col (const size_type i) const inline
get local nnz per column
Parameters
[in] i column entry (C-based index)
Returns
number of nonzeros in column i
Definition at line 1941 of file CompressedStorage.hpp.
nrows()
template<class ValueType , class IndexType , class IndPtrType > size_type hif::CCS< ValueType, IndexType, IndPtrType >::nrows () const inline
get number of rows
Definition at line 1912 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::compute_perm(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt_low(), and hif::CCS< ValueType, IndexType, IndPtrType >::multiply_t().
operator=() [1/2]
template<class ValueType , class IndexType , class IndPtrType > CCS& hif::CCS< ValueType, IndexType, IndPtrType >::operator= (CCS< ValueType, IndexType, IndPtrType > &&) default
operator=() [2/2]
template<class ValueType , class IndexType , class IndPtrType > CCS& hif::CCS< ValueType, IndexType, IndPtrType >::operator= (const CCS< ValueType, IndexType, IndPtrType > &) default
prune()
template<class ValueType , class IndexType , class IndPtrType > size_type hif::CCS< ValueType, IndexType, IndPtrType >::prune (const typename _base::scalar_type eps = 0.0, const bool shrink = false) inline
prune tiny values
Parameters
[in] eps (optional) relative threshold for determining "tiny"
[in] shrink (optional) if true, then we shrink-to-fit the memory
Returns
total number of pruned entries
An entry, say will be pruned if
Definition at line 2628 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
push_back_col() [1/2]
template<class ValueType , class IndexType , class IndPtrType > template<class Iter , class ValueArray > void hif::CCS< ValueType, IndexType, IndPtrType >::push_back_col (const size_type col, Iter first, Iter last, const ValueArray & v) inline
push back a new column
Template Parameters
Iter iterator type
ValueArray dense value array
Parameters
[in] col current col (C-based index)
[in] first starting iterator
[in] last ending iterator
[in] v dense value array, the value can be queried from indices
Warning
The indices are assumed to be sorted
Definition at line 1987 of file CompressedStorage.hpp.
push_back_col() [2/2]
template<class ValueType , class IndexType , class IndPtrType > template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 > void hif::CCS< ValueType, IndexType, IndPtrType >::push_back_col (const size_type col, Iter1 first1, Iter1 last1, const ValueArray1 & v1, Iter2 first2, Iter2 last2, const ValueArray2 & v2) inline
push back a new column from two lists
Template Parameters
Iter1 iterator type
ValueArray1 dense value array
Iter2 iterator type
ValueArray2 dense value array
Parameters
[in] col current col (C-based index)
[in] first1 starting iterator
[in] last1 ending iterator
[in] v1 dense value array, the value can be queried from indices
[in] first2 starting iterator
[in] last2 ending iterator
[in] v2 dense value array, the value can be queried from indices
Warning
The indices are assumed to be sorted
Definition at line 2006 of file CompressedStorage.hpp.
push_back_empty_col()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::push_back_empty_col (const size_type col) inline
push back an empty column
Parameters
[in] col current column entry
Definition at line 1974 of file CompressedStorage.hpp.
read_bin()
template<class ValueType , class IndexType , class IndPtrType > size_type hif::CCS< ValueType, IndexType, IndPtrType >::read_bin (const char * fname) inline
read a native HIF binary file
Parameters
[in] fname file name
Returns
leading symmetric block size
Definition at line 2437 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::resize().
read_mm()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::read_mm (const char * fname) inline
Read data from a MatrixMarket file.
Parameters
[in] fname File name
See also
write_mm
Definition at line 2468 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
resize()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::resize (const size_type nrows, const size_type ncols) inline
resize
Parameters
[in] nrows number of rows
[in] ncols number of columns
Definition at line 1928 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::resize_ncols(), and hif::CCS< ValueType, IndexType, IndPtrType >::resize_nrows().
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::read_bin().
resize_ncols()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::resize_ncols (const size_type ncols) inline
resize columns
Parameters
[in] ncols number of columns
Definition at line 1923 of file CompressedStorage.hpp.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::resize().
resize_nrows()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::resize_nrows (const size_type nrows) inline
resize rows
Parameters
[in] nrows number of rows
Definition at line 1919 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::resize().
row_ind() [1/2]
template<class ValueType , class IndexType , class IndPtrType > iarray_type& hif::CCS< ValueType, IndexType, IndPtrType >::row_ind () inline
Definition at line 1905 of file CompressedStorage.hpp.
row_ind() [2/2]
template<class ValueType , class IndexType , class IndPtrType > const iarray_type& hif::CCS< ValueType, IndexType, IndPtrType >::row_ind () const inline
Definition at line 1908 of file CompressedStorage.hpp.
row_ind_begin() [1/2]
template<class ValueType , class IndexType , class IndPtrType > i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_begin (const size_type i) inline
Definition at line 1947 of file CompressedStorage.hpp.
row_ind_begin() [2/2]
template<class ValueType , class IndexType , class IndPtrType > const_i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_begin (const size_type i) const inline
Definition at line 1953 of file CompressedStorage.hpp.
row_ind_cbegin()
template<class ValueType , class IndexType , class IndPtrType > const_i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin (const size_type i) const inline
Definition at line 1959 of file CompressedStorage.hpp.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_t_low(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs_tran(), and hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_tran().
row_ind_cend()
template<class ValueType , class IndexType , class IndPtrType > const_i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend (const size_type i) const inline
Definition at line 1962 of file CompressedStorage.hpp.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_nt_low(), hif::CCS< ValueType, IndexType, IndPtrType >::multiply_t_low(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs_tran(), and hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_tran().
row_ind_end() [1/2]
template<class ValueType , class IndexType , class IndPtrType > i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_end (const size_type i) inline
Definition at line 1950 of file CompressedStorage.hpp.
row_ind_end() [2/2]
template<class ValueType , class IndexType , class IndPtrType > const_i_iterator hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_end (const size_type i) const inline
Definition at line 1956 of file CompressedStorage.hpp.
scale_diag_left()
template<class ValueType , class IndexType , class IndPtrType > template<class DiagArray > void hif::CCS< ValueType, IndexType, IndPtrType >::scale_diag_left (const DiagArray & s) inline
scale by a diagonal matrix from left
Template Parameters
DiagArray diagonal array type
Parameters
[in] s diagonal matrix multiplying from left-hand side
See also
scale_diag_right
Mathematically, this member function is to perform ; the overall complexity is in order of
Definition at line 2021 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows, and hif::error().
scale_diag_right()
template<class ValueType , class IndexType , class IndPtrType > template<class DiagArray > void hif::CCS< ValueType, IndexType, IndPtrType >::scale_diag_right (const DiagArray & t) inline
scale by a diagonal matrix from right
Template Parameters
DiagArray diagonal array type
Parameters
[in] t diagonal matrix multiplying from left-hand side
See also
scale_diag_left
Mathematically, this member function is to perform ; the overall complexity is in order of
Definition at line 2039 of file CompressedStorage.hpp.
References hif::error().
scale_diags()
template<class ValueType , class IndexType , class IndPtrType > template<class LeftDiagArray , class RightDiagArray > void hif::CCS< ValueType, IndexType, IndPtrType >::scale_diags (const LeftDiagArray & s, const RightDiagArray & t) inline
scale by two diagonal matrices from both lh and rh sides
Template Parameters
LeftDiagArray diagonal array type of left side
RightDiagArray diagonal array type of right side
Parameters
[in] s diagonal matrix of left side
[in] t diagonal matrix of right side
Mathematically, this member function is to perform
Definition at line 2061 of file CompressedStorage.hpp.
solve_as_strict_lower()
template<class ValueType , class IndexType , class IndPtrType > template<class RhsType > void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower (RhsType & y) const inline
Assume as a strict lower matrix and solve with forward sub.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Note
Advanced use for preconditioner solve.
See also
solve_as_strict_upper
Definition at line 2262 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
solve_as_strict_lower_mrhs()
template<class ValueType , class IndexType , class IndPtrType > template<class InOutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict lower matrix and solve with forward sub for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Definition at line 2281 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
solve_as_strict_lower_mrhs_tran()
template<class ValueType , class IndexType , class IndPtrType > template<class InOutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs_tran (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict lower matrix and solve with transpose backward for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Definition at line 2325 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows, and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin().
solve_as_strict_lower_tran()
template<class ValueType , class IndexType , class IndPtrType > template<class RhsType > void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_tran (RhsType & y) const inline
Assume as a strict lower matrix and solve with transpose backward.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Definition at line 2301 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows, hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
solve_as_strict_upper()
template<class ValueType , class IndexType , class IndPtrType > template<class RhsType > void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper (RhsType & y) const inline
Assume as a strict upper matrix and solve with backward sub.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Note
Advanced use for preconditioner solve.
See also
solve_as_strict_lower
Definition at line 2351 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
solve_as_strict_upper_mrhs()
template<class ValueType , class IndexType , class IndPtrType > template<class InOutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict upper matrix and solve with backward sub for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Definition at line 2371 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
solve_as_strict_upper_mrhs_tran()
template<class ValueType , class IndexType , class IndPtrType > template<class InOutType , size_type Nrhs> void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs_tran (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict upper matrix and solve tranpose forward for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Definition at line 2415 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows, hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
solve_as_strict_upper_tran()
template<class ValueType , class IndexType , class IndPtrType > template<class RhsType > void hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_tran (RhsType & y) const inline
Assume as a strict upper matrix and solve tranpose forward.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Definition at line 2393 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows, hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cbegin(), and hif::CCS< ValueType, IndexType, IndPtrType >::row_ind_cend().
split() [1/4]
template<class ValueType , class IndexType , class IndPtrType > template<bool IsSecond> CCS hif::CCS< ValueType, IndexType, IndPtrType >::split (const size_type m) const inline
split against row
Template Parameters
IsSecond if true, then the offset part is returned
Parameters
[in] m splitted row size
Definition at line 2490 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
split() [2/4]
template<class ValueType , class IndexType , class IndPtrType > template<bool IsSecond> CCS hif::CCS< ValueType, IndexType, IndPtrType >::split (const size_type m, const iparray_type & start) const inline
split against row
Template Parameters
IsSecond if true, then the offset part is returned
Parameters
[in] m splitted row size
[in] start starting position array
Definition at line 2503 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
split() [3/4]
template<class ValueType , class IndexType , class IndPtrType > std::pair<CCS, CCS> hif::CCS< ValueType, IndexType, IndPtrType >::split (const size_type m) const inline
split against row
Parameters
[in] m splitted row size
Definition at line 2515 of file CompressedStorage.hpp.
split() [4/4]
template<class ValueType , class IndexType , class IndPtrType > std::pair<CCS, CCS> hif::CCS< ValueType, IndexType, IndPtrType >::split (const size_type m, const iparray_type & start) const inline
split against row
Parameters
[in] m splitted row size
[in] start starting position array
Definition at line 2522 of file CompressedStorage.hpp.
split_crs() [1/4]
template<class ValueType , class IndexType , class IndPtrType > template<bool IsSecond> other_type hif::CCS< ValueType, IndexType, IndPtrType >::split_crs (const size_type m) const inline
split against row and store in CRS
Template Parameters
IsSecond if true, then the offset part is returned
Parameters
[in] m splitted row size
Definition at line 2531 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
split_crs() [2/4]
template<class ValueType , class IndexType , class IndPtrType > template<bool IsSecond> other_type hif::CCS< ValueType, IndexType, IndPtrType >::split_crs (const size_type m, const iparray_type & start) const inline
split against row and store in CRS
Template Parameters
IsSecond if true, then the offset part is returned
Parameters
[in] m splitted row size
[in] start starting position array
Definition at line 2545 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
split_crs() [3/4]
template<class ValueType , class IndexType , class IndPtrType > std::pair<other_type, other_type> hif::CCS< ValueType, IndexType, IndPtrType >::split_crs (const size_type m) const inline
split against row and store in CRS
Parameters
[in] m splitted row size
Definition at line 2558 of file CompressedStorage.hpp.
split_crs() [4/4]
template<class ValueType , class IndexType , class IndPtrType > std::pair<other_type, other_type> hif::CCS< ValueType, IndexType, IndPtrType >::split_crs (const size_type m, const iparray_type & start) const inline
split against row and store in CRS
Parameters
[in] m splitted row size
[in] start starting position array
Definition at line 2565 of file CompressedStorage.hpp.
vals() [1/2]
template<class ValueType , class IndexType , class IndPtrType > array_type& hif::CCS< ValueType, IndexType, IndPtrType >::vals () inline
Definition at line 1906 of file CompressedStorage.hpp.
vals() [2/2]
template<class ValueType , class IndexType , class IndPtrType > const array_type& hif::CCS< ValueType, IndexType, IndPtrType >::vals () const inline
Definition at line 1909 of file CompressedStorage.hpp.
write_bin()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::write_bin (const char * fname, const size_type = 0) const inline
write to a native HIF binary file
Parameters
[in] fname file name
Definition at line 2461 of file CompressedStorage.hpp.
write_mm()
template<class ValueType , class IndexType , class IndPtrType > void hif::CCS< ValueType, IndexType, IndPtrType >::write_mm (const char * fname) const inline
Write data to a MatrixMarket file.
Parameters
[in] fname File name
See also
read_mm
Definition at line 2482 of file CompressedStorage.hpp.
References hif::CCS< ValueType, IndexType, IndPtrType >::_nrows.
Member Data Documentation
_nrows
template<class ValueType , class IndexType , class IndPtrType > size_type hif::CCS< ValueType, IndexType, IndPtrType >::_nrows protected
number of rows
Definition at line 2634 of file CompressedStorage.hpp.
Referenced by hif::CCS< ValueType, IndexType, IndPtrType >::CCS(), hif::CCS< ValueType, IndexType, IndPtrType >::check_validity(), hif::CCS< ValueType, IndexType, IndPtrType >::compute_perm(), hif::CCS< ValueType, IndexType, IndPtrType >::destroy(), hif::CCS< ValueType, IndexType, IndPtrType >::nrows(), hif::CCS< ValueType, IndexType, IndPtrType >::prune(), hif::CCS< ValueType, IndexType, IndPtrType >::read_mm(), hif::CCS< ValueType, IndexType, IndPtrType >::resize_nrows(), hif::CCS< ValueType, IndexType, IndPtrType >::scale_diag_left(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_tran(), hif::CCS< ValueType, IndexType, IndPtrType >::split(), hif::CCS< ValueType, IndexType, IndPtrType >::split_crs(), and hif::CCS< ValueType, IndexType, IndPtrType >::write_mm().
ROW_MAJOR
template<class ValueType , class IndexType , class IndPtrType > constexpr bool hif::CCS< ValueType, IndexType, IndPtrType >::ROW_MAJOR = false static
column major
Definition at line 1826 of file CompressedStorage.hpp.
The documentation for this class was generated from the following file:
CompressedStorage.hpp