HIFIR: hif::CRS< ValueType, IndexType, IndPtrType > Class Template Reference
hif::CRS< ValueType, IndexType, IndPtrType > Class Template Reference
Data Structures
Compressed Row Storage (CRS) format for sparse matrices.
#include <CompressedStorage.hpp>
Public Types
typedef ValueType value_type
value type
typedef IndexType index_type
index type
typedef IndPtrType indptr_type
index_pointer type
typedef _base::array_type array_type
value array
typedef _base::iarray_type iarray_type
index array
typedef _base::iparray_type iparray_type
indptr array
typedef _base::size_type size_type
size type
typedef _base::pointer pointer
value pointer
typedef _base::ipointer ipointer
index pointer
typedef _base::ippointer ippointer
index_pointer pointer
typedef CCS< ValueType, IndexType, IndPtrType > other_type
ccs type
typedef _base::i_iterator i_iterator
index iterator
typedef _base::const_i_iterator const_i_iterator
const index iterator
typedef _base::v_iterator v_iterator
value iterator
typedef _base::const_v_iterator const_v_iterator
Public Types inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
typedef ValueType value_type
value type
typedef value_type * pointer
pointer type
typedef IndexType index_type
index type
typedef index_type * ipointer
index pointer
typedef IndPtrType indptr_type
index_pointer type
typedef indptr_type * ippointer
index_pointer pointer
typedef CompressedStorage this_type
this
typedef Array< ValueType > array_type
value array
typedef Array< IndexType > iarray_type
index array
typedef Array< IndPtrType > iparray_type
index pointer array
typedef array_type::size_type size_type
size type
typedef array_type::iterator v_iterator
value iterator
typedef array_type::const_iterator const_v_iterator
constant
typedef iarray_type::iterator i_iterator
index iterator
typedef iarray_type::const_iterator const_i_iterator
constant
typedef ValueTypeTrait< value_type >::value_type scalar_type
scalar (real) type
Public Member Functions
CRS ()
default constructor
CRS (const size_type nrows, const size_type ncols, ippointer row_start, ipointer col_ind, pointer vals, bool wrap=false)
external data for matrix
CRS (const size_type n, ippointer row_start, ipointer col_ind, pointer vals, bool wrap=false)
external data for squared matrix
CRS (const size_type nrows, const size_type ncols, const size_type nnz=0u, bool reserve=true)
own data for crs matrix
CRS (const CRS &other, bool clone=false)
shallow copy constructor (default) or make a clone
CRS (const other_type &ccs)
make a CRS based on CCS input
CRS (CRS &&)=default
CRS & operator= (CRS &&)=default
CRS & operator= (const CRS &)=default
iparray_type & row_start ()
iarray_type & col_ind ()
array_type & vals ()
const iparray_type & row_start () const
const iarray_type & col_ind () const
const array_type & vals () const
size_type nrows () const
get number of rows
size_type ncols () const
get number of columns
void resize_nrows (const size_type nrows)
resize rows
void resize_ncols (const size_type ncols)
resize columns
void resize (const size_type nrows, const size_type ncols)
resize
void check_validity () const
check validity
size_type nnz_in_row (const size_type i) const
get local nnz per row
i_iterator col_ind_begin (const size_type i)
i_iterator col_ind_end (const size_type i)
const_i_iterator col_ind_begin (const size_type i) const
const_i_iterator col_ind_end (const size_type i) const
const_i_iterator col_ind_cbegin (const size_type i) const
const_i_iterator col_ind_cend (const size_type i) const
void begin_assemble_rows ()
begin assemble rows
void end_assemble_rows ()
finish assemble rows
void push_back_empty_row (const size_type row)
push back an empty row
template<class Iter , class ValueArray >
void push_back_row (const size_type row, Iter first, Iter last, const ValueArray &v)
push back a new row
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void push_back_row (const size_type row, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back a new row from two lists
template<class DiagArray >
void scale_diag_left (const DiagArray &s)
scale by a diagonal matrix from left
template<class DiagArray >
void scale_diag_right (const DiagArray &t)
scale by a diagonal matrix from right
template<class LeftDiagArray , class RightDiagArray >
void scale_diags (const LeftDiagArray &s, const RightDiagArray &t)
scale by two diagonal matrices from both lh and rh sides
template<class Vx , class Vy >
void multiply_nt_low (const Vx *x, Vy *y) const
matrix vector multiplication with different value type
template<class Vx , class Vy >
void multiply_nt_low (const Vx *x, const size_type istart, const size_type len, Vy *y) const
matrix vector for kernel MT compatibility with different type
template<size_type Nrhs, class Vx , class Vy >
void multiply_mrhs_nt_low (const Vx *x, const size_type istart, const size_type len, Vy *y) const
matrix vector for kernel MT compatibility with different type
template<size_type Nrhs, class Vx , class Vy >
void multiply_mrhs_nt_low (const Vx *x, Vy *y) const
matrix vector multiplication with different value type
template<class IArray , class OArray >
void multiply_nt (const IArray &x, OArray &y) const
matrix vector multiplication
template<class IArray , class OArray >
void multiply_nt (const IArray &x, const size_type istart, const size_type len, OArray &y) const
matrix vector multiplication for MT (CRS only)
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs_nt (const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y) const
matrix vector multiplication with multiple RHS
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs_nt (const Array< std::array< InType, Nrhs >> &x, const size_type istart, const size_type len, Array< std::array< OutType, Nrhs >> &y) const
matrix vector multiplication for MT (CRS only)
template<class Vx , class Vy >
void multiply_t_low (const Vx *x, Vy *y) const
matrix transpose vector multiplication with different type
template<class IArray , class OArray >
void multiply_t (const IArray &x, OArray &y) const
matrix transpose vector multiplication
template<size_type Nrhs, class Vx , class Vy >
void multiply_mrhs_t_low (const Vx *x, Vy *y) const
matrix transpose vector multiplication with different type
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs_t (const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y) const
matrix transpose vector multiplication
template<class IArray , class OArray >
void multiply (const IArray &x, OArray &y, bool tran=false) const
matrix vector multiplication
template<class InType , class OutType , size_type Nrhs>
void multiply_mrhs (const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y, bool tran=false) const
matrix vector multiplication with multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_lower (RhsType &y) const
Assume as a strict lower matrix and solve with forward sub.
template<class InOutType , size_type Nrhs>
void solve_as_strict_lower_mrhs (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict lower matrix and solve with forward sub for multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_lower_tran (RhsType &y) const
Assume as a strict lower matrix and solve with transpose backward.
template<class InOutType , size_type Nrhs>
void solve_as_strict_lower_mrhs_tran (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict lower matrix and solve with transpose backward for multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_upper (RhsType &y) const
Assume as a strict upper matrix and solve with backward sub.
template<class InOutType , size_type Nrhs>
void solve_as_strict_upper_mrhs (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict upper matrix and solve with backward sub for multiple right-hand sides (RHS)
template<class RhsType >
void solve_as_strict_upper_tran (RhsType &y) const
Assume as a strict upper matrix and solve with transpose forward.
template<class InOutType , size_type Nrhs>
void solve_as_strict_upper_mrhs_tran (Array< std::array< InOutType, Nrhs >> &y) const
Assume as a strict upper matrix and solve with transpose forward for multiple right-hand sides (RHS)
size_type read_bin (const char *fname)
read a native binary file
void write_bin (const char *fname, const size_type=0) const
write a native binary file
void read_mm (const char *fname)
Read data from a MatrixMarket file.
void write_mm (const char *fname) const
Write data to a MatrixMarket file.
template<bool IsSecond>
CRS split (const size_type m) const
split the matrix against column
template<bool IsSecond>
CRS split (const size_type m, const iparray_type &start) const
split the matrix against column
std::pair< CRS, CRS > split (const size_type m) const
split the matrix against column
std::pair< CRS, CRS > split (const size_type m, const iparray_type &start) const
split the matrix against column
template<bool IsSecond>
other_type split_ccs (const size_type m) const
split and store to CCS
template<bool IsSecond>
other_type split_ccs (const size_type m, const iparray_type &start) const
split and store to CCS
std::pair< other_type, other_type > split_ccs (const size_type m) const
split the matrix against column and store to CCS
std::pair< other_type, other_type > split_ccs (const size_type m, const iarray_type &start) const
split the matrix against column and store to CCS
CRS compute_perm (const iarray_type &p, const iarray_type &qt, const size_type leading=0, const bool struct_only=false) const
compute permutation CRS
CRS extract_leading (const size_type m) const
extract leading block
void destroy ()
explicit destroy the memory
size_type prune (const typename _base::scalar_type eps=0.0, const bool shrink=false)
prune tiny values
Public Member Functions inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
CompressedStorage ()
default constructor
CompressedStorage (const size_type n, ippointer ind_start, ipointer indices, pointer vals, bool wrap=false)
constructor with external data, either copy (default) or wrap
CompressedStorage (const size_type n, const size_type nnz=0u, bool reserve=true)
constructor for own data
CompressedStorage (const this_type &other, bool clone=false)
shallow copy constructor (default) or deep copy
CompressedStorage (this_type &&)=default
this_type & operator= (this_type &&)=default
this_type & operator= (const this_type &)=default
unsigned char status () const
check the status of the storage
size_type nnz () const
v_iterator val_begin (const size_type i)
v_iterator val_end (const size_type i)
const_v_iterator val_begin (const size_type i) const
const_v_iterator val_end (const size_type i) const
const_v_iterator val_cbegin (const size_type i) const
const_v_iterator val_cend (const size_type i) const
size_type nnz_in_primary (const size_type i) const
i_iterator ind_begin (const size_type i)
i_iterator ind_end (const size_type i)
const_i_iterator ind_begin (const size_type i) const
const_i_iterator ind_end (const size_type i) const
const_i_iterator ind_cbegin (const size_type i) const
const_i_iterator ind_cend (const size_type i) const
iarray_type & inds ()
const iarray_type & inds () const
iparray_type & ind_start ()
const iparray_type & ind_start () const
const size_type primary_size () const
void reserve (const size_type nnz)
reserve space for nnz
template<bool IsRow>
void check_validity (const size_type other_size) const
check the validity of a matrix
Static Public Member Functions
static CRS from_bin (const char *filename, size_type *m=nullptr)
read a matrix from HIF native binary file
static CRS from_mm (const char *filename)
Read a matrix from a MatrixMarket file.
Static Public Attributes
static constexpr bool ROW_MAJOR = true
row major
Protected Attributes
size_type _ncols
number of columns
Protected Attributes inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
iparray_type _ind_start
index pointer array, size of n+1
iarray_type _indices
index array, size of nnz
array_type _vals
numerical data array, size of nnz
size_type _psize
primary size
Private Types
typedef internal::CompressedStorage< ValueType, IndexType, IndPtrType > _base
Additional Inherited Members
Protected Member Functions inherited from hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
void _begin_assemble ()
begin assemble rows
void _end_assemble ()
finish assembling process
void _push_back_primary_empty (const size_type ii)
push back an empty entry
template<class Iter , class ValueArray >
void _push_back_primary (const size_type ii, Iter first, Iter last, const ValueArray &v)
push back a SORTED index list to _indices
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void _push_back_primary (const size_type ii, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back two SORTED index lists to _indices
size_type _nnz (const size_type i) const
check local number of nonzeros
i_iterator _ind_begin (const size_type i)
i_iterator _ind_end (const size_type i)
const_i_iterator _ind_begin (const size_type i) const
const_i_iterator _ind_end (const size_type i) const
const_i_iterator _ind_cbegin (const size_type i) const
const_i_iterator _ind_cend (const size_type i) const
template<bool IsSecond>
void _split (const size_type m, const indptr_type *start, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split against secondary size
template<bool IsSecond>
void _split (const size_type m, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split against secondary size
template<bool IsSecond>
void _split_dual (const size_type m, const size_type n, const indptr_type *start, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split and store to the counterpart type
template<bool IsSecond>
void _split_dual (const size_type m, const size_type n, iparray_type &indptr, iarray_type &indices, array_type &vals) const
split and store to the counterpart type
template<bool DoValue, bool OnlyLeading>
void _compute_perm (const iarray_type &p, const iarray_type &qt, const size_type leading, iparray_type &indptr, iarray_type &indices, array_type &vals) const
construct permutated matrix
void _extract_leading_struct (const size_type m, iparray_type &indptr, iarray_type &indices) const
extract leading block structure
void _extract_leading (const size_type m, iparray_type &indptr, iarray_type &indices, array_type &vals) const
extract leading block
void _destroy ()
destroy the memory explicitly
size_type _prune (const size_type n, scalar_type eps=0, const bool shrink=false)
filter out small values
Detailed Description
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t>
class hif::CRS< ValueType, IndexType, IndPtrType >
Compressed Row Storage (CRS) format for sparse matrices.
Template Parameters
ValueType numerical value type, e.g. double, float, etc
IndexType index type, e.g. int, long, etc
IndPtrType index pointer type, default is std::ptrdiff_t
Examples:
demo_complex.cpp.
Definition at line 823 of file CompressedStorage.hpp.
Member Typedef Documentation
_base
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef internal::CompressedStorage<ValueType, IndexType, IndPtrType> hif::CRS< ValueType, IndexType, IndPtrType >::_base private
Definition at line 825 of file CompressedStorage.hpp.
array_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::array_type hif::CRS< ValueType, IndexType, IndPtrType >::array_type
value array
Definition at line 831 of file CompressedStorage.hpp.
const_i_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::const_i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::const_i_iterator
const index iterator
Definition at line 840 of file CompressedStorage.hpp.
const_v_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::const_v_iterator hif::CRS< ValueType, IndexType, IndPtrType >::const_v_iterator
Definition at line 843 of file CompressedStorage.hpp.
i_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::i_iterator
index iterator
Definition at line 839 of file CompressedStorage.hpp.
iarray_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::iarray_type hif::CRS< ValueType, IndexType, IndPtrType >::iarray_type
index array
Definition at line 832 of file CompressedStorage.hpp.
index_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef IndexType hif::CRS< ValueType, IndexType, IndPtrType >::index_type
index type
Definition at line 829 of file CompressedStorage.hpp.
indptr_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef IndPtrType hif::CRS< ValueType, IndexType, IndPtrType >::indptr_type
index_pointer type
Definition at line 830 of file CompressedStorage.hpp.
iparray_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::iparray_type hif::CRS< ValueType, IndexType, IndPtrType >::iparray_type
indptr array
Definition at line 833 of file CompressedStorage.hpp.
ipointer
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::ipointer hif::CRS< ValueType, IndexType, IndPtrType >::ipointer
index pointer
Definition at line 836 of file CompressedStorage.hpp.
ippointer
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::ippointer hif::CRS< ValueType, IndexType, IndPtrType >::ippointer
index_pointer pointer
Definition at line 837 of file CompressedStorage.hpp.
other_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef CCS<ValueType, IndexType, IndPtrType> hif::CRS< ValueType, IndexType, IndPtrType >::other_type
ccs type
Definition at line 838 of file CompressedStorage.hpp.
pointer
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::pointer hif::CRS< ValueType, IndexType, IndPtrType >::pointer
value pointer
Definition at line 835 of file CompressedStorage.hpp.
size_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::size_type hif::CRS< ValueType, IndexType, IndPtrType >::size_type
size type
Definition at line 834 of file CompressedStorage.hpp.
v_iterator
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef _base::v_iterator hif::CRS< ValueType, IndexType, IndPtrType >::v_iterator
value iterator
Definition at line 842 of file CompressedStorage.hpp.
value_type
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> typedef ValueType hif::CRS< ValueType, IndexType, IndPtrType >::value_type
value type
Definition at line 828 of file CompressedStorage.hpp.
Constructor & Destructor Documentation
CRS() [1/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS () inline
default constructor
Definition at line 867 of file CompressedStorage.hpp.
CRS() [2/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS (const size_type nrows, const size_type ncols, ippointer row_start, ipointer col_ind, pointer vals, bool wrap = false) inline
external data for matrix
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] row_start row index start array
[in] col_ind column indices
[in] vals value data
[in] wrap if false (default), then do copy
Definition at line 876 of file CompressedStorage.hpp.
CRS() [3/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS (const size_type n, ippointer row_start, ipointer col_ind, pointer vals, bool wrap = false) inline
external data for squared matrix
Parameters
[in] n number of rows and columns
[in] row_start row index start array
[in] col_ind column indices
[in] vals value data
[in] wrap if false (default), then do copy
Definition at line 886 of file CompressedStorage.hpp.
CRS() [4/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS (const size_type nrows, const size_type ncols, const size_type nnz = 0u, bool reserve = true) inline
own data for crs matrix
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] nnz total number of nonzeros, default is 0
[in] reserve if true (default), then reserve space for nnz arrays
Definition at line 895 of file CompressedStorage.hpp.
CRS() [5/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS (const CRS< ValueType, IndexType, IndPtrType > & other, bool clone = false) inline
shallow copy constructor (default) or make a clone
Parameters
[in] other another CRS
[in] clone if false (defaut), do shallow copy
Definition at line 902 of file CompressedStorage.hpp.
CRS() [6/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS (const other_type & ccs) inline explicit
make a CRS based on CCS input
Parameters
[in] ccs a CCS matrix
Definition at line 907 of file CompressedStorage.hpp.
CRS() [7/7]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> hif::CRS< ValueType, IndexType, IndPtrType >::CRS (CRS< ValueType, IndexType, IndPtrType > &&) default
Member Function Documentation
begin_assemble_rows()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::begin_assemble_rows () inline
begin assemble rows
Definition at line 987 of file CompressedStorage.hpp.
check_validity()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::check_validity () const inline
check validity
Definition at line 954 of file CompressedStorage.hpp.
col_ind() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> iarray_type& hif::CRS< ValueType, IndexType, IndPtrType >::col_ind () inline
Definition at line 925 of file CompressedStorage.hpp.
col_ind() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const iarray_type& hif::CRS< ValueType, IndexType, IndPtrType >::col_ind () const inline
Definition at line 928 of file CompressedStorage.hpp.
col_ind_begin() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::col_ind_begin (const size_type i) inline
Definition at line 967 of file CompressedStorage.hpp.
col_ind_begin() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::col_ind_begin (const size_type i) const inline
Definition at line 973 of file CompressedStorage.hpp.
col_ind_cbegin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::col_ind_cbegin (const size_type i) const inline
Definition at line 979 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_nt_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_t_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_nt_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_t_low(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_mrhs(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_mrhs_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_mrhs(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_mrhs_tran(), and hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_tran().
col_ind_cend()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::col_ind_cend (const size_type i) const inline
Definition at line 982 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_nt_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_t_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_nt_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_t_low(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_mrhs(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_mrhs_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_mrhs(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_mrhs_tran(), and hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_tran().
col_ind_end() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::col_ind_end (const size_type i) inline
Definition at line 970 of file CompressedStorage.hpp.
col_ind_end() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const_i_iterator hif::CRS< ValueType, IndexType, IndPtrType >::col_ind_end (const size_type i) const inline
Definition at line 976 of file CompressedStorage.hpp.
compute_perm()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> CRS hif::CRS< ValueType, IndexType, IndPtrType >::compute_perm (const iarray_type & p, const iarray_type & qt, const size_type leading = 0, const bool struct_only = false) const inline
compute permutation CRS
Parameters
[in] p row permutation, from perm to origin
[in] qt column permutation, from origin to perm
[in] leading if > 0, then extract leading block
[in] struct_only if false (default), then also compute values
Definition at line 1676 of file CompressedStorage.hpp.
destroy()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::destroy () inline
explicit destroy the memory
Definition at line 1716 of file CompressedStorage.hpp.
end_assemble_rows()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::end_assemble_rows () inline
finish assemble rows
Definition at line 990 of file CompressedStorage.hpp.
extract_leading()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> CRS hif::CRS< ValueType, IndexType, IndPtrType >::extract_leading (const size_type m) const inline
extract leading block
Parameters
[in] m leading size
Definition at line 1708 of file CompressedStorage.hpp.
from_bin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> static CRS hif::CRS< ValueType, IndexType, IndPtrType >::from_bin (const char * filename, size_type * m = nullptr) inline static
read a matrix from HIF native binary file
Parameters
[in] filename file name
[out] m if given, the leading block size is also returned
Returns
A CRS matrix
Definition at line 850 of file CompressedStorage.hpp.
from_mm()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> static CRS hif::CRS< ValueType, IndexType, IndPtrType >::from_mm (const char * filename) inline static
Read a matrix from a MatrixMarket file.
Parameters
[in] filename file name
Returns
A CRS matrix
Definition at line 860 of file CompressedStorage.hpp.
Referenced by get_input_data(), and get_user_data().
multiply()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class IArray , class OArray > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply (const IArray & x, OArray & y, bool tran = false) const inline
matrix vector multiplication
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[out] y output array
[in] tran if false (default), perform normal matrix vector
See also
multiply_nt, multiply_t
Definition at line 1329 of file CompressedStorage.hpp.
multiply_mrhs()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InType , class OutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs (const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y, bool tran = false) const inline
matrix vector multiplication with multiple right-hand sides (RHS)
Template Parameters
InType input data type
OutType output data type
Nrhs number of RHS
Parameters
[in] x input array
[out] y output array
[in] tran if false (default), perform normal matrix vector
See also
multiply_nt
Definition at line 1342 of file CompressedStorage.hpp.
multiply_mrhs_nt() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InType , class OutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt (const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y) const inline
matrix vector multiplication with multiple RHS
Template Parameters
InType input data type
OutType output data type
Nrhs number of right-hand sides (RHS)
Parameters
[in] x input array
[out] y output array
Definition at line 1209 of file CompressedStorage.hpp.
multiply_mrhs_nt() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InType , class OutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt (const Array< std::array< InType, Nrhs >> & x, const size_type istart, const size_type len, Array< std::array< OutType, Nrhs >> & y) const inline
matrix vector multiplication for MT (CRS only)
Template Parameters
InType input data type
OutType output data type
Nrhs number of right-hand sides (RHS)
Parameters
[in] x input array
[in] istart index start
[in] len local length
[out] y output array
Definition at line 1226 of file CompressedStorage.hpp.
multiply_mrhs_nt_low() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<size_type Nrhs, class Vx , class Vy > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt_low (const Vx * x, const size_type istart, const size_type len, Vy * y) const inline
matrix vector for kernel MT compatibility with different type
Template Parameters
Nrhs number of right-hand sides (RHS)
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[in] istart index start
[in] len local length
[out] y output array pointer
Definition at line 1134 of file CompressedStorage.hpp.
multiply_mrhs_nt_low() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<size_type Nrhs, class Vx , class Vy > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs_nt_low (const Vx * x, Vy * y) const inline
matrix vector multiplication with different value type
Template Parameters
Nrhs number of right-hand sides (RHS)
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Warning
User's responsibility to maintain valid pointers
Definition at line 1165 of file CompressedStorage.hpp.
multiply_mrhs_t()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InType , class OutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t (const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y) const inline
matrix transpose vector multiplication
Template Parameters
InType input data type
OutType output data type
Nrhs number of right-hand sides (RHS)
Parameters
[in] x input array
[out] y output array
Definition at line 1313 of file CompressedStorage.hpp.
multiply_mrhs_t_low()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<size_type Nrhs, class Vx , class Vy > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_mrhs_t_low (const Vx * x, Vy * y) const inline
matrix transpose vector multiplication with different type
Template Parameters
Nrhs number of right-hand sides (RHS)
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Definition at line 1286 of file CompressedStorage.hpp.
multiply_nt() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class IArray , class OArray > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_nt (const IArray & x, OArray & y) const inline
matrix vector multiplication
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[out] y output array
Note
Sizes must match
Definition at line 1176 of file CompressedStorage.hpp.
multiply_nt() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class IArray , class OArray > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_nt (const IArray & x, const size_type istart, const size_type len, OArray & y) const inline
matrix vector multiplication for MT (CRS only)
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[in] istart index start
[in] len local length
[out] y output array
Note
Sizes must match
Definition at line 1191 of file CompressedStorage.hpp.
multiply_nt_low() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Vx , class Vy > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_nt_low (const Vx * x, Vy * y) const inline
matrix vector multiplication with different value type
Template Parameters
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Warning
User's responsibility to maintain valid pointers
Definition at line 1093 of file CompressedStorage.hpp.
multiply_nt_low() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Vx , class Vy > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_nt_low (const Vx * x, const size_type istart, const size_type len, Vy * y) const inline
matrix vector for kernel MT compatibility with different type
Template Parameters
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[in] istart index start
[in] len local length
[out] y output array pointer
Definition at line 1105 of file CompressedStorage.hpp.
multiply_t()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class IArray , class OArray > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_t (const IArray & x, OArray & y) const inline
matrix transpose vector multiplication
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] x input array
[out] y output array
Note
Sizes must match
Compute
Definition at line 1273 of file CompressedStorage.hpp.
multiply_t_low()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Vx , class Vy > void hif::CRS< ValueType, IndexType, IndPtrType >::multiply_t_low (const Vx * x, Vy * y) const inline
matrix transpose vector multiplication with different type
Template Parameters
Vx other value type for x
Vy other value type for y
Parameters
[in] x input array pointer
[out] y output array pointer
Warning
User's responsibility to maintain valid pointers
Definition at line 1246 of file CompressedStorage.hpp.
ncols()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::CRS< ValueType, IndexType, IndPtrType >::ncols () const inline
get number of columns
Definition at line 935 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::compute_perm(), get_user_data(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_nt(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_t(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_t_low(), hif::CRS< value_type, index_type, IndPtrType >::multiply_nt(), hif::CRS< value_type, index_type, IndPtrType >::multiply_t(), and hif::CRS< value_type, index_type, IndPtrType >::multiply_t_low().
nnz_in_row()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::CRS< ValueType, IndexType, IndPtrType >::nnz_in_row (const size_type i) const inline
get local nnz per row
Parameters
[in] i row entry (C-based index)
Returns
number of nonzeros in row i
Definition at line 961 of file CompressedStorage.hpp.
nrows()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::CRS< ValueType, IndexType, IndPtrType >::nrows () const inline
get number of rows
Definition at line 932 of file CompressedStorage.hpp.
Referenced by get_user_data(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_nt(), hif::CRS< value_type, index_type, IndPtrType >::multiply_mrhs_t(), hif::CRS< value_type, index_type, IndPtrType >::multiply_nt(), and hif::CRS< value_type, index_type, IndPtrType >::multiply_t().
operator=() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> CRS& hif::CRS< ValueType, IndexType, IndPtrType >::operator= (CRS< ValueType, IndexType, IndPtrType > &&) default
operator=() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> CRS& hif::CRS< ValueType, IndexType, IndPtrType >::operator= (const CRS< ValueType, IndexType, IndPtrType > &) default
prune()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::CRS< ValueType, IndexType, IndPtrType >::prune (const typename _base::scalar_type eps = 0.0, const bool shrink = false) inline
prune tiny values
Parameters
[in] eps (optional) relative threshold for determining "tiny"
[in] shrink (optional) if true, then we shrink-to-fit the memory
Returns
total number of pruned entries
An entry, say will be pruned if
Definition at line 1729 of file CompressedStorage.hpp.
push_back_empty_row()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::push_back_empty_row (const size_type row) inline
push back an empty row
Parameters
[in] row current row entry
Definition at line 994 of file CompressedStorage.hpp.
push_back_row() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Iter , class ValueArray > void hif::CRS< ValueType, IndexType, IndPtrType >::push_back_row (const size_type row, Iter first, Iter last, const ValueArray & v) inline
push back a new row
Template Parameters
Iter iterator type
ValueArray dense value array
Parameters
[in] row current row (C-based index)
[in] first starting iterator
[in] last ending iterator
[in] v dense value array, the value can be queried from indices
Warning
The indices are assumed to be sorted
Definition at line 1007 of file CompressedStorage.hpp.
push_back_row() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 > void hif::CRS< ValueType, IndexType, IndPtrType >::push_back_row (const size_type row, Iter1 first1, Iter1 last1, const ValueArray1 & v1, Iter2 first2, Iter2 last2, const ValueArray2 & v2) inline
push back a new row from two lists
Template Parameters
Iter1 iterator type
ValueArray1 dense value array
Iter2 iterator type
ValueArray2 dense value array
Parameters
[in] row current row (C-based index)
[in] first1 starting iterator
[in] last1 ending iterator
[in] v1 dense value array, the value can be queried from indices
[in] first2 starting iterator
[in] last2 ending iterator
[in] v2 dense value array, the value can be queried from indices
Warning
The indices are assumed to be sorted
Definition at line 1026 of file CompressedStorage.hpp.
read_bin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::CRS< ValueType, IndexType, IndPtrType >::read_bin (const char * fname) inline
read a native binary file
Parameters
[in] fname file name
Returns
leading symmetric block size
Definition at line 1531 of file CompressedStorage.hpp.
read_mm()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::read_mm (const char * fname) inline
Read data from a MatrixMarket file.
Parameters
[in] fname File name
See also
write_mm
Definition at line 1562 of file CompressedStorage.hpp.
resize()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::resize (const size_type nrows, const size_type ncols) inline
resize
Parameters
[in] nrows number of rows
[in] ncols number of columns
Definition at line 948 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::read_bin().
resize_ncols()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::resize_ncols (const size_type ncols) inline
resize columns
Parameters
[in] ncols number of columns
Definition at line 943 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::resize().
resize_nrows()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::resize_nrows (const size_type nrows) inline
resize rows
Parameters
[in] nrows number of rows
Definition at line 939 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::resize().
row_start() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> iparray_type& hif::CRS< ValueType, IndexType, IndPtrType >::row_start () inline
Definition at line 924 of file CompressedStorage.hpp.
row_start() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const iparray_type& hif::CRS< ValueType, IndexType, IndPtrType >::row_start () const inline
Definition at line 927 of file CompressedStorage.hpp.
scale_diag_left()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class DiagArray > void hif::CRS< ValueType, IndexType, IndPtrType >::scale_diag_left (const DiagArray & s) inline
scale by a diagonal matrix from left
Template Parameters
DiagArray diagonal array type
Parameters
[in] s diagonal matrix multiplying from left-hand side
See also
scale_diag_right
Mathematically, this member function is to perform ; the overall complexity is in order of
Definition at line 1041 of file CompressedStorage.hpp.
scale_diag_right()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class DiagArray > void hif::CRS< ValueType, IndexType, IndPtrType >::scale_diag_right (const DiagArray & t) inline
scale by a diagonal matrix from right
Template Parameters
DiagArray diagonal array type
Parameters
[in] t diagonal matrix multiplying from right-hand side
See also
scale_diag_left
Mathematically, this member function is to perform ; the overall complexity is in order of
Definition at line 1062 of file CompressedStorage.hpp.
scale_diags()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class LeftDiagArray , class RightDiagArray > void hif::CRS< ValueType, IndexType, IndPtrType >::scale_diags (const LeftDiagArray & s, const RightDiagArray & t) inline
scale by two diagonal matrices from both lh and rh sides
Template Parameters
LeftDiagArray diagonal array type of left side
RightDiagArray diagonal array type of right side
Parameters
[in] s diagonal matrix of left side
[in] t diagonal matrix of right side
Mathematically, this member function is to perform
Definition at line 1081 of file CompressedStorage.hpp.
solve_as_strict_lower()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class RhsType > void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower (RhsType & y) const inline
Assume as a strict lower matrix and solve with forward sub.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Note
Advanced use for preconditioner solve.
See also
solve_as_strict_upper
Definition at line 1354 of file CompressedStorage.hpp.
solve_as_strict_lower_mrhs()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InOutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict lower matrix and solve with forward sub for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Note
Advanced use for preconditioner solve.
See also
solve_as_strict_lower
Definition at line 1378 of file CompressedStorage.hpp.
solve_as_strict_lower_mrhs_tran()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InOutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_mrhs_tran (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict lower matrix and solve with transpose backward for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Definition at line 1422 of file CompressedStorage.hpp.
solve_as_strict_lower_tran()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class RhsType > void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_lower_tran (RhsType & y) const inline
Assume as a strict lower matrix and solve with transpose backward.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Definition at line 1401 of file CompressedStorage.hpp.
solve_as_strict_upper()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class RhsType > void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper (RhsType & y) const inline
Assume as a strict upper matrix and solve with backward sub.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Note
Advanced use for preconditioner solve.
See also
solve_as_strict_lower
Definition at line 1447 of file CompressedStorage.hpp.
solve_as_strict_upper_mrhs()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InOutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict upper matrix and solve with backward sub for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in,out] y Input rhs, output solution
Note
Advanced use for preconditioner solve.
See also
solve_as_strict_upper
Definition at line 1473 of file CompressedStorage.hpp.
solve_as_strict_upper_mrhs_tran()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class InOutType , size_type Nrhs> void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_mrhs_tran (Array< std::array< InOutType, Nrhs >> & y) const inline
Assume as a strict upper matrix and solve with transpose forward for multiple right-hand sides (RHS)
Template Parameters
InOutType In- and out- put types
Nrhs Number of RHS
Parameters
[in] y Input rhs, output solution
Definition at line 1514 of file CompressedStorage.hpp.
solve_as_strict_upper_tran()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<class RhsType > void hif::CRS< ValueType, IndexType, IndPtrType >::solve_as_strict_upper_tran (RhsType & y) const inline
Assume as a strict upper matrix and solve with transpose forward.
Template Parameters
RhsType Rhs type
Parameters
[in,out] y Input rhs, output solution
Definition at line 1498 of file CompressedStorage.hpp.
split() [1/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> CRS hif::CRS< ValueType, IndexType, IndPtrType >::split (const size_type m) const inline
split the matrix against column
Template Parameters
IsSecond if true, then the second half is returned
Parameters
[in] m column size
If IsSecond is true, then the result matrix is A[:,m:]; otherwise the result matrix is A[:,0:m]
Definition at line 1587 of file CompressedStorage.hpp.
split() [2/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> CRS hif::CRS< ValueType, IndexType, IndPtrType >::split (const size_type m, const iparray_type & start) const inline
split the matrix against column
Template Parameters
IsSecond if true, then the second half is returned
Parameters
[in] m column size
[in] start starting position array, at least size of nrows()
If IsSecond is true, then the result matrix is A[:,m:]; otherwise the result matrix is A[:,0:m]
Definition at line 1603 of file CompressedStorage.hpp.
split() [3/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> std::pair<CRS, CRS> hif::CRS< ValueType, IndexType, IndPtrType >::split (const size_type m) const inline
split the matrix against column
Parameters
[in] m column size
Definition at line 1615 of file CompressedStorage.hpp.
split() [4/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> std::pair<CRS, CRS> hif::CRS< ValueType, IndexType, IndPtrType >::split (const size_type m, const iparray_type & start) const inline
split the matrix against column
Parameters
[in] m column size
[in] start starting position array, at least size of m
Definition at line 1622 of file CompressedStorage.hpp.
split_ccs() [1/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> other_type hif::CRS< ValueType, IndexType, IndPtrType >::split_ccs (const size_type m) const inline
split and store to CCS
Template Parameters
IsSecond if true, then the second half is returned
Parameters
[in] m column size
Definition at line 1631 of file CompressedStorage.hpp.
split_ccs() [2/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> template<bool IsSecond> other_type hif::CRS< ValueType, IndexType, IndPtrType >::split_ccs (const size_type m, const iparray_type & start) const inline
split and store to CCS
Template Parameters
IsSecond if true, then the second half is returned
Parameters
[in] m column size
[in] start starting position array, at least size of nrows()
Definition at line 1645 of file CompressedStorage.hpp.
split_ccs() [3/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> std::pair<other_type, other_type> hif::CRS< ValueType, IndexType, IndPtrType >::split_ccs (const size_type m) const inline
split the matrix against column and store to CCS
Parameters
[in] m column size
Definition at line 1658 of file CompressedStorage.hpp.
split_ccs() [4/4]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> std::pair<other_type, other_type> hif::CRS< ValueType, IndexType, IndPtrType >::split_ccs (const size_type m, const iarray_type & start) const inline
split the matrix against column and store to CCS
Parameters
[in] m column size
[in] start starting position array, at least size of nrows()
Definition at line 1665 of file CompressedStorage.hpp.
vals() [1/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> array_type& hif::CRS< ValueType, IndexType, IndPtrType >::vals () inline
Definition at line 926 of file CompressedStorage.hpp.
vals() [2/2]
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> const array_type& hif::CRS< ValueType, IndexType, IndPtrType >::vals () const inline
Definition at line 929 of file CompressedStorage.hpp.
write_bin()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::write_bin (const char * fname, const size_type = 0) const inline
write a native binary file
Parameters
[in] fname file name
Definition at line 1555 of file CompressedStorage.hpp.
write_mm()
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> void hif::CRS< ValueType, IndexType, IndPtrType >::write_mm (const char * fname) const inline
Write data to a MatrixMarket file.
Parameters
[in] fname File name
See also
read_mm
Definition at line 1576 of file CompressedStorage.hpp.
Member Data Documentation
_ncols
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> size_type hif::CRS< ValueType, IndexType, IndPtrType >::_ncols protected
number of columns
Definition at line 1735 of file CompressedStorage.hpp.
Referenced by hif::CRS< value_type, index_type, IndPtrType >::check_validity(), hif::CRS< value_type, index_type, IndPtrType >::compute_perm(), hif::CRS< value_type, index_type, IndPtrType >::CRS(), hif::CRS< value_type, index_type, IndPtrType >::destroy(), hif::CRS< value_type, index_type, IndPtrType >::ncols(), hif::CRS< value_type, index_type, IndPtrType >::prune(), hif::CRS< value_type, index_type, IndPtrType >::read_mm(), hif::CRS< value_type, index_type, IndPtrType >::resize_ncols(), hif::CRS< value_type, index_type, IndPtrType >::scale_diag_right(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_mrhs_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_lower_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_mrhs_tran(), hif::CRS< value_type, index_type, IndPtrType >::solve_as_strict_upper_tran(), hif::CRS< value_type, index_type, IndPtrType >::split(), hif::CRS< value_type, index_type, IndPtrType >::split_ccs(), and hif::CRS< value_type, index_type, IndPtrType >::write_mm().
ROW_MAJOR
template<class ValueType, class IndexType, class IndPtrType = std::ptrdiff_t> constexpr bool hif::CRS< ValueType, IndexType, IndPtrType >::ROW_MAJOR = true static
row major
Definition at line 844 of file CompressedStorage.hpp.
The documentation for this class was generated from the following file:
CompressedStorage.hpp