HIFIR: hif::PivotCrout Class Reference
hif::PivotCrout Class Reference
Algorithms » Crout Update
Crout update in deferred fashion with pivotingThe idea of this class is to implement Crout kernels that wrap around a common factor—step. In this case, the class Crout is as simple (in terms of data size) as an integer. It also supports implicitly casting to integer as well as increment operations (both suffix and prefix versions). The whole disign can be demonstrate by the following C++ pseudocode:
#include <PivotCrout.hpp>
Public Types
using size_type = Crout::size_type
size type
Public Types inherited from hif::Crout
using size_type = std::size_t
size type
Public Member Functions
template<class ScaleArray , class CcsType , class PermType , class AugCcsType , class IndPtrArray , class DiagType , class AugCrsType >
DiagType::value_type compute_dk (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p_inv, const size_type qk, const AugCcsType &L, const IndPtrArray &L_start, const DiagType &d, const AugCrsType &U) const
compute diagonal entry
template<class ScaleArray , class CrsType , class PermType , class AugCcsType , class DiagType , class AugCrsType , class IndPtrArray , class SpVecType >
void compute_ut (const ScaleArray &s, const CrsType &crs_A, const ScaleArray &t, const size_type pk, const PermType &q_inv, const AugCcsType &L, const DiagType &d, const AugCrsType &U, const IndPtrArray &U_start, SpVecType &ut) const
dual of the compute_l, i.e. computing the row of U
template<class ScaleArray , class CcsType , class PermType , class AugCcsType , class IndPtrArray , class DiagType , class AugCrsType , class SpVecType >
void compute_l (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p_inv, const size_type qk, const AugCcsType &L, const IndPtrArray &L_start, const DiagType &d, const AugCrsType &U, SpVecType &l) const
compute the column vector of L of current step
template<class CsType , class IndPtrArray >
void update_compress (CsType &T, IndPtrArray &start) const
compress L and U and update their corresponding starting positions
template<class AugCsType , class KappaArray >
bool update_kappa (const AugCsType &T, KappaArray &kappa, const size_type entry=0u)
estimate the inverse norm with augmented ds
template<class CsType >
void defer_entry (const size_type to_idx, CsType &T) const
defer an secondary entry, i.e., rows in CCS and columns in CRS
template<class AugCsType , class PermType , class InvPermType , class DiagArrayType , class SpVecType >
void interchange (const size_type pivot, AugCsType &T, PermType &p, InvPermType &p_inv, DiagArrayType &d, SpVecType &a_k) const
interchagen with pivot for pivoting with Crout LU
template<class ScaleArray , class PermType , class PermType2 , class CcsType , class CrsType , class CroutInfoStreamer , class IndPtrType , class PivotUnaryOpL , class PivotUnaryOpU , class AugCcsType , class DiagType , class AugCrsType , class SpVecType >
std::pair< int, int > apply_thres_pivot (const ScaleArray &s, const ScaleArray &t, const CcsType &A_ccs, const CrsType &A_crs, const size_type m, const double gamma, const int max_steps, const CroutInfoStreamer &Crout_info, const IndPtrType &L_start, const IndPtrType &U_start, const PivotUnaryOpL &op_l, const PivotUnaryOpU &op_ut, PermType &p, PermType2 &p_inv, PermType &q, PermType2 &q_inv, AugCcsType &L, DiagType &d, AugCrsType &U, SpVecType &l, SpVecType &ut) const
Apply inverse-based rook pivoting.
Public Member Functions inherited from hif::Crout
Crout ()
default constructor
Crout (const Crout &)=default
Crout & operator= (const Crout &)=default
Crout & operator= (const size_type step)
assign to a step
const Crout & operator++ ()
increment Crout step
Crout operator++ (int)
increment Crout step, suffix
operator size_type () const
implicitly casting to size_type
size_type defers () const
get the current defers
size_type deferred_step () const
get the deferred step
void increment_defer_counter ()
increment the defer counter
template<class ArrayType >
void compress_array (ArrayType &v) const
compress an array without deferrals (gaps)
template<class ArrayIn , class ArrayOut >
void assign_gap_array (const ArrayIn &r, ArrayOut &l) const
compress an array and assign the no-gapped value to another one
template<class ScaleArray , class CrsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class CcsType , class SpVecType >
void compute_ut (const ScaleArray &s, const CrsType &crs_A, const ScaleArray &t, const size_type pk, const PermType &q, const CcsType &L, const IndPtrArray &L_start, const ListArray &L_list, const DiagType &d, const CrsType &U, const IndPtrArray &U_start, SpVecType &ut) const
dual of the compute_l, i.e. computing the row of U
template<bool IsSymm, class ScaleArray , class CcsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class CrsType , class SpVecType >
void compute_l (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p, const size_type qk, const size_type m, const CcsType &L, const IndPtrArray &L_start, const DiagType &d, const CrsType &U, const IndPtrArray &U_start, const ListArray &U_list, SpVecType &l) const
compute the column vector of L of current step
template<class ScaleArray , class CcsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class SpVecType >
void compute_symm (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p, const size_type qk, const size_type m, const CcsType &L, const IndPtrArray &L_start, const ListArray &L_list, const DiagType &d, SpVecType &l) const
compute the column vector of L of current step for
template<class CsType , class ListArray , class IndPtrArray >
void update_compress (CsType &T, ListArray &list, IndPtrArray &start) const
compress L and U and update their corresponding starting positions and linked lists
template<class CcsType , class IndPtrArray >
void symm_update_lstart (const CcsType &L, const typename CcsType::size_type m, IndPtrArray &L_start) const
another starting array needed in symmetric computation to get the offsets
template<class CsType , class ListArray , class IndPtrArray , class KappaArray >
bool update_kappa (const CsType &T, const ListArray &list, const IndPtrArray &start, KappaArray &kappa) const
estimate the inverse norm
template<bool IsSymm, class SpVecType , class DiagType >
std::enable_if<!IsSymm >::type update_diag (const SpVecType &l, const SpVecType &ut, const size_type m, DiagType &d) const
update the current diagonal entry
template<bool IsSymm, class SpVecType , class DiagType >
std::enable_if< IsSymm >::type update_diag (const SpVecType &, const SpVecType &ut, const size_type m, DiagType &d) const
update the current diagonal entry
template<class DiagType , class SpVecType >
bool scale_inv_diag (const DiagType &d, SpVecType &v) const
scale the computed row/column vectors by current diagonal inverse
template<class CsType , class IndPtrArray , class ListArray >
void defer_entry (const size_type to_idx, const IndPtrArray &start, CsType &T, ListArray &list) const
defer an secondary entry
template<class CcsType , class IndPtrArray , class ListArray >
void symm_defer_l (const size_type to_idx, const IndPtrArray &L_start, CcsType &L, ListArray &L_list, IndPtrArray &L_offsets) const
for symmetric leading block, we need to fix the offset positions while we do deferring
Additional Inherited Members
Protected Member Functions inherited from hif::Crout
template<class ScaleArray , class CrsType , class PermType , class SpVecType >
void _load_arow (const ScaleArray &s, const CrsType &crs_A, const ScaleArray &t, const size_type &pk, const PermType &q_inv, SpVecType &ut) const
load a row of A to ut buffer
template<bool IsSymm, class ScaleArray , class CcsType , class PermType , class SpVecType >
void _load_acol (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p_inv, const size_type &qk, const size_type m, SpVecType &l) const
load a column of A to l buffer
Protected Attributes inherited from hif::Crout
size_type _step
current step
size_type _defers
deferring counter
Detailed Description
Crout update in deferred fashion with pivoting
The idea of this class is to implement Crout kernels that wrap around a common factor—step. In this case, the class Crout is as simple (in terms of data size) as an integer. It also supports implicitly casting to integer as well as increment operations (both suffix and prefix versions). The whole disign can be demonstrate by the following C++ pseudocode:
for (Crout crout; crout < m; ++crout) {
  crout.do_work1(...);
  crout.do_work2(...);
  ...
}
Definition at line 60 of file PivotCrout.hpp.
Member Typedef Documentation
size_type
using hif::PivotCrout::size_type = Crout::size_type
size type
Definition at line 62 of file PivotCrout.hpp.
Member Function Documentation
apply_thres_pivot()
template<class ScaleArray , class PermType , class PermType2 , class CcsType , class CrsType , class CroutInfoStreamer , class IndPtrType , class PivotUnaryOpL , class PivotUnaryOpU , class AugCcsType , class DiagType , class AugCrsType , class SpVecType > std::pair<int, int> hif::PivotCrout::apply_thres_pivot (const ScaleArray & s, const ScaleArray & t, const CcsType & A_ccs, const CrsType & A_crs, const size_type m, const double gamma, const int max_steps, const CroutInfoStreamer & Crout_info, const IndPtrType & L_start, const IndPtrType & U_start, const PivotUnaryOpL & op_l, const PivotUnaryOpU & op_ut, PermType & p, PermType2 & p_inv, PermType & q, PermType2 & q_inv, AugCcsType & L, DiagType & d, AugCrsType & U, SpVecType & l, SpVecType & ut) const inline
Apply inverse-based rook pivoting.
Template Parameters
ScaleArray Row/column scaling array, see Array
PermType Permutation array type
PermType2 Inverse permutation array type
CcsType Ccs storage type, see CCS
CrsType Crs storage type, see CRS
CroutInfoStreamer Crout update information streamer
IndPtrType Integer array type for storing position information
PivotUnaryOpL Unary predictor for finding pivot in L
PivotUnaryOpU Unary predictor for finding pivot in U
AugCcsType Augmented ccs storage type, see AugCCS
DiagType Diagonal array type, see Array
AugCrsType Augmented crs storage type, see AugCRS
SpVecType Sparse vector workspace, see SparseVector
Parameters
[in] s row scaling vector
[in] t column scaling vector
[in] A_ccs input coefficient matrix in CCS
[in] A_crs input coefficient matrix in CRS
[in] m leading dimension size
[in] gamma thresholding for rook pivoting
[in] max_steps maximum number of pivoting steps
[in] Crout_info information streamer (empty for non-verbose mode)
[in] L_start starting positions in columns for L
[in] U_start starting positions in rows for U
[in] op_l unary operator for finding a pivot in L
[in] op_ut unary operator for finding a pivot in U
[in,out] p row permutation array, will be updated due to pivoting
[in,out] p_inv inverse of row permutation, will be updated
[in,out] q column permutation array, will be updated due to pivoting
[in,out] q_inv inverse of column permutation, will be updated
[in,out] L lower factor, will be permuted if necessary
[in,out] d diagonal factor (vector), will be updated for current step
[in,out] U upper factor, will be permuted if ncessary
[out] l sparse vector work space for computing
[out] ut sparse vector work space for computing
Returns
number of pivots in row and column swappings.
See also
interchange
Regarding op_l and op_u, we find a pivot in L if and only if it satisfies op_l condition, i.e., op_l(pivot_l)==true.
Definition at line 510 of file PivotCrout.hpp.
References hif::Crout::_defers, hif::Crout::deferred_step(), and hif::warning().
compute_dk()
template<class ScaleArray , class CcsType , class PermType , class AugCcsType , class IndPtrArray , class DiagType , class AugCrsType > DiagType::value_type hif::PivotCrout::compute_dk (const ScaleArray & s, const CcsType & ccs_A, const ScaleArray & t, const PermType & p_inv, const size_type qk, const AugCcsType & L, const IndPtrArray & L_start, const DiagType & d, const AugCrsType & U) const inline
compute diagonal entry
Template Parameters
ScaleArray row/column scaling diagonal matrix type, see Array
CcsType ccs format, see CCS
PermType permutation matrix type, see Array
AugCcsType ccs format, see AugCCS
IndPtrArray position array type, see Array
DiagType array used for storing diagonal array, see Array
AugCrsType crs format, see AugCRS
Parameters
[in] s row scaling matrix from preprocessing
[in] ccs_A input matrix in ccs scheme
[in] t column scaling matrix from preprocessing
[in] p_inv row inverse permutation (with tail indices)
[in] qk permutated column index (with deferring)
[in] L lower part of decomposition
[in] L_start position array storing the starting locations of L
[in] d diagonal entries
[in] U augmented U matrix
Returns
diagonal entry value
See also
compute_ut, compute_l
This routine computes the current diagonal entry of Mathematically, this routine is to compute:
Definition at line 93 of file PivotCrout.hpp.
References hif::Crout::_step, and hif::Crout::deferred_step().
compute_l()
template<class ScaleArray , class CcsType , class PermType , class AugCcsType , class IndPtrArray , class DiagType , class AugCrsType , class SpVecType > void hif::PivotCrout::compute_l (const ScaleArray & s, const CcsType & ccs_A, const ScaleArray & t, const PermType & p_inv, const size_type qk, const AugCcsType & L, const IndPtrArray & L_start, const DiagType & d, const AugCrsType & U, SpVecType & l) const inline
compute the column vector of L of current step
Template Parameters
ScaleArray row/column scaling diagonal matrix type, see Array
CcsType ccs format, see CCS
PermType permutation matrix type, see Array
AugCcsType ccs format, see AugCCS
IndPtrArray position array type, see Array
DiagType array used for storing diagonal array, see Array
AugCrsType crs format, see AugCRS
SpVecType sparse vector for storing l, see SparseVector
Parameters
[in] s row scaling matrix from preprocessing
[in] ccs_A input matrix in ccs scheme
[in] t column scaling matrix from preprocessing
[in] p_inv row inverse permutation (with tail indices)
[in] qk permutated column index (with deferring)
[in] L lower part of decomposition
[in] L_start position array storing the starting locations of L
[in] d diagonal entries
[in] U augmented U matrix
[in,out] l upon input, it contains preloaded column in A via load_acol; upon output, it contains the factor of .
See also
compute_ut
This routine computes the current column vector of (w/o diagonal scaling). Mathematically, this routine is to compute:
It's worth noting that, conceptally, the formula above is nothing but a matrix vector operation. However, standard implementation won't give good performance (especially with consideration of cache performance), this is because is stored in column major whereas row major for . Therefore, the actual implementation is in the fashion that loops through in column major while keeping as much static as possible.
Regarding the complexity cost, it takes , where for computing the matrix vector operation.
Definition at line 298 of file PivotCrout.hpp.
References hif::Crout::_step, and hif::Crout::deferred_step().
compute_ut()
template<class ScaleArray , class CrsType , class PermType , class AugCcsType , class DiagType , class AugCrsType , class IndPtrArray , class SpVecType > void hif::PivotCrout::compute_ut (const ScaleArray & s, const CrsType & crs_A, const ScaleArray & t, const size_type pk, const PermType & q_inv, const AugCcsType & L, const DiagType & d, const AugCrsType & U, const IndPtrArray & U_start, SpVecType & ut) const inline
dual of the compute_l, i.e. computing the row of U
Template Parameters
ScaleArray row scaling diagonal matrix type, see Array
CrsType crs format, see CRS
PermType permutation matrix type, see Array
AugCcsType ccs format, see AugCCS
DiagType diagonal matrix type, see Array
AugCrsType crs format, see AugCRS
IndPtrArray position array type, see Array
SpVecType work array for current row vector, see SparseVector
Parameters
[in] s row scaling matrix from preprocessing
[in] crs_A input matrix in crs format
[in] t column scaling matrix from preprocessing
[in] pk permuted row index (with deferring)
[in] q_inv inverse column permutation (with tails indices)
[in] L lower part
[in] d diagonal vector
[in] U upper part
[in] U_start leading row positions of current _step
[in,out] ut upon input, it contains preloaded row in A via load_arow; upon output, it contains the factor of .
See also
compute_l
This routine computes the current row vector of (w/o diagonal scaling). Mathematically, this routine is to compute:
It's worth noting that, conceptally, the formula above is nothing but a vector matrix operation. However, standard implementation won't give good performance (especially with consideration of cache performance), this is because is stored in column major whereas row major for . Therefore, the actual implementation is in the fashion that loops through in row major while keeping as much static as possible.
Regarding computation cost, it takes , where for computing the vector matrix operation.
Definition at line 195 of file PivotCrout.hpp.
References hif::Crout::_step, and hif::Crout::deferred_step().
interchange()
template<class AugCsType , class PermType , class InvPermType , class DiagArrayType , class SpVecType > void hif::PivotCrout::interchange (const size_type pivot, AugCsType & T, PermType & p, InvPermType & p_inv, DiagArrayType & d, SpVecType & a_k) const inline
interchagen with pivot for pivoting with Crout LU
Template Parameters
AugCsType Augmented compressed data types, see AugCRS or AugCCS
PermType Permutation array type, see BiPermMatrix
InvPermType Inverse permutation array type
DiagArrayType Diagonal array type, see Array
SpVecType Array type for storing current row or column of A
Parameters
[in] pivot Pivoting position
[in,out] T Either lower or upper factors from Crout LU and step k
[in,out] p Permutation array
[in,out] p_inv Inverse permutation mapping of p
[in,out] d diagonal array
[in,out] a_k k-th row or column of A (scaled and permuted)
Definition at line 454 of file PivotCrout.hpp.
References hif::Crout::deferred_step().
update_compress()
template<class CsType , class IndPtrArray > void hif::PivotCrout::update_compress (CsType & T, IndPtrArray & start) const inline
compress L and U and update their corresponding starting positions
Template Parameters
CsType either AugCRS or AugCCS
IndPtrArray position array type, see Array
Parameters
[in,out] T strictly lower (L) or upper (U) matrices
[in,out] start local positions
Note
This routine essentially compresses deferred_step to _step
All other routines should be called before this one, and deferred_step therein are conceptually the current Crout step
Definition at line 362 of file PivotCrout.hpp.
References hif::Crout::_defers, hif::Crout::_step, and hif::Crout::deferred_step().
update_kappa()
template<class AugCsType , class KappaArray > bool hif::PivotCrout::update_kappa (const AugCsType & T, KappaArray & kappa, const size_type entry = 0u) inline
estimate the inverse norm with augmented ds
Template Parameters
AugCsType Augmented compressed storage, see AugCRS or AugCCS
KappaArray Inverse norm array type, see Array
Parameters
[in] T Augmented compressed storage input
[in,out] kappa history of inverse norms
[in] entry (optional) concatenate entry to T_{k-1} for computing the absolute conditioning of leading block of T, default value is k, i.e., _step
Definition at line 394 of file PivotCrout.hpp.
References hif::Crout::_step, and hif::Crout::deferred_step().
The documentation for this class was generated from the following file:
PivotCrout.hpp