HIFIR: hif::AugCCS< CcsType > Class Template Reference
hif::AugCCS< CcsType > Class Template Reference
Data Structures
Augmented CCS data structure.
#include <AugmentedStorage.hpp>
Public Types
typedef AugCCS this_type
this
typedef CcsType ccs_type
ccs type
typedef ccs_type::other_type crs_type
crs
typedef ccs_type::size_type size_type
size
typedef _base::iarray_type iarray_type
index array
typedef iarray_type::value_type index_type
index type
typedef _base::indptr_type indptr_type
index_pointer
typedef _base::iparray_type iparray_type
indptr array
typedef ccs_type::value_type value_type
value
Public Types inherited from hif::internal::AugmentedCore< CcsType::index_type, CcsType::indptr_type >
typedef CcsType::index_type index_type
index
typedef Array< index_type > iarray_type
container
typedef CcsType::indptr_type indptr_type
index_pointer type
typedef Array< indptr_type > iparray_type
indptr array
typedef iarray_type::size_type size_type
size
typedef AugmentedCore this_type
this
typedef iarray_type::iterator iterator
iterator type
Public Member Functions
AugCCS ()=default
default constructor
AugCCS (const size_type nrows, const size_type ncols, const size_type nnz=0u, bool reserve=true)
constructor for general matrices
AugCCS (const this_type &other, bool clone=false)
constructor to either clone or shallow copy another AugCCS
AugCCS (this_type &&)=default
this_type & operator= (const this_type &)=default
this_type & operator= (this_type &&)=default
void build_aug (const ccs_type &ccs, bool clone=false)
build augmented data structure based on mature CCS matrices
void build_aug (crs_type &&ccs)
build augmented data structure based on mature CCS
void build_aug (const crs_type &crs)
build augmented data structured based on mature CRS matrices
indptr_type start_row_id (const size_type row) const
given row index, get the starting row handle/ID
indptr_type start_aug_id (const size_type row) const
unified interface for getting starting augmented ID
indptr_type next_row_id (const size_type row_id) const
given a row handle, get its next location
indptr_type next_aug_id (const size_type aug_id) const
unified interface for advancing to next augmented ID
index_type col_idx (const size_type row_id) const
given a row handle/ID, get its corresponding column index
index_type primary_idx (const size_type aug_id) const
unified interface for getting primary (col) index
void reserve (const size_type nnz)
reserve space for nnz arrays
value_type val_from_row_id (const size_type row_id) const
get the value from row handle
value_type val_from_aug_id (const size_type aug_id) const
unified interface for value from augmented ID
size_type nnz_in_row (const size_type row) const
get the total number of nonzeros in row
size_type nnz_in_secondary (const size_type row) const
unified interface for nnz in secondary direction
void interchange_rows (const size_type i, const size_type k)
interchange two rows
void interchange_entries (const size_type i, const size_type k)
unified interface for interchanging
void defer_row (const size_type from, const size_type to)
defer a row to the end
void defer_entry (const size_type from, const size_type to)
unified interface for deferring
iarray_type & col_ind ()
const iarray_type & col_ind () const
iparray_type & row_start ()
const iparray_type & row_start () const
iparray_type & row_end ()
const iparray_type * row_end () const
iparray_type & row_next ()
const iparray_type & row_next () const
iarray_type & row_counts ()
const iarray_type & row_counts () const
void begin_assemble_cols ()
begin to assemble columns
template<class Iter , class ValueArray >
void push_back_col (const size_type col, Iter first, Iter last, const ValueArray &v)
push back a column with row indices
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void push_back_col (const size_type col, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back a column with two lists of row indices
Public Member Functions inherited from hif::internal::AugmentedCore< CcsType::index_type, CcsType::indptr_type >
AugmentedCore ()=default
default constructor
AugmentedCore (const size_type nlist, const size_type nnz=0, bool reserve=true)
constructor with number of lists
AugmentedCore (const this_type &other, bool clone=false)
shallow copy of clone
AugmentedCore (this_type &&)=default
this_type & operator= (const this_type &)=default
this_type & operator= (this_type &&)=default
indptr_type val_pos_idx (const size_type nid) const
given a node handle, query its value position (index)
iparray_type & val_pos ()
const iparray_type & val_pos () const
void reserve (const size_type nnz)
reserve spaces for nnz arrays
iparray_type & secondary_start ()
const iparray_type & secondary_start () const
iparray_type & secondary_end ()
const iparray_type & secondary_end () const
iarray_type & secondary_counts ()
const iarray_type & secondary_counts () const
Static Public Attributes
static constexpr bool ROW_MAJOR = false
row major flag
Private Types
typedef internal::AugmentedCore< typename CcsType::index_type, typename CcsType::indptr_type > _base
Static Private Attributes
static constexpr indptr_type _NIL = _base::_NIL
Additional Inherited Members
Static Public Member Functions inherited from hif::internal::AugmentedCore< CcsType::index_type, CcsType::indptr_type >
static constexpr bool is_nil (const indptr_type i)
check if a given node handle is NIL or not
Protected Member Functions inherited from hif::internal::AugmentedCore< CcsType::index_type, CcsType::indptr_type >
void _begin_assemble_nodes (const size_type nlist)
begin assemble nodes
void _push_back_nodes (const size_type entry, Iter first, Iter last)
update linked lists given new nodes from back
indptr_type _start_node (const size_type lid) const
get starting node ID
indptr_type _next_node (const size_type nid) const
get the next node ID
index_type _node_ind (const size_type nid) const
get node item ({col-,row-}index in aug-{ccx,crs}, correspondingly)
void _swap_val_pos_exp (const size_type p1, const size_type p2)
given two existing indices, swap them explicitly
void _rotate_val_pos_left (const size_type n, const size_type src)
rotate value positions toward left
void _rotate_val_pos_right (const size_type n, const size_type src)
rotate value positions toward right
void _interchange_ik_head_tail (const size_type i, const size_type k)
interchange the head and tail nodes given list i and k
void _build_aug (const size_type nlist, const iparray_type &ind_start, const iarray_type &indices)
build augmented cores based on compressed storages
size_type _nodes_in_list (const size_type i) const
query total number of in a certain list
Protected Attributes inherited from hif::internal::AugmentedCore< CcsType::index_type, CcsType::indptr_type >
iarray_type _node_inds
indices (values) of each node
iparray_type _node_start
head nodes
iparray_type _node_next
next nodes
iparray_type _node_end
ending positions
iparray_type _val_pos
value positions
iparray_type _val_pos_inv
value position inverse, i.e. inv(_val_pos)
iarray_type _node_counts
number of nodes per list
Static Protected Attributes inherited from hif::internal::AugmentedCore< CcsType::index_type, CcsType::indptr_type >
static constexpr indptr_type _NIL
Detailed Description
template<class CcsType>
class hif::AugCCS< CcsType >
Augmented CCS data structure.
Template Parameters
CcsType A CCS type instantiation
See also
AugCRS
Note
This class inherits from CCS
Definition at line 760 of file AugmentedStorage.hpp.
Member Typedef Documentation
_base
template<class CcsType > typedef internal::AugmentedCore<typename CcsType::index_type, typename CcsType::indptr_type> hif::AugCCS< CcsType >::_base private
Definition at line 765 of file AugmentedStorage.hpp.
ccs_type
template<class CcsType > typedef CcsType hif::AugCCS< CcsType >::ccs_type
ccs type
Definition at line 769 of file AugmentedStorage.hpp.
crs_type
template<class CcsType > typedef ccs_type::other_type hif::AugCCS< CcsType >::crs_type
crs
Definition at line 770 of file AugmentedStorage.hpp.
iarray_type
template<class CcsType > typedef _base::iarray_type hif::AugCCS< CcsType >::iarray_type
index array
Definition at line 772 of file AugmentedStorage.hpp.
index_type
template<class CcsType > typedef iarray_type::value_type hif::AugCCS< CcsType >::index_type
index type
Definition at line 773 of file AugmentedStorage.hpp.
indptr_type
template<class CcsType > typedef _base::indptr_type hif::AugCCS< CcsType >::indptr_type
index_pointer
Definition at line 774 of file AugmentedStorage.hpp.
iparray_type
template<class CcsType > typedef _base::iparray_type hif::AugCCS< CcsType >::iparray_type
indptr array
Definition at line 775 of file AugmentedStorage.hpp.
size_type
template<class CcsType > typedef ccs_type::size_type hif::AugCCS< CcsType >::size_type
size
Definition at line 771 of file AugmentedStorage.hpp.
this_type
template<class CcsType > typedef AugCCS hif::AugCCS< CcsType >::this_type
this
Definition at line 768 of file AugmentedStorage.hpp.
value_type
template<class CcsType > typedef ccs_type::value_type hif::AugCCS< CcsType >::value_type
value
Definition at line 776 of file AugmentedStorage.hpp.
Constructor & Destructor Documentation
AugCCS() [1/4]
template<class CcsType > hif::AugCCS< CcsType >::AugCCS () default
default constructor
AugCCS() [2/4]
template<class CcsType > hif::AugCCS< CcsType >::AugCCS (const size_type nrows, const size_type ncols, const size_type nnz = 0u, bool reserve = true) inline
constructor for general matrices
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] nnz ignored if zero (default)
[in] reserve if true (default), then reserve spaces
Definition at line 791 of file AugmentedStorage.hpp.
AugCCS() [3/4]
template<class CcsType > hif::AugCCS< CcsType >::AugCCS (const this_type & other, bool clone = false) inline
constructor to either clone or shallow copy another AugCCS
Parameters
[in] other another augmented CCS
[in] clone if false (default), then do shallow copy
Definition at line 798 of file AugmentedStorage.hpp.
AugCCS() [4/4]
template<class CcsType > hif::AugCCS< CcsType >::AugCCS (this_type &&) default
Member Function Documentation
begin_assemble_cols()
template<class CcsType > void hif::AugCCS< CcsType >::begin_assemble_cols () inline
begin to assemble columns
Definition at line 1090 of file AugmentedStorage.hpp.
build_aug() [1/3]
template<class CcsType > void hif::AugCCS< CcsType >::build_aug (const ccs_type & ccs, bool clone = false) inline
build augmented data structure based on mature CCS matrices
Parameters
[in] ccs mature CCS system
[in] clone if false (default), crs will be shallow copied
Warning
Advanced usage routine!
Definition at line 810 of file AugmentedStorage.hpp.
References hif::DATA_UNDEF, and hif::error().
build_aug() [2/3]
template<class CcsType > void hif::AugCCS< CcsType >::build_aug (crs_type && ccs) inline
build augmented data structure based on mature CCS
Parameters
[in] ccs temp CCS system
Definition at line 824 of file AugmentedStorage.hpp.
References hif::DATA_UNDEF, and hif::error().
build_aug() [3/3]
template<class CcsType > void hif::AugCCS< CcsType >::build_aug (const crs_type & crs) inline
build augmented data structured based on mature CRS matrices
Parameters
[in] crs mature CRS system
Warning
Advanced usage routine
Definition at line 838 of file AugmentedStorage.hpp.
References hif::DATA_UNDEF, and hif::error().
col_idx()
template<class CcsType > index_type hif::AugCCS< CcsType >::col_idx (const size_type row_id) const inline
given a row handle/ID, get its corresponding column index
Parameters
[in] row_id row handle/ID
Definition at line 875 of file AugmentedStorage.hpp.
Referenced by hif::AugCCS< CcsType >::defer_row(), hif::AugCCS< CcsType >::interchange_rows(), and hif::AugCCS< CcsType >::primary_idx().
col_ind() [1/2]
template<class CcsType > iarray_type& hif::AugCCS< CcsType >::col_ind () inline
Definition at line 1078 of file AugmentedStorage.hpp.
col_ind() [2/2]
template<class CcsType > const iarray_type& hif::AugCCS< CcsType >::col_ind () const inline
Definition at line 1079 of file AugmentedStorage.hpp.
defer_entry()
template<class CcsType > void hif::AugCCS< CcsType >::defer_entry (const size_type from, const size_type to) inline
unified interface for deferring
See also
defer_row
Definition at line 1073 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::defer_row().
defer_row()
template<class CcsType > void hif::AugCCS< CcsType >::defer_row (const size_type from, const size_type to) inline
defer a row to the end
Parameters
[in] from which row to defer
[in] to the current pass-of-end row index
Warning
the parameter to must be current pass-of-last row
Definition at line 1046 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::col_idx(), hif::AugCCS< CcsType >::next_row_id(), and hif::AugCCS< CcsType >::start_row_id().
Referenced by hif::AugCCS< CcsType >::defer_entry().
interchange_entries()
template<class CcsType > void hif::AugCCS< CcsType >::interchange_entries (const size_type i, const size_type k) inline
unified interface for interchanging
See also
interchange_rows
Definition at line 1038 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::interchange_rows().
interchange_rows()
template<class CcsType > void hif::AugCCS< CcsType >::interchange_rows (const size_type i, const size_type k) inline
interchange two rows
Note
This is the core operation for augmented data structure
Parameters
[in] i i-th row
[in] k k-th row
Mathematically, after calling this routine, the i-th and k-th rows will be interchanged. The total complexity of this routine is linear with respect to the total number of nonzeros in rows i and k.
Definition at line 930 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::_NIL, hif::AugCCS< CcsType >::col_idx(), hif::AugCCS< CcsType >::next_row_id(), and hif::AugCCS< CcsType >::start_row_id().
Referenced by hif::AugCCS< CcsType >::interchange_entries().
next_aug_id()
template<class CcsType > indptr_type hif::AugCCS< CcsType >::next_aug_id (const size_type aug_id) const inline
unified interface for advancing to next augmented ID
Parameters
[in] aug_id augmented ID
Definition at line 869 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::next_row_id().
next_row_id()
template<class CcsType > indptr_type hif::AugCCS< CcsType >::next_row_id (const size_type row_id) const inline
given a row handle, get its next location
Parameters
[in] row_id row handle/ID
Definition at line 863 of file AugmentedStorage.hpp.
Referenced by hif::AugCCS< CcsType >::defer_row(), hif::AugCCS< CcsType >::interchange_rows(), and hif::AugCCS< CcsType >::next_aug_id().
nnz_in_row()
template<class CcsType > size_type hif::AugCCS< CcsType >::nnz_in_row (const size_type row) const inline
get the total number of nonzeros in row
Parameters
[in] row row index
Definition at line 913 of file AugmentedStorage.hpp.
Referenced by hif::AugCCS< CcsType >::nnz_in_secondary().
nnz_in_secondary()
template<class CcsType > size_type hif::AugCCS< CcsType >::nnz_in_secondary (const size_type row) const inline
unified interface for nnz in secondary direction
Definition at line 918 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::nnz_in_row().
operator=() [1/2]
template<class CcsType > this_type& hif::AugCCS< CcsType >::operator= (const this_type &) default
operator=() [2/2]
template<class CcsType > this_type& hif::AugCCS< CcsType >::operator= (this_type &&) default
primary_idx()
template<class CcsType > index_type hif::AugCCS< CcsType >::primary_idx (const size_type aug_id) const inline
unified interface for getting primary (col) index
Parameters
[in] aug_id augmented ID
Definition at line 881 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::col_idx().
push_back_col() [1/2]
template<class CcsType > template<class Iter , class ValueArray > void hif::AugCCS< CcsType >::push_back_col (const size_type col, Iter first, Iter last, const ValueArray & v) inline
push back a column with row indices
Template Parameters
Iter iterator type
ValueArray dense value array
Parameters
[in] col current column index (C-based)
[in] first starting iterator
[in] last pass-of-end iterator
[in] v dense value array, the value can be queried from indices
Definition at line 1103 of file AugmentedStorage.hpp.
push_back_col() [2/2]
template<class CcsType > template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 > void hif::AugCCS< CcsType >::push_back_col (const size_type col, Iter1 first1, Iter1 last1, const ValueArray1 & v1, Iter2 first2, Iter2 last2, const ValueArray2 & v2) inline
push back a column with two lists of row indices
Template Parameters
Iter1 iterator type
ValueArray1 dense value array
Iter2 iterator type
ValueArray2 dense value array
Parameters
[in] col current column index (c-based)
[in] first1 starting iterator for list 1
[in] last1 pass-of-end iterator for list 1
[in] v1 dense value array for list 1
[in] first2 starting iterator for list 2
[in] last2 pass-of-end iterator for list 2
[in] v2 dense value array for list 2
Definition at line 1122 of file AugmentedStorage.hpp.
reserve()
template<class CcsType > void hif::AugCCS< CcsType >::reserve (const size_type nnz) inline
reserve space for nnz arrays
Parameters
[in] nnz total number of nonzeros
Definition at line 887 of file AugmentedStorage.hpp.
row_counts() [1/2]
template<class CcsType > iarray_type& hif::AugCCS< CcsType >::row_counts () inline
Definition at line 1086 of file AugmentedStorage.hpp.
row_counts() [2/2]
template<class CcsType > const iarray_type& hif::AugCCS< CcsType >::row_counts () const inline
Definition at line 1087 of file AugmentedStorage.hpp.
row_end() [1/2]
template<class CcsType > iparray_type& hif::AugCCS< CcsType >::row_end () inline
Definition at line 1082 of file AugmentedStorage.hpp.
row_end() [2/2]
template<class CcsType > const iparray_type* hif::AugCCS< CcsType >::row_end () const inline
Definition at line 1083 of file AugmentedStorage.hpp.
row_next() [1/2]
template<class CcsType > iparray_type& hif::AugCCS< CcsType >::row_next () inline
Definition at line 1084 of file AugmentedStorage.hpp.
row_next() [2/2]
template<class CcsType > const iparray_type& hif::AugCCS< CcsType >::row_next () const inline
Definition at line 1085 of file AugmentedStorage.hpp.
row_start() [1/2]
template<class CcsType > iparray_type& hif::AugCCS< CcsType >::row_start () inline
Definition at line 1080 of file AugmentedStorage.hpp.
row_start() [2/2]
template<class CcsType > const iparray_type& hif::AugCCS< CcsType >::row_start () const inline
Definition at line 1081 of file AugmentedStorage.hpp.
start_aug_id()
template<class CcsType > indptr_type hif::AugCCS< CcsType >::start_aug_id (const size_type row) const inline
unified interface for getting starting augmented ID
Definition at line 857 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::start_row_id().
start_row_id()
template<class CcsType > indptr_type hif::AugCCS< CcsType >::start_row_id (const size_type row) const inline
given row index, get the starting row handle/ID
Parameters
[in] row row index
Returns
first row handle in the augmented data structure
Definition at line 852 of file AugmentedStorage.hpp.
Referenced by hif::AugCCS< CcsType >::defer_row(), hif::AugCCS< CcsType >::interchange_rows(), and hif::AugCCS< CcsType >::start_aug_id().
val_from_aug_id()
template<class CcsType > value_type hif::AugCCS< CcsType >::val_from_aug_id (const size_type aug_id) const inline
unified interface for value from augmented ID
Parameters
[in] aug_id row augmented ID
Definition at line 907 of file AugmentedStorage.hpp.
References hif::AugCCS< CcsType >::val_from_row_id().
val_from_row_id()
template<class CcsType > value_type hif::AugCCS< CcsType >::val_from_row_id (const size_type row_id) const inline
get the value from row handle
Parameters
[in] row_id row handle/ID
Definition at line 901 of file AugmentedStorage.hpp.
Referenced by hif::AugCCS< CcsType >::val_from_aug_id().
Member Data Documentation
_NIL
template<class CcsType > constexpr indptr_type hif::AugCCS< CcsType >::_NIL = _base::_NIL static private
Definition at line 780 of file AugmentedStorage.hpp.
Referenced by hif::AugCCS< CcsType >::interchange_rows().
ROW_MAJOR
template<class CcsType > constexpr bool hif::AugCCS< CcsType >::ROW_MAJOR = false static
row major flag
Definition at line 777 of file AugmentedStorage.hpp.
The documentation for this class was generated from the following file:
AugmentedStorage.hpp