HIFIR: hif::Crout Class Reference
hif::Crout Class Reference
Algorithms » Crout Update
Crout update in deferred fashionThe idea of this class is to implement Crout kernels that wrap around a common factor—step. In this case, the class Crout is as simple (in terms of data size) as an integer. It also supports implicitly casting to integer as well as increment operations (both suffix and prefix versions). The whole disign can be demonstrate by the following C++ pseudocode:
#include <Crout.hpp>
Public Types
using size_type = std::size_t
size type
Public Member Functions
Crout ()
default constructor
Crout (const Crout &)=default
Crout & operator= (const Crout &)=default
Crout & operator= (const size_type step)
assign to a step
const Crout & operator++ ()
increment Crout step
Crout operator++ (int)
increment Crout step, suffix
operator size_type () const
implicitly casting to size_type
size_type defers () const
get the current defers
size_type deferred_step () const
get the deferred step
void increment_defer_counter ()
increment the defer counter
template<class ArrayType >
void compress_array (ArrayType &v) const
compress an array without deferrals (gaps)
template<class ArrayIn , class ArrayOut >
void assign_gap_array (const ArrayIn &r, ArrayOut &l) const
compress an array and assign the no-gapped value to another one
template<class ScaleArray , class CrsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class CcsType , class SpVecType >
void compute_ut (const ScaleArray &s, const CrsType &crs_A, const ScaleArray &t, const size_type pk, const PermType &q, const CcsType &L, const IndPtrArray &L_start, const ListArray &L_list, const DiagType &d, const CrsType &U, const IndPtrArray &U_start, SpVecType &ut) const
dual of the compute_l, i.e. computing the row of U
template<bool IsSymm, class ScaleArray , class CcsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class CrsType , class SpVecType >
void compute_l (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p, const size_type qk, const size_type m, const CcsType &L, const IndPtrArray &L_start, const DiagType &d, const CrsType &U, const IndPtrArray &U_start, const ListArray &U_list, SpVecType &l) const
compute the column vector of L of current step
template<class ScaleArray , class CcsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class SpVecType >
void compute_symm (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p, const size_type qk, const size_type m, const CcsType &L, const IndPtrArray &L_start, const ListArray &L_list, const DiagType &d, SpVecType &l) const
compute the column vector of L of current step for
template<class CsType , class ListArray , class IndPtrArray >
void update_compress (CsType &T, ListArray &list, IndPtrArray &start) const
compress L and U and update their corresponding starting positions and linked lists
template<class CcsType , class IndPtrArray >
void symm_update_lstart (const CcsType &L, const typename CcsType::size_type m, IndPtrArray &L_start) const
another starting array needed in symmetric computation to get the offsets
template<class CsType , class ListArray , class IndPtrArray , class KappaArray >
bool update_kappa (const CsType &T, const ListArray &list, const IndPtrArray &start, KappaArray &kappa) const
estimate the inverse norm
template<bool IsSymm, class SpVecType , class DiagType >
std::enable_if<!IsSymm >::type update_diag (const SpVecType &l, const SpVecType &ut, const size_type m, DiagType &d) const
update the current diagonal entry
template<bool IsSymm, class SpVecType , class DiagType >
std::enable_if< IsSymm >::type update_diag (const SpVecType &, const SpVecType &ut, const size_type m, DiagType &d) const
update the current diagonal entry
template<class DiagType , class SpVecType >
bool scale_inv_diag (const DiagType &d, SpVecType &v) const
scale the computed row/column vectors by current diagonal inverse
template<class CsType , class IndPtrArray , class ListArray >
void defer_entry (const size_type to_idx, const IndPtrArray &start, CsType &T, ListArray &list) const
defer an secondary entry
template<class CcsType , class IndPtrArray , class ListArray >
void symm_defer_l (const size_type to_idx, const IndPtrArray &L_start, CcsType &L, ListArray &L_list, IndPtrArray &L_offsets) const
for symmetric leading block, we need to fix the offset positions while we do deferring
Protected Member Functions
template<class ScaleArray , class CrsType , class PermType , class SpVecType >
void _load_arow (const ScaleArray &s, const CrsType &crs_A, const ScaleArray &t, const size_type &pk, const PermType &q_inv, SpVecType &ut) const
load a row of A to ut buffer
template<bool IsSymm, class ScaleArray , class CcsType , class PermType , class SpVecType >
void _load_acol (const ScaleArray &s, const CcsType &ccs_A, const ScaleArray &t, const PermType &p_inv, const size_type &qk, const size_type m, SpVecType &l) const
load a column of A to l buffer
Protected Attributes
size_type _step
current step
size_type _defers
deferring counter
Detailed Description
Crout update in deferred fashion
The idea of this class is to implement Crout kernels that wrap around a common factor—step. In this case, the class Crout is as simple (in terms of data size) as an integer. It also supports implicitly casting to integer as well as increment operations (both suffix and prefix versions). The whole disign can be demonstrate by the following C++ pseudocode:
for (Crout crout; crout < m; ++crout) {
  crout.do_work1(...);
  crout.do_work2(...);
  ...
}
Definition at line 59 of file Crout.hpp.
Member Typedef Documentation
size_type
using hif::Crout::size_type = std::size_t
size type
Definition at line 61 of file Crout.hpp.
Constructor & Destructor Documentation
Crout() [1/2]
hif::Crout::Crout () inline
default constructor
Definition at line 64 of file Crout.hpp.
References _defers, and _step.
Crout() [2/2]
hif::Crout::Crout (const Crout &) default
Referenced by operator++().
Member Function Documentation
_load_acol()
template<bool IsSymm, class ScaleArray , class CcsType , class PermType , class SpVecType > void hif::Crout::_load_acol (const ScaleArray & s, const CcsType & ccs_A, const ScaleArray & t, const PermType & p_inv, const size_type & qk, const size_type m, SpVecType & l) const inline protected
load a column of A to l buffer
Template Parameters
IsSymm if true, then only load the offset
ScaleArray scaling from left/right-hand sides, see Array
CcsType ccs matrix of input A, see CCS
PermType permutation vector type, see BiPermMatrix
SpVecType sparse vector type, see SparseVector
Parameters
[in] s row scaling vector
[in] ccs_A input matrix in CCS scheme
[in] t column scaling vector
[in] p_inv row permutation matrix
[in] qk permuted column index
[in] m leading size
[out] l output sparse vector of column vector for A
See also
_load_arow
Definition at line 803 of file Crout.hpp.
References _step, and deferred_step().
_load_arow()
template<class ScaleArray , class CrsType , class PermType , class SpVecType > void hif::Crout::_load_arow (const ScaleArray & s, const CrsType & crs_A, const ScaleArray & t, const size_type & pk, const PermType & q_inv, SpVecType & ut) const inline protected
load a row of A to ut buffer
Template Parameters
ScaleArray scaling from left/right-hand sides, see Array
CrsType crs matrix of input A, see CRS
PermType permutation vector type, see BiPermMatrix
SpVecType sparse vector type, see SparseVector
Parameters
[in] s row scaling vector
[in] crs_A input matrix in CRS scheme
[in] t column scaling vector
[in] pk row permuted index
[in] q_inv column inverse permutation matrix
[out] ut output sparse vector of row vector for A
See also
_load_acol
Definition at line 761 of file Crout.hpp.
References _step, and deferred_step().
assign_gap_array()
template<class ArrayIn , class ArrayOut > void hif::Crout::assign_gap_array (const ArrayIn & r, ArrayOut & l) const inline
compress an array and assign the no-gapped value to another one
Template Parameters
ArrayIn input array type
ArrayOut output array type
Parameters
[in] r rhs array
[in] l lhs array
Note
l[k]=r[k+d]
Definition at line 117 of file Crout.hpp.
References _step, and deferred_step().
compress_array()
template<class ArrayType > void hif::Crout::compress_array (ArrayType & v) const inline
compress an array without deferrals (gaps)
Template Parameters
ArrayType in and out array type
Parameters
[in,out] v v[k]=v[k+d]
Definition at line 106 of file Crout.hpp.
References _step, and deferred_step().
compute_l()
template<bool IsSymm, class ScaleArray , class CcsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class CrsType , class SpVecType > void hif::Crout::compute_l (const ScaleArray & s, const CcsType & ccs_A, const ScaleArray & t, const PermType & p, const size_type qk, const size_type m, const CcsType & L, const IndPtrArray & L_start, const DiagType & d, const CrsType & U, const IndPtrArray & U_start, const ListArray & U_list, SpVecType & l) const inline
compute the column vector of L of current step
Template Parameters
IsSymm if true, then a symmetric leading block is assumed
ScaleArray row/column scaling diagonal matrix type, see Array
CcsType ccs format, see CCS
PermType permutation matrix type, see Array
ListArray "linked-list" array type, see Array
IndPtrArray index pointer array type, see Array
DiagType array used for storing diagonal array, see Array
CrsType crs format, see CRS
SpVecType sparse vector for storing l, see SparseVector
Parameters
[in] s row scaling matrix from preprocessing
[in] ccs_A input matrix in ccs scheme
[in] t column scaling matrix from preprocessing
[in] p row inverse permutation matrix (deferred)
[in] qk permutated column index
[in] m leading block size
[in] L lower part of decomposition
[in] L_start "linked-list" array storing the starting locations of L
[in] d diagonal entries
[in] U augmented U matrix
[in] U_start starting positions of U
[in] U_list linked list of row indices of current step in U
[out] l column vector of L at current _step
See also
compute_ut
This routine computes the current column vector of (w/o diagonal scaling). Mathematically, this routine is to compute:
It's worth noting that, conceptally, the formula above is nothing but a matrix vector operation. However, standard implementation won't give good performance (especially with consideration of cache performance), this is because is stored in column major whereas row major for . Therefore, the actual implementation is in the fashion that loops through in column major while keeping as much static as possible.
Regarding the complexity cost, it takes to first load the column of A to , and takes , where for computing the matrix vector operation.
Definition at line 271 of file Crout.hpp.
References _defers, _step, and deferred_step().
compute_symm()
template<class ScaleArray , class CcsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class SpVecType > void hif::Crout::compute_symm (const ScaleArray & s, const CcsType & ccs_A, const ScaleArray & t, const PermType & p, const size_type qk, const size_type m, const CcsType & L, const IndPtrArray & L_start, const ListArray & L_list, const DiagType & d, SpVecType & l) const inline
compute the column vector of L of current step for
Template Parameters
ScaleArray row/column scaling diagonal matrix type, see Array
CcsType ccs format, see CCS
PermType permutation matrix type, see Array
ListArray "linked-list" array type, see Array
IndPtrArray index pointer array type, see Array
DiagType array used for storing diagonal array, see Array
SpVecType sparse vector for storing l, see SparseVector
Parameters
[in] s row scaling matrix from preprocessing
[in] ccs_A input matrix in ccs scheme
[in] t column scaling matrix from preprocessing, should be s
[in] p row inverse permutation matrix (deferred)
[in] qk permutated column index
[in] m leading block size
[in] L lower part of decomposition
[in] L_start position array storing the starting locations of L
[in] L_list linked list of row indices of current step in L
[in] d diagonal entries
[out] l column vector of L at current _step
See also
compute_ut
This routine computes the current column vector of (w/o diagonal scaling). Mathematically, this routine is to compute:
Definition at line 359 of file Crout.hpp.
References _step, and deferred_step().
compute_ut()
template<class ScaleArray , class CrsType , class PermType , class ListArray , class IndPtrArray , class DiagType , class CcsType , class SpVecType > void hif::Crout::compute_ut (const ScaleArray & s, const CrsType & crs_A, const ScaleArray & t, const size_type pk, const PermType & q, const CcsType & L, const IndPtrArray & L_start, const ListArray & L_list, const DiagType & d, const CrsType & U, const IndPtrArray & U_start, SpVecType & ut) const inline
dual of the compute_l, i.e. computing the row of U
Template Parameters
ScaleArray row scaling diagonal matrix type, see Array
CrsType crs format, see CRS
PermType permutation matrix type, see Array
ListArray "linked-list" array type, see Array
IndPtrArray index pointer array, see Array
DiagType diagonal matrix type, see Array
CcsType ccs format, see CCS
SpVecType work array for current row vector, see SparseVector
Parameters
[in] s row scaling matrix from preprocessing
[in] crs_A input matrix in crs scheme
[in] t column scaling matrix from preprocessing
[in] pk permutated row index
[in] q column inverse permutation (deferred)
[in] L lower part
[in] L_start starting positions for current step
[in] L_list linked list of column indices for current step
[in] d diagonal vector
[in] U upper part
[in] U_start leading row positions of current _step
[out] ut current row vector of U
See also
compute_l
This routine computes the current row vector of (w/o diagonal scaling). Mathematically, this routine is to compute:
It's worth noting that, conceptally, the formula above is nothing but a vector matrix operation. However, standard implementation won't give good performance (especially with consideration of cache performance), this is because is stored in column major whereas row major for . Therefore, the actual implementation is in the fashion that loops through in row major while keeping as much static as possible.
Regarding the complexity cost, it takes to first load the row of A to , and takes , where for computing the vector matrix operation.
Definition at line 169 of file Crout.hpp.
References _step, and deferred_step().
deferred_step()
size_type hif::Crout::deferred_step () const inline
get the deferred step
Definition at line 97 of file Crout.hpp.
References _defers, and _step.
Referenced by _load_acol(), _load_arow(), hif::PivotCrout::apply_thres_pivot(), assign_gap_array(), compress_array(), hif::PivotCrout::compute_dk(), compute_l(), hif::PivotCrout::compute_l(), compute_symm(), compute_ut(), hif::PivotCrout::compute_ut(), hif::PivotCrout::defer_entry(), defer_entry(), hif::PivotCrout::interchange(), hif::level_factorize(), hif::pivot_level_factorize(), symm_defer_l(), hif::symm_level_factorize(), hif::PivotCrout::update_compress(), update_compress(), hif::PivotCrout::update_kappa(), and update_kappa().
defers()
size_type hif::Crout::defers () const inline
get the current defers
Definition at line 94 of file Crout.hpp.
References _defers.
Referenced by hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
increment_defer_counter()
void hif::Crout::increment_defer_counter () inline
increment the defer counter
Definition at line 100 of file Crout.hpp.
References _defers.
Referenced by hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
operator size_type()
hif::Crout::operator size_type () const inline
implicitly casting to size_type
Definition at line 91 of file Crout.hpp.
References _step.
operator++() [1/2]
const Crout& hif::Crout::operator++ () inline
increment Crout step
Definition at line 78 of file Crout.hpp.
References _step.
Referenced by hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
operator++() [2/2]
Crout hif::Crout::operator++ (int) inline
increment Crout step, suffix
Definition at line 84 of file Crout.hpp.
References _step, and Crout().
operator=() [1/2]
Crout& hif::Crout::operator= (const Crout &) default
operator=() [2/2]
Crout& hif::Crout::operator= (const size_type step) inline
assign to a step
Parameters
[in] step step number
Definition at line 72 of file Crout.hpp.
References _step.
scale_inv_diag()
template<class DiagType , class SpVecType > bool hif::Crout::scale_inv_diag (const DiagType & d, SpVecType & v) const inline
scale the computed row/column vectors by current diagonal inverse
Template Parameters
DiagType diagonal matrix type, see Array
SpVecType sparse vector for storing l/U, see SparseVector
Parameters
[in] d diagonal vector
[in,out] v vector to be scaled
Returns
The returned boolean flag indices a singularity occurs if true
This routine computes ; firstly, singularity is checked to ensure the validation of computation. Then, we test if it's safe to invert so that we can use multiplication instead of division.
Regarding complexity, this routine takes
Definition at line 647 of file Crout.hpp.
References _step.
symm_update_lstart()
template<class CcsType , class IndPtrArray > void hif::Crout::symm_update_lstart (const CcsType & L, const typename CcsType::size_type m, IndPtrArray & L_start) const inline
another starting array needed in symmetric computation to get the offsets
Template Parameters
CcsType ccs type for L, see CCS
IndPtrArray index pointer array, see Array
Parameters
[in] L lower factor
[in] m leading block size
[out] L_start offset starting positions
Definition at line 467 of file Crout.hpp.
References _step.
update_compress()
template<class CsType , class ListArray , class IndPtrArray > void hif::Crout::update_compress (CsType & T, ListArray & list, IndPtrArray & start) const inline
compress L and U and update their corresponding starting positions and linked lists
Template Parameters
CsType either CRS or CCS
ListArray "linked-list" array type, see Array
IndPtrArray index pointer array, see Array
Parameters
[in,out] T strictly lower (L) or upper (U) matrices
[in,out] list linked list of current step with primary indices
[in,out] start local positions
The overall idea involves the following steps: (1) loop through the current secondary axis to get the primary indices in list, then (2) from these primary indices combining with starting positions, start, to get the index and value arrays position, (3) next step is to compress the index wrt to the current overall deferals, finally (4) advance the starting position and update the linked list accordingly.
Clearly, all these steps must be done concurrently with in a single loop.
Definition at line 428 of file Crout.hpp.
References _defers, _step, and deferred_step().
update_diag() [1/2]
template<bool IsSymm, class SpVecType , class DiagType > std::enable_if<!IsSymm>::type hif::Crout::update_diag (const SpVecType & l, const SpVecType & ut, const size_type m, DiagType & d) const inline
update the current diagonal entry
Template Parameters
IsSymm if true, then assuming we have a leading block
SpVecType sparse vector for storing l/U, see SparseVector
DiagType diagonal vector array type, see Array
Parameters
[in] l newly computed column vector of L
[in] ut newly computed row vector of U
[in] m leading block size (not necessary for symmetric)
[in,out] d diagonal vector
This routine is SFINAE-able by IsSymm and it's for asymmetric cases. This routine is to compute the last step in Crout updates, i.e. updating the diagonal entries:
The complexity is bounded by:
Definition at line 543 of file Crout.hpp.
References _step.
update_diag() [2/2]
template<bool IsSymm, class SpVecType , class DiagType > std::enable_if<IsSymm>::type hif::Crout::update_diag (const SpVecType & , const SpVecType & ut, const size_type m, DiagType & d) const inline
update the current diagonal entry
Template Parameters
IsSymm if true, then assuming we have a leading block
SpVecType sparse vector for storing l, see SparseVector
DiagType diagonal vector array type, see Array
Parameters
[in] ut newly computed row vector of U
[in] m leading block size (not necessary for symmetric)
[in,out] d diagonal vector
This routine is SFINAE-able by IsSymm and it's for symmetric cases. This routine is to compute the last step in Crout updates, i.e. updating the diagonal entries:
The complexity is bounded by:
Definition at line 614 of file Crout.hpp.
References _step.
update_kappa()
template<class CsType , class ListArray , class IndPtrArray , class KappaArray > bool hif::Crout::update_kappa (const CsType & T, const ListArray & list, const IndPtrArray & start, KappaArray & kappa) const inline
estimate the inverse norm
Template Parameters
CsType either CRS (U) or CCS (L)
ListArray "linked-list" array type, see Array
IndPtrArray index pointer array
KappaArray array type for storing inverse norms, see Array
Parameters
[in] T lower or upper factors
[in] list linked list of primary indices of current step
[in] start starting positions in index and value arrays
[in,out] kappa inverse norm solutions
Definition at line 486 of file Crout.hpp.
References _step, and deferred_step().
Member Data Documentation
_defers
size_type hif::Crout::_defers protected
deferring counter
Definition at line 833 of file Crout.hpp.
Referenced by hif::PivotCrout::apply_thres_pivot(), compute_l(), Crout(), deferred_step(), defers(), increment_defer_counter(), hif::PivotCrout::update_compress(), and update_compress().
_step
size_type hif::Crout::_step protected
current step
Definition at line 832 of file Crout.hpp.
Referenced by _load_acol(), _load_arow(), assign_gap_array(), compress_array(), hif::PivotCrout::compute_dk(), compute_l(), hif::PivotCrout::compute_l(), compute_symm(), compute_ut(), hif::PivotCrout::compute_ut(), Crout(), defer_entry(), deferred_step(), operator size_type(), operator++(), operator=(), scale_inv_diag(), symm_defer_l(), symm_update_lstart(), hif::PivotCrout::update_compress(), update_compress(), update_diag(), hif::PivotCrout::update_kappa(), and update_kappa().
The documentation for this class was generated from the following file:
Crout.hpp