HIFIR: hif::AugCRS< CrsType > Class Template Reference
hif::AugCRS< CrsType > Class Template Reference
Data Structures
Augmented CRS data structure.
#include <AugmentedStorage.hpp>
Public Types
typedef AugCRS this_type
aug crs type
typedef CrsType crs_type
crs
typedef crs_type::other_type ccs_type
ccs
typedef crs_type::size_type size_type
size
typedef _base::iarray_type iarray_type
index array
typedef iarray_type::value_type index_type
index type
typedef _base::indptr_type indptr_type
index_pointer
typedef _base::iparray_type iparray_type
indptr array
typedef crs_type::value_type value_type
value
Public Types inherited from hif::internal::AugmentedCore< CrsType::index_type, CrsType::indptr_type >
typedef CrsType::index_type index_type
index
typedef Array< index_type > iarray_type
container
typedef CrsType::indptr_type indptr_type
index_pointer type
typedef Array< indptr_type > iparray_type
indptr array
typedef iarray_type::size_type size_type
size
typedef AugmentedCore this_type
this
typedef iarray_type::iterator iterator
iterator type
Public Member Functions
AugCRS ()=default
default constructor
AugCRS (const size_type nrows, const size_type ncols, const size_type nnz=0u, bool reserve=true)
constructor for general matrix
AugCRS (const this_type &other, bool clone=false)
constructor to either clone or shallow copy another AugCRS
AugCRS (this_type &&)=default
this_type & operator= (const this_type &)=default
this_type & operator= (this_type &&)=default
void build_aug (const crs_type &crs, bool clone=false)
build augmented data structure based on mature CRS matrices
void build_aug (crs_type &&crs)
build augmented data structure based on mature CRS
void build_aug (const ccs_type &ccs)
build augmented data structured based on mature CCS matrices
indptr_type start_col_id (const size_type col) const
given column index, get the starting column handle
indptr_type start_aug_id (const size_type col) const
unified interface to get starting augmented ID
indptr_type next_col_id (const size_type col_id) const
given a column handle, get its next location
indptr_type next_aug_id (const size_type aug_id) const
unified interface for advancing augmented ID
index_type row_idx (const size_type col_id) const
given a column handle/ID, get its corresponding row index
index_type primary_idx (const size_type aug_id) const
unified interface for getting primary index
void reserve (const size_type nnz)
reserve space for nnz arrays
value_type val_from_col_id (const size_type col_id) const
get value with col id
value_type val_from_aug_id (const size_type aug_id) const
unified interface for getting value from augmented ID
size_type nnz_in_col (const size_type col) const
get the total number of nonzeros columnwise
size_type nnz_in_secondary (const size_type col) const
unified interface for getting in secondary (col) direction
void interchange_cols (const size_type i, const size_type k)
interchange two columns
void interchange_entries (const size_type i, const size_type k)
unified interface for interchanging entries
void defer_col (const size_type from, const size_type to)
defer a column to the end
void defer_entry (const size_type from, const size_type to)
unified interface for deferring
iarray_type & row_ind ()
const iarray_type & row_ind () const
iparray_type & col_start ()
const iparray_type & col_start () const
iparray_type & col_end ()
const iparray_type & col_end () const
iparray_type & col_next ()
const iparray_type & col_next () const
iarray_type & col_counts ()
const iarray_type & col_counts () const
void begin_assemble_rows ()
begin to assemble rows
template<class Iter , class ValueArray >
void push_back_row (const size_type row, Iter first, Iter last, const ValueArray &v)
push back a row with column indices
template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 >
void push_back_row (const size_type row, Iter1 first1, Iter1 last1, const ValueArray1 &v1, Iter2 first2, Iter2 last2, const ValueArray2 &v2)
push back a row with two lists of column indices
Public Member Functions inherited from hif::internal::AugmentedCore< CrsType::index_type, CrsType::indptr_type >
AugmentedCore ()=default
default constructor
AugmentedCore (const size_type nlist, const size_type nnz=0, bool reserve=true)
constructor with number of lists
AugmentedCore (const this_type &other, bool clone=false)
shallow copy of clone
AugmentedCore (this_type &&)=default
this_type & operator= (const this_type &)=default
this_type & operator= (this_type &&)=default
indptr_type val_pos_idx (const size_type nid) const
given a node handle, query its value position (index)
iparray_type & val_pos ()
const iparray_type & val_pos () const
void reserve (const size_type nnz)
reserve spaces for nnz arrays
iparray_type & secondary_start ()
const iparray_type & secondary_start () const
iparray_type & secondary_end ()
const iparray_type & secondary_end () const
iarray_type & secondary_counts ()
const iarray_type & secondary_counts () const
Static Public Attributes
static constexpr bool ROW_MAJOR = true
crs flag
Private Types
typedef internal::AugmentedCore< typename CrsType::index_type, typename CrsType::indptr_type > _base
Static Private Attributes
static constexpr indptr_type _NIL = _base::_NIL
Additional Inherited Members
Static Public Member Functions inherited from hif::internal::AugmentedCore< CrsType::index_type, CrsType::indptr_type >
static constexpr bool is_nil (const indptr_type i)
check if a given node handle is NIL or not
Protected Member Functions inherited from hif::internal::AugmentedCore< CrsType::index_type, CrsType::indptr_type >
void _begin_assemble_nodes (const size_type nlist)
begin assemble nodes
void _push_back_nodes (const size_type entry, Iter first, Iter last)
update linked lists given new nodes from back
indptr_type _start_node (const size_type lid) const
get starting node ID
indptr_type _next_node (const size_type nid) const
get the next node ID
index_type _node_ind (const size_type nid) const
get node item ({col-,row-}index in aug-{ccx,crs}, correspondingly)
void _swap_val_pos_exp (const size_type p1, const size_type p2)
given two existing indices, swap them explicitly
void _rotate_val_pos_left (const size_type n, const size_type src)
rotate value positions toward left
void _rotate_val_pos_right (const size_type n, const size_type src)
rotate value positions toward right
void _interchange_ik_head_tail (const size_type i, const size_type k)
interchange the head and tail nodes given list i and k
void _build_aug (const size_type nlist, const iparray_type &ind_start, const iarray_type &indices)
build augmented cores based on compressed storages
size_type _nodes_in_list (const size_type i) const
query total number of in a certain list
Protected Attributes inherited from hif::internal::AugmentedCore< CrsType::index_type, CrsType::indptr_type >
iarray_type _node_inds
indices (values) of each node
iparray_type _node_start
head nodes
iparray_type _node_next
next nodes
iparray_type _node_end
ending positions
iparray_type _val_pos
value positions
iparray_type _val_pos_inv
value position inverse, i.e. inv(_val_pos)
iarray_type _node_counts
number of nodes per list
Static Protected Attributes inherited from hif::internal::AugmentedCore< CrsType::index_type, CrsType::indptr_type >
static constexpr indptr_type _NIL
Detailed Description
template<class CrsType>
class hif::AugCRS< CrsType >
Augmented CRS data structure.
Template Parameters
CrsType A CRS type instantiation
See also
AugCCS
Note
This class inherits from CRS
Definition at line 373 of file AugmentedStorage.hpp.
Member Typedef Documentation
_base
template<class CrsType > typedef internal::AugmentedCore<typename CrsType::index_type, typename CrsType::indptr_type> hif::AugCRS< CrsType >::_base private
Definition at line 378 of file AugmentedStorage.hpp.
ccs_type
template<class CrsType > typedef crs_type::other_type hif::AugCRS< CrsType >::ccs_type
ccs
Definition at line 383 of file AugmentedStorage.hpp.
crs_type
template<class CrsType > typedef CrsType hif::AugCRS< CrsType >::crs_type
crs
Definition at line 382 of file AugmentedStorage.hpp.
iarray_type
template<class CrsType > typedef _base::iarray_type hif::AugCRS< CrsType >::iarray_type
index array
Definition at line 385 of file AugmentedStorage.hpp.
index_type
template<class CrsType > typedef iarray_type::value_type hif::AugCRS< CrsType >::index_type
index type
Definition at line 386 of file AugmentedStorage.hpp.
indptr_type
template<class CrsType > typedef _base::indptr_type hif::AugCRS< CrsType >::indptr_type
index_pointer
Definition at line 387 of file AugmentedStorage.hpp.
iparray_type
template<class CrsType > typedef _base::iparray_type hif::AugCRS< CrsType >::iparray_type
indptr array
Definition at line 388 of file AugmentedStorage.hpp.
size_type
template<class CrsType > typedef crs_type::size_type hif::AugCRS< CrsType >::size_type
size
Definition at line 384 of file AugmentedStorage.hpp.
this_type
template<class CrsType > typedef AugCRS hif::AugCRS< CrsType >::this_type
aug crs type
Definition at line 381 of file AugmentedStorage.hpp.
value_type
template<class CrsType > typedef crs_type::value_type hif::AugCRS< CrsType >::value_type
value
Definition at line 389 of file AugmentedStorage.hpp.
Constructor & Destructor Documentation
AugCRS() [1/4]
template<class CrsType > hif::AugCRS< CrsType >::AugCRS () default
default constructor
AugCRS() [2/4]
template<class CrsType > hif::AugCRS< CrsType >::AugCRS (const size_type nrows, const size_type ncols, const size_type nnz = 0u, bool reserve = true) inline
constructor for general matrix
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] nnz ignored if zero (default)
[in] reserve if true (default), reserve spaces
Definition at line 404 of file AugmentedStorage.hpp.
AugCRS() [3/4]
template<class CrsType > hif::AugCRS< CrsType >::AugCRS (const this_type & other, bool clone = false) inline
constructor to either clone or shallow copy another AugCRS
Parameters
[in] other another augmented CRS
[in] clone if false (default), then do shallow copy
Definition at line 411 of file AugmentedStorage.hpp.
AugCRS() [4/4]
template<class CrsType > hif::AugCRS< CrsType >::AugCRS (this_type &&) default
Member Function Documentation
begin_assemble_rows()
template<class CrsType > void hif::AugCRS< CrsType >::begin_assemble_rows () inline
begin to assemble rows
Definition at line 712 of file AugmentedStorage.hpp.
build_aug() [1/3]
template<class CrsType > void hif::AugCRS< CrsType >::build_aug (const crs_type & crs, bool clone = false) inline
build augmented data structure based on mature CRS matrices
Parameters
[in] crs mature CRS system
[in] clone if false (default), crs will be shallow copied
Warning
Advanced usage routine!
Definition at line 423 of file AugmentedStorage.hpp.
References hif::DATA_UNDEF, and hif::error().
build_aug() [2/3]
template<class CrsType > void hif::AugCRS< CrsType >::build_aug (crs_type && crs) inline
build augmented data structure based on mature CRS
Parameters
[in] crs temp CRS system
Definition at line 436 of file AugmentedStorage.hpp.
References hif::DATA_UNDEF, and hif::error().
build_aug() [3/3]
template<class CrsType > void hif::AugCRS< CrsType >::build_aug (const ccs_type & ccs) inline
build augmented data structured based on mature CCS matrices
Parameters
[in] ccs mature CCS system
Warning
Advanced usage routine
Definition at line 449 of file AugmentedStorage.hpp.
References hif::DATA_UNDEF, and hif::error().
col_counts() [1/2]
template<class CrsType > iarray_type& hif::AugCRS< CrsType >::col_counts () inline
Definition at line 708 of file AugmentedStorage.hpp.
col_counts() [2/2]
template<class CrsType > const iarray_type& hif::AugCRS< CrsType >::col_counts () const inline
Definition at line 709 of file AugmentedStorage.hpp.
col_end() [1/2]
template<class CrsType > iparray_type& hif::AugCRS< CrsType >::col_end () inline
Definition at line 704 of file AugmentedStorage.hpp.
col_end() [2/2]
template<class CrsType > const iparray_type& hif::AugCRS< CrsType >::col_end () const inline
Definition at line 705 of file AugmentedStorage.hpp.
col_next() [1/2]
template<class CrsType > iparray_type& hif::AugCRS< CrsType >::col_next () inline
Definition at line 706 of file AugmentedStorage.hpp.
col_next() [2/2]
template<class CrsType > const iparray_type& hif::AugCRS< CrsType >::col_next () const inline
Definition at line 707 of file AugmentedStorage.hpp.
col_start() [1/2]
template<class CrsType > iparray_type& hif::AugCRS< CrsType >::col_start () inline
Definition at line 702 of file AugmentedStorage.hpp.
col_start() [2/2]
template<class CrsType > const iparray_type& hif::AugCRS< CrsType >::col_start () const inline
Definition at line 703 of file AugmentedStorage.hpp.
defer_col()
template<class CrsType > void hif::AugCRS< CrsType >::defer_col (const size_type from, const size_type to) inline
defer a column to the end
Parameters
[in] from which column to defer
[in] to the current pass-of-end column index
Warning
the parameter to must be current pass-of-last column
Definition at line 668 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::next_col_id(), hif::AugCRS< CrsType >::row_idx(), and hif::AugCRS< CrsType >::start_col_id().
Referenced by hif::AugCRS< CrsType >::defer_entry().
defer_entry()
template<class CrsType > void hif::AugCRS< CrsType >::defer_entry (const size_type from, const size_type to) inline
unified interface for deferring
See also
defer_col
Definition at line 695 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::defer_col().
interchange_cols()
template<class CrsType > void hif::AugCRS< CrsType >::interchange_cols (const size_type i, const size_type k) inline
interchange two columns
Note
This is the core operation for augmented data structure
Parameters
[in] i i-th column
[in] k k-th column
Mathematically, after calling this routine, the i-th and k-th columns will be interchanged. The total complexity of this routine is linear with respect to the total number of nonzeros in columns i and k.
Definition at line 541 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::_NIL, hif::AugCRS< CrsType >::next_col_id(), hif::AugCRS< CrsType >::row_idx(), and hif::AugCRS< CrsType >::start_col_id().
Referenced by hif::AugCRS< CrsType >::interchange_entries().
interchange_entries()
template<class CrsType > void hif::AugCRS< CrsType >::interchange_entries (const size_type i, const size_type k) inline
unified interface for interchanging entries
See also
interchange_cols
Definition at line 660 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::interchange_cols().
next_aug_id()
template<class CrsType > indptr_type hif::AugCRS< CrsType >::next_aug_id (const size_type aug_id) const inline
unified interface for advancing augmented ID
Parameters
[in] aug_id augmented ID
Definition at line 479 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::next_col_id().
next_col_id()
template<class CrsType > indptr_type hif::AugCRS< CrsType >::next_col_id (const size_type col_id) const inline
given a column handle, get its next location
Parameters
[in] col_id column handle/ID
Definition at line 473 of file AugmentedStorage.hpp.
Referenced by hif::AugCRS< CrsType >::defer_col(), hif::AugCRS< CrsType >::interchange_cols(), and hif::AugCRS< CrsType >::next_aug_id().
nnz_in_col()
template<class CrsType > size_type hif::AugCRS< CrsType >::nnz_in_col (const size_type col) const inline
get the total number of nonzeros columnwise
Parameters
[in] col column index
Definition at line 523 of file AugmentedStorage.hpp.
Referenced by hif::AugCRS< CrsType >::nnz_in_secondary().
nnz_in_secondary()
template<class CrsType > size_type hif::AugCRS< CrsType >::nnz_in_secondary (const size_type col) const inline
unified interface for getting in secondary (col) direction
Parameters
[in] col column index
Definition at line 529 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::nnz_in_col().
operator=() [1/2]
template<class CrsType > this_type& hif::AugCRS< CrsType >::operator= (const this_type &) default
operator=() [2/2]
template<class CrsType > this_type& hif::AugCRS< CrsType >::operator= (this_type &&) default
primary_idx()
template<class CrsType > index_type hif::AugCRS< CrsType >::primary_idx (const size_type aug_id) const inline
unified interface for getting primary index
Definition at line 490 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::row_idx().
push_back_row() [1/2]
template<class CrsType > template<class Iter , class ValueArray > void hif::AugCRS< CrsType >::push_back_row (const size_type row, Iter first, Iter last, const ValueArray & v) inline
push back a row with column indices
Template Parameters
Iter iterator type
ValueArray dense value array
Parameters
[in] row current row index (C-based)
[in] first starting iterator
[in] last pass-of-end iterator
[in] v dense value array, the value can be queried from indices
Definition at line 725 of file AugmentedStorage.hpp.
push_back_row() [2/2]
template<class CrsType > template<class Iter1 , class ValueArray1 , class Iter2 , class ValueArray2 > void hif::AugCRS< CrsType >::push_back_row (const size_type row, Iter1 first1, Iter1 last1, const ValueArray1 & v1, Iter2 first2, Iter2 last2, const ValueArray2 & v2) inline
push back a row with two lists of column indices
Template Parameters
Iter1 iterator type
ValueArray1 dense value array
Iter2 iterator type
ValueArray2 dense value array
Parameters
[in] row current row index (c-based)
[in] first1 starting iterator of list 1
[in] last1 pass-of-end iterator of list 1
[in] v1 dense value array for list 1
[in] first2 starting iterator of list 2
[in] last2 pass-of-end iterator of list 2
[in] v2 dense value array for list 2
Definition at line 744 of file AugmentedStorage.hpp.
reserve()
template<class CrsType > void hif::AugCRS< CrsType >::reserve (const size_type nnz) inline
reserve space for nnz arrays
Parameters
[in] nnz total number of nonzeros
Definition at line 496 of file AugmentedStorage.hpp.
row_idx()
template<class CrsType > index_type hif::AugCRS< CrsType >::row_idx (const size_type col_id) const inline
given a column handle/ID, get its corresponding row index
Parameters
[in] col_id column handle/ID
Definition at line 485 of file AugmentedStorage.hpp.
Referenced by hif::AugCRS< CrsType >::defer_col(), hif::AugCRS< CrsType >::interchange_cols(), and hif::AugCRS< CrsType >::primary_idx().
row_ind() [1/2]
template<class CrsType > iarray_type& hif::AugCRS< CrsType >::row_ind () inline
Definition at line 700 of file AugmentedStorage.hpp.
row_ind() [2/2]
template<class CrsType > const iarray_type& hif::AugCRS< CrsType >::row_ind () const inline
Definition at line 701 of file AugmentedStorage.hpp.
start_aug_id()
template<class CrsType > indptr_type hif::AugCRS< CrsType >::start_aug_id (const size_type col) const inline
unified interface to get starting augmented ID
Definition at line 467 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::start_col_id().
start_col_id()
template<class CrsType > indptr_type hif::AugCRS< CrsType >::start_col_id (const size_type col) const inline
given column index, get the starting column handle
Parameters
[in] col column index
Returns
first column handle in the augmented data structure
Definition at line 462 of file AugmentedStorage.hpp.
Referenced by hif::AugCRS< CrsType >::defer_col(), hif::AugCRS< CrsType >::interchange_cols(), and hif::AugCRS< CrsType >::start_aug_id().
val_from_aug_id()
template<class CrsType > value_type hif::AugCRS< CrsType >::val_from_aug_id (const size_type aug_id) const inline
unified interface for getting value from augmented ID
Parameters
[in] aug_id augmented ID
Definition at line 517 of file AugmentedStorage.hpp.
References hif::AugCRS< CrsType >::val_from_col_id().
val_from_col_id()
template<class CrsType > value_type hif::AugCRS< CrsType >::val_from_col_id (const size_type col_id) const inline
get value with col id
Parameters
[in] col_id column handle/ID
Definition at line 510 of file AugmentedStorage.hpp.
Referenced by hif::AugCRS< CrsType >::val_from_aug_id().
Member Data Documentation
_NIL
template<class CrsType > constexpr indptr_type hif::AugCRS< CrsType >::_NIL = _base::_NIL static private
Definition at line 393 of file AugmentedStorage.hpp.
Referenced by hif::AugCRS< CrsType >::interchange_cols().
ROW_MAJOR
template<class CrsType > constexpr bool hif::AugCRS< CrsType >::ROW_MAJOR = true static
crs flag
Definition at line 390 of file AugmentedStorage.hpp.
The documentation for this class was generated from the following file:
AugmentedStorage.hpp