HIFIR: demo_utils.hpp File Reference
demo_utils.hpp File Reference
#include <cstdlib>
#include <fstream>
#include <iostream>
#include "hifir.hpp"
Classes
struct system_t
Typedefs
using matrix_t = hif::CRS< double, int >
using array_t = hif::Array< double >
Functions
system_t get_user_data (const char *A_file, const char *b_file)
system_t get_input_data (const char *A_file=nullptr, const char *b_file=nullptr)
double compute_error (const array_t &v1, const array_t &v2)
double compute_relres (const matrix_t &A, const array_t &b, const array_t &x)
std::pair< std::string, std::string > parse_input_files (int argc, char *argv[])
system_t parse_cmd4input (int argc, char *argv[])
Typedef Documentation
array_t
using array_t = hif::Array<double>
Definition at line 17 of file demo_utils.hpp.
matrix_t
using matrix_t = hif::CRS<double, int>
Examples:
demo_fgmres_sparsifier.cpp, and demo_sparsifier.cpp.
Definition at line 16 of file demo_utils.hpp.
Function Documentation
compute_error()
double compute_error (const array_t & v1, const array_t & v2) inline
Examples:
demo_multiply.cpp.
Definition at line 53 of file demo_utils.hpp.
References hif::Array< T >::Array(), hif::norm2(), hif::Array< T >::operator[](), and hif::Array< T >::size().
compute_relres()
double compute_relres (const matrix_t & A, const array_t & b, const array_t & x) inline
Examples:
demo_fgmres.cpp, demo_fgmres_sparsifier.cpp, demo_gmreshif.cpp, demo_hifir.cpp, and demo_sparsifier.cpp.
Definition at line 61 of file demo_utils.hpp.
References hif::Array< T >::Array(), hif::norm2(), hif::Array< T >::operator[](), and hif::Array< T >::size().
get_input_data()
system_t get_input_data (const char * A_file = nullptr, const char * b_file = nullptr) inline
Examples:
demo_fgmres.cpp, demo_fgmres_sparsifier.cpp, demo_gmreshif.cpp, and demo_sparsifier.cpp.
Definition at line 37 of file demo_utils.hpp.
References system_t::A, system_t::b, hif::Array< T >::from_mm(), hif::CRS< ValueType, IndexType, IndPtrType >::from_mm(), and get_user_data().
Referenced by parse_cmd4input().
get_user_data()
system_t get_user_data (const char * A_file, const char * b_file) inline
Definition at line 25 of file demo_utils.hpp.
References system_t::A, hif::Array< T >::Array(), system_t::b, hif::Array< T >::begin(), hif::Array< T >::end(), hif::Array< T >::from_mm(), hif::CRS< ValueType, IndexType, IndPtrType >::from_mm(), hif::CRS< ValueType, IndexType, IndPtrType >::ncols(), and hif::CRS< ValueType, IndexType, IndPtrType >::nrows().
Referenced by get_input_data().
parse_cmd4input()
system_t parse_cmd4input (int argc, char * argv[]) inline
Examples:
demo_hifir.cpp, demo_mixedprecision.cpp, demo_multiply.cpp, demo_params.cpp, demo_simple.cpp, demo_trans.cpp, and demo_verbose.cpp.
Definition at line 109 of file demo_utils.hpp.
References get_input_data(), and parse_input_files().
parse_input_files()
std::pair<std::string, std::string> parse_input_files (int argc, char * argv[]) inline
Definition at line 70 of file demo_utils.hpp.
Referenced by parse_cmd4input().