HIFIR: Double-Precision Routines in LIBHIFIR
Double-Precision Routines in LIBHIFIR
LIBHIFIR C Interfaces
Typedefs
typedef struct LhfdMatrix * LhfdMatrixHdl
Pointer to double precision sparse matrix in libhifir.
typedef struct LhfdHif * LhfdHifHdl
Pointer to double precision HIF structure in libhifir.
Functions
LhfdMatrixHdl lhfdCreateMatrix (const int is_rowmajor, const size_t n, const LhfIndPtr *indptr, const LhfInt *indices, const double *vals)
Create an instance of double-precision sparse matrix.
LhfStatus lhfdDestroyMatrix (LhfdMatrixHdl mat)
Destroy a double-precision matrix instance.
size_t lhfdGetMatrixSize (const LhfdMatrixHdl mat)
Get the matrix size.
size_t lhfdGetMatrixNnz (const LhfdMatrixHdl mat)
Get the matrix number of nonzeros.
LhfStatus lhfdReadSparse (const char *fname, LhfdMatrixHdl mat)
Read a sparse matrix.
LhfStatus lhfdReadVector (const char *fname, const size_t n, double *v)
Read a vector.
LhfStatus lhfdWrapMatrix (LhfdMatrixHdl mat, const size_t n, const LhfIndPtr *indptr, const LhfInt *indices, const double *vals)
Wrap external data into a double-precision sparse matrix.
LhfdHifHdl lhfdCreate (const LhfdMatrixHdl A, const LhfdMatrixHdl S, const double params[])
Create a double-precision HIF instance.
LhfStatus lhfdDestroy (LhfdHifHdl hif)
Destroy a double-precision HIF instance.
LhfStatus lhfdSetup (LhfdHifHdl hif, const LhfdMatrixHdl A, const LhfdMatrixHdl S, const double params[])
Setup a double-precision HIF instance.
LhfStatus lhfdUpdate (LhfdHifHdl hif, const LhfdMatrixHdl A)
Update the A matrix in HIF.
LhfStatus lhfdRefactorize (LhfdHifHdl hif, const LhfdMatrixHdl S, const double params[])
Refactorize a HIF preconditioner.
LhfStatus lhfdApply (const LhfdHifHdl hif, const LhfOperationType op, const double *b, const int nirs, const double *betas, const int rank, double *x, int *ir_status)
Apply a preconditioner with a certian operation mode.
LhfStatus lhfdSolve (const LhfdHifHdl hif, const double *b, double *x)
Triangular solve.
LhfStatus lhfdGetStats (const LhfdHifHdl hif, size_t stats[])
Get the statistics of a computed HIF instance.
size_t lhfdGetNnz (const LhfdHifHdl hif)
Get number of nonzeros of a HIF preconditioner.
size_t lhfdGetLevels (const LhfdHifHdl hif)
Get number of levels.
size_t lhfdGetSchurSize (const LhfdHifHdl hif)
Get the Schur complement size.
size_t lhfdGetSchurRank (const LhfdHifHdl hif)
Get the Schur complement rank.
Detailed Description
Typedef Documentation
LhfdHifHdl
LhfdHifHdl
Pointer to double precision HIF structure in libhifir.
Definition at line 207 of file libhifir.h.
LhfdMatrixHdl
LhfdMatrixHdl
Pointer to double precision sparse matrix in libhifir.
Definition at line 179 of file libhifir.h.
Function Documentation
lhfdApply()
LhfStatus lhfdApply (const LhfdHifHdl hif, const LhfOperationType op, const double * b, const int nirs, const double * betas, const int rank, double * x, int * ir_status)
Apply a preconditioner with a certian operation mode.
Parameters
[in] hif A HIF instance
[in] op Operation tag
[in] b The RHS vector
[in] nirs Number of iterative refinements
[in] betas Relative residual norm bounds for IR with op=solve
[in] rank Numerical rank
[out] x Computed solution vector
[out] ir_status (optional) If IR and betas is provided, then this records the number of actual IR (ir_status[0]) and the IR status (ir_status[1]).
This is the core function of HIF. A HIF instance can be applied in four different modes, namely triangular solve and its Hermitian/tranpose variant, as well as matrix-vector multiplication and its Hermitian/tranpose variant. For the triangular solve modes, nirs can be greater than one, which means iterative refinement is enabled. With IR enabled, if betas is provided, i.e., not NULL, then we will iterative until (1) res<=betas[0], (2) res>betas[1], or (3) it=nirs, and the actual iteratoin steps and return status are stored in ir_status if provided (i.e., not NULL). On the other side, if betas=NULL, then the a fixed amount of IR (nirs) are performed and ir_status is not accessed. Regarding rank, in general, it should use LHF_DEFAULT_RANK.
See also
lhfdSolve
Definition at line 453 of file libhifir.cpp.
References libhifir_impl::hifir(), LHF_DEFAULT_RANK, LHF_M, LHF_MH, LHF_MISMATCHED_SIZES, LHF_S, LHF_SH, LHF_SUCCESS, libhifir_impl::mmultiply(), hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows(), and libhifir_impl::solve().
lhfdCreate()
LhfdHifHdl lhfdCreate (const LhfdMatrixHdl A, const LhfdMatrixHdl S, const double params[])
Create a double-precision HIF instance.
Parameters
[in] A Input coefficient matrix (used in iterative refinement)
[in] S Sparsifier input
[in] params Control parameters, see lhfSetDefaultParams
This function create an instance of double-precision HIF (see hif::HIF) preconditioner. Note that both A and S can be NULL, which then will create an empty instance. If both operators are provided, then the preconditioner will be factorized based on S. If only A is provided, then HIF is computed on A. If only S is provided, then A is set to be S besides computing the factorization on it. In addition, if params is NULL, then the default parameters will be used.
See also
lhfdDestroy
Definition at line 389 of file libhifir.cpp.
References LHF_HIFIR_ERROR, lhfdDestroy(), and lhfdSetup().
lhfdCreateMatrix()
LhfdMatrixHdl lhfdCreateMatrix (const int is_rowmajor, const size_t n, const LhfIndPtr * indptr, const LhfInt * indices, const double * vals)
Create an instance of double-precision sparse matrix.
Parameters
[in] is_rowmajor If true, then we use CRS, otherwise CCS is assumed
[in] n Size of the squared matrix
[in] indptr Index pointer array
[in] indices Index list
[in] vals Numerical value array
Note
The last three entries can be NULL, which will create an empty instance of sparse matrix.
Definition at line 312 of file libhifir.cpp.
lhfdDestroy()
LhfStatus lhfdDestroy (LhfdHifHdl hif)
Destroy a double-precision HIF instance.
Parameters
[out] hif HIF preconditioner
See also
lhfdCreate
Definition at line 407 of file libhifir.cpp.
References LHF_SUCCESS.
Referenced by lhfdCreate().
lhfdDestroyMatrix()
LhfStatus lhfdDestroyMatrix (LhfdMatrixHdl mat)
Destroy a double-precision matrix instance.
Parameters
[in,out] mat Matrix instance
Definition at line 332 of file libhifir.cpp.
References LHF_SUCCESS.
lhfdGetLevels()
size_t lhfdGetLevels (const LhfdHifHdl hif)
Get number of levels.
See also
lhfdGetStats
Definition at line 505 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::levels().
lhfdGetMatrixNnz()
size_t lhfdGetMatrixNnz (const LhfdMatrixHdl mat)
Get the matrix number of nonzeros.
Definition at line 343 of file libhifir.cpp.
lhfdGetMatrixSize()
size_t lhfdGetMatrixSize (const LhfdMatrixHdl mat)
Get the matrix size.
Definition at line 338 of file libhifir.cpp.
lhfdGetNnz()
size_t lhfdGetNnz (const LhfdHifHdl hif)
Get number of nonzeros of a HIF preconditioner.
See also
lhfdGetStats
Definition at line 501 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nnz().
lhfdGetSchurRank()
size_t lhfdGetSchurRank (const LhfdHifHdl hif)
Get the Schur complement rank.
See also
lhfdGetStats
Definition at line 513 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::schur_rank().
lhfdGetSchurSize()
size_t lhfdGetSchurSize (const LhfdHifHdl hif)
Get the Schur complement size.
See also
lhfdGetStats
Definition at line 509 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::schur_size().
lhfdGetStats()
LhfStatus lhfdGetStats (const LhfdHifHdl hif, size_t stats[])
Get the statistics of a computed HIF instance.
Parameters
[in] hif A HIF instance
[out] stats A length-9 array stores certain useful information
Regarding the output stats:
stats[0]: Number of nonzeros of a preconditioner
stats[1]: Total deferals
stats[2]: Dynamic deferals (status[1]-status[2] are static deferals)
stats[3]: Total droppings
stats[4]: Droppings due to scalability-oriented strategy
stats[5]: Number of levels
stats[6]: Numerical rank of the whole preconditioner
stats[7]: The numerical rank of the final Schur complement
stats[8]: The size of the final Schur complement (status[7]<=status[8])
Definition at line 492 of file libhifir.cpp.
References libhifir_impl::get_factor_stats(), and LHF_SUCCESS.
lhfdReadSparse()
LhfStatus lhfdReadSparse (const char * fname, LhfdMatrixHdl mat)
Read a sparse matrix.
Parameters
[in] fname Filename of a matrix market file
[out] mat Output sparse matrix that stores the data in fname
See also
lhfQueryMmFile
Definition at line 364 of file libhifir.cpp.
References libhifir_impl::mm_read_sparse().
lhfdReadVector()
LhfStatus lhfdReadVector (const char * fname, const size_t n, double * v)
Read a vector.
Parameters
[in] fname Filename of a matrix market file
[in] n Vector size
[out] v Vector data output
See also
lhfQueryMmFile
Definition at line 369 of file libhifir.cpp.
References hif::Array< T >::cbegin(), hif::Array< T >::cend(), hif::Array< T >::from_mm(), LHF_MISMATCHED_SIZES, LHF_SUCCESS, hif::Array< T >::operator=(), and hif::Array< T >::size().
lhfdRefactorize()
LhfStatus lhfdRefactorize (LhfdHifHdl hif, const LhfdMatrixHdl S, const double params[])
Refactorize a HIF preconditioner.
Parameters
[out] hif A HIF instance
[in] S A new sparsifier
[in] params Control parameters
Note
This function will not update A inside hif
If params is NULL, then the default parameters will be used.
See also
lhfdUpdate
Definition at line 440 of file libhifir.cpp.
References libhifir_impl::factorize(), and LHF_SUCCESS.
lhfdSetup()
LhfStatus lhfdSetup (LhfdHifHdl hif, const LhfdMatrixHdl A, const LhfdMatrixHdl S, const double params[])
Setup a double-precision HIF instance.
Parameters
[out] hif A HIF instance
[in] A Input coefficient matrix (used in iterative refinement)
[in] S Sparsifier input
[in] params Control parameters, see lhfSetDefaultParams
This function serves similar to lhfdCreate, except that A and S cannot be both NULL. This function is to defer the factorization from construction of HIF preconditioners.
See also
lhfdCreate
Definition at line 416 of file libhifir.cpp.
References libhifir_impl::factorize(), and LHF_SUCCESS.
Referenced by lhfdCreate().
lhfdSolve()
LhfStatus lhfdSolve (const LhfdHifHdl hif, const double * b, double * x)
Triangular solve.
For the sake of convenience, we provide the following routine as it is the most commonly used interface. The following routine is equivalent to calling lhfdApply with op=LHF_S, nirs=1, and rank=LHF_DEFAULT_RANK.
See also
lhfdApply
Definition at line 481 of file libhifir.cpp.
References LHF_SUCCESS, and libhifir_impl::solve().
lhfdUpdate()
LhfStatus lhfdUpdate (LhfdHifHdl hif, const LhfdMatrixHdl A)
Update the A matrix in HIF.
Parameters
[out] hif A HIF instance
[in] A A new matrix
Note
This function will not call factorization on A.
See also
lhfdRefactorize
Definition at line 431 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::empty(), LHF_MISMATCHED_SIZES, LHF_SUCCESS, and hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows().
lhfdWrapMatrix()
LhfStatus lhfdWrapMatrix (LhfdMatrixHdl mat, const size_t n, const LhfIndPtr * indptr, const LhfInt * indices, const double * vals)
Wrap external data into a double-precision sparse matrix.
Parameters
[out] mat Matrix that holds the external data
[in] n Size the squared matrix
[in] indptr Index pointer array
[in] indices Index list
[in] vals Numerical value array
Definition at line 349 of file libhifir.cpp.
References LHF_NULL_OBJ, and LHF_SUCCESS.