HIFIR: Single-Precision Complex Routines in LIBHIFIR
Single-Precision Complex Routines in LIBHIFIR
LIBHIFIR C Interfaces
Typedefs
typedef struct LhfcMatrix * LhfcMatrixHdl
Pointer to single precision complex sparse matrix in libhifir.
typedef struct LhfcHif * LhfcHifHdl
Pointer to single precision complex HIF structure in libhifir.
Functions
LhfcMatrixHdl lhfcCreateMatrix (const int is_rowmajor, const size_t n, const LhfIndPtr *indptr, const LhfInt *indices, const float _Complex *vals)
Create an instance of single-precision complex sparse matrix.
LhfStatus lhfcDestroyMatrix (LhfcMatrixHdl mat)
Destroy a single-precision complex matrix instance.
size_t lhfcGetMatrixSize (const LhfcMatrixHdl mat)
Get the matrix size.
size_t lhfcGetMatrixNnz (const LhfcMatrixHdl mat)
Get the matrix number of nonzeros.
LhfStatus lhfcReadSparse (const char *fname, LhfcMatrixHdl mat)
Read a sparse matrix.
LhfStatus lhfcReadVector (const char *fname, const size_t n, float _Complex *v)
Read a vector.
LhfStatus lhfcWrapMatrix (LhfcMatrixHdl mat, const size_t n, const LhfIndPtr *indptr, const LhfInt *indices, const float _Complex *vals)
Wrap external data into a single-precision complex sparse matrix.
LhfcHifHdl lhfcCreate (const LhfcMatrixHdl A, const LhfcMatrixHdl S, const double params[])
Create a single-precision complex HIF instance.
LhfStatus lhfcDestroy (LhfcHifHdl hif)
Destroy a single-precision complex HIF instance.
LhfStatus lhfcSetup (LhfcHifHdl hif, const LhfcMatrixHdl A, const LhfcMatrixHdl S, const double params[])
Setup a single-precision complex HIF instance.
LhfStatus lhfcUpdate (LhfcHifHdl hif, const LhfcMatrixHdl A)
Update the A matrix in HIF.
LhfStatus lhfcRefactorize (LhfcHifHdl hif, const LhfcMatrixHdl S, const double params[])
Refactorize a HIF preconditioner.
LhfStatus lhfcApply (const LhfcHifHdl hif, const LhfOperationType op, const float _Complex *b, const int nirs, const double *betas, const int rank, float _Complex *x, int *ir_status)
Apply a preconditioner with a certian operation mode.
LhfStatus lhfcSolve (const LhfcHifHdl hif, const float _Complex *b, float _Complex *x)
Triangular solve.
LhfStatus lhfcGetStats (const LhfcHifHdl hif, size_t stats[])
Get the statistics of a computed HIF instance.
size_t lhfcGetNnz (const LhfcHifHdl hif)
Get number of nonzeros of a HIF preconditioner.
size_t lhfcGetLevels (const LhfcHifHdl hif)
Get number of levels.
size_t lhfcGetSchurSize (const LhfcHifHdl hif)
Get the Schur complement size.
size_t lhfcGetSchurRank (const LhfcHifHdl hif)
Get the Schur complement rank.
Detailed Description
Typedef Documentation
LhfcHifHdl
LhfcHifHdl
Pointer to single precision complex HIF structure in libhifir.
Definition at line 228 of file libhifir.h.
LhfcMatrixHdl
LhfcMatrixHdl
Pointer to single precision complex sparse matrix in libhifir.
Definition at line 200 of file libhifir.h.
Function Documentation
lhfcApply()
LhfStatus lhfcApply (const LhfcHifHdl hif, const LhfOperationType op, const float _Complex * b, const int nirs, const double * betas, const int rank, float _Complex * x, int * ir_status)
Apply a preconditioner with a certian operation mode.
Parameters
[in] hif A HIF instance
[in] op Operation tag
[in] b The RHS vector
[in] nirs Number of iterative refinements
[in] betas Relative residual norm bounds for IR with op=solve
[in] rank Numerical rank
[out] x Computed solution vector
[out] ir_status (optional) If IR and betas is provided, then this records the number of actual IR (ir_status[0]) and the IR status (ir_status[1]).
This is the core function of HIF. A HIF instance can be applied in four different modes, namely triangular solve and its Hermitian/tranpose variant, as well as matrix-vector multiplication and its Hermitian/tranpose variant. For the triangular solve modes, nirs can be greater than one, which means iterative refinement is enabled. With IR enabled, if betas is provided, i.e., not NULL, then we will iterative until (1) res<=betas[0], (2) res>betas[1], or (3) it=nirs, and the actual iteratoin steps and return status are stored in ir_status if provided (i.e., not NULL). On the other side, if betas=NULL, then the a fixed amount of IR (nirs) are performed and ir_status is not accessed. Regarding rank, in general, it should use LHF_DEFAULT_RANK.
See also
lhfcSolve
Definition at line 1114 of file libhifir.cpp.
References libhifir_impl::hifir(), LHF_DEFAULT_RANK, LHF_M, LHF_MH, LHF_MISMATCHED_SIZES, LHF_S, LHF_SH, LHF_SUCCESS, libhifir_impl::mmultiply(), hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows(), and libhifir_impl::solve().
lhfcCreate()
LhfcHifHdl lhfcCreate (const LhfcMatrixHdl A, const LhfcMatrixHdl S, const double params[])
Create a single-precision complex HIF instance.
Parameters
[in] A Input coefficient matrix (used in iterative refinement)
[in] S Sparsifier input
[in] params Control parameters, see lhfSetDefaultParams
This function create an instance of single-precision HIF (see hif::HIF) preconditioner. Note that both A and S can be NULL, which then will create an empty instance. If both operators are provided, then the preconditioner will be factorized based on S. If only A is provided, then HIF is computed on A. If only S is provided, then A is set to be S besides computing the factorization on it. In addition, if params is NULL, then the default parameters will be used.
See also
lhfcDestroy
Definition at line 1053 of file libhifir.cpp.
References LHF_HIFIR_ERROR, lhfcDestroy(), and lhfcSetup().
lhfcCreateMatrix()
LhfcMatrixHdl lhfcCreateMatrix (const int is_rowmajor, const size_t n, const LhfIndPtr * indptr, const LhfInt * indices, const float _Complex * vals)
Create an instance of single-precision complex sparse matrix.
Parameters
[in] is_rowmajor If true, then we use CRS, otherwise CCS is assumed
[in] n Size of the squared matrix
[in] indptr Index pointer array
[in] indices Index list
[in] vals Numerical value array
Note
The last three entries can be NULL, which will create an empty instance of sparse matrix.
Definition at line 975 of file libhifir.cpp.
lhfcDestroy()
LhfStatus lhfcDestroy (LhfcHifHdl hif)
Destroy a single-precision complex HIF instance.
Parameters
[out] hif HIF preconditioner
See also
lhfcCreate
Definition at line 1067 of file libhifir.cpp.
References LHF_SUCCESS.
Referenced by lhfcCreate().
lhfcDestroyMatrix()
LhfStatus lhfcDestroyMatrix (LhfcMatrixHdl mat)
Destroy a single-precision complex matrix instance.
Parameters
[in,out] mat Matrix instance
Definition at line 995 of file libhifir.cpp.
References LHF_SUCCESS.
lhfcGetLevels()
size_t lhfcGetLevels (const LhfcHifHdl hif)
Get number of levels.
See also
lhfcGetStats
Definition at line 1172 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::levels().
lhfcGetMatrixNnz()
size_t lhfcGetMatrixNnz (const LhfcMatrixHdl mat)
Get the matrix number of nonzeros.
Definition at line 1006 of file libhifir.cpp.
lhfcGetMatrixSize()
size_t lhfcGetMatrixSize (const LhfcMatrixHdl mat)
Get the matrix size.
Definition at line 1001 of file libhifir.cpp.
lhfcGetNnz()
size_t lhfcGetNnz (const LhfcHifHdl hif)
Get number of nonzeros of a HIF preconditioner.
See also
lhfcGetStats
Definition at line 1168 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nnz().
lhfcGetSchurRank()
size_t lhfcGetSchurRank (const LhfcHifHdl hif)
Get the Schur complement rank.
See also
lhfcGetStats
Definition at line 1180 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::schur_rank().
lhfcGetSchurSize()
size_t lhfcGetSchurSize (const LhfcHifHdl hif)
Get the Schur complement size.
See also
lhfcGetStats
Definition at line 1176 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::schur_size().
lhfcGetStats()
LhfStatus lhfcGetStats (const LhfcHifHdl hif, size_t stats[])
Get the statistics of a computed HIF instance.
Parameters
[in] hif A HIF instance
[out] stats A length-9 array stores certain useful information
Regarding the output stats:
stats[0]: Number of nonzeros of a preconditioner
stats[1]: Total deferals
stats[2]: Dynamic deferals (status[1]-status[2] are static deferals)
stats[3]: Total droppings
stats[4]: Droppings due to scalability-oriented strategy
stats[5]: Number of levels
stats[6]: Numerical rank of the whole preconditioner
stats[7]: The numerical rank of the final Schur complement
stats[8]: The size of the final Schur complement (status[7]<=status[8])
Definition at line 1159 of file libhifir.cpp.
References libhifir_impl::get_factor_stats(), and LHF_SUCCESS.
lhfcReadSparse()
LhfStatus lhfcReadSparse (const char * fname, LhfcMatrixHdl mat)
Read a sparse matrix.
Parameters
[in] fname Filename of a matrix market file
[out] mat Output sparse matrix that stores the data in fname
See also
lhfQueryMmFile
Definition at line 1027 of file libhifir.cpp.
References libhifir_impl::mm_read_sparse().
lhfcReadVector()
LhfStatus lhfcReadVector (const char * fname, const size_t n, float _Complex * v)
Read a vector.
Parameters
[in] fname Filename of a matrix market file
[in] n Vector size
[out] v Vector data output
See also
lhfQueryMmFile
Definition at line 1032 of file libhifir.cpp.
References hif::Array< T >::cbegin(), hif::Array< T >::cend(), hif::Array< T >::from_mm(), LHF_MISMATCHED_SIZES, LHF_SUCCESS, hif::Array< T >::operator=(), and hif::Array< T >::size().
lhfcRefactorize()
LhfStatus lhfcRefactorize (LhfcHifHdl hif, const LhfcMatrixHdl S, const double params[])
Refactorize a HIF preconditioner.
Parameters
[out] hif A HIF instance
[in] S A new sparsifier
[in] params Control parameters
Note
This function will not update A inside hif
If params is NULL, then the default parameters will be used.
See also
lhfcUpdate
Definition at line 1101 of file libhifir.cpp.
References libhifir_impl::factorize(), and LHF_SUCCESS.
lhfcSetup()
LhfStatus lhfcSetup (LhfcHifHdl hif, const LhfcMatrixHdl A, const LhfcMatrixHdl S, const double params[])
Setup a single-precision complex HIF instance.
Parameters
[out] hif A HIF instance
[in] A Input coefficient matrix (used in iterative refinement)
[in] S Sparsifier input
[in] params Control parameters, see lhfSetDefaultParams
This function serves similar to lhfcCreate, except that A and S cannot be both NULL. This function is to defer the factorization from construction of HIF preconditioners.
See also
lhfcCreate
Definition at line 1076 of file libhifir.cpp.
References libhifir_impl::factorize(), and LHF_SUCCESS.
Referenced by lhfcCreate().
lhfcSolve()
LhfStatus lhfcSolve (const LhfcHifHdl hif, const float _Complex * b, float _Complex * x)
Triangular solve.
For the sake of convenience, we provide the following routine as it is the most commonly used interface. The following routine is equivalent to calling lhfcApply with op=LHF_S, nirs=1, and rank=LHF_DEFAULT_RANK.
See also
lhfcApply
Definition at line 1146 of file libhifir.cpp.
References LHF_SUCCESS, and libhifir_impl::solve().
lhfcUpdate()
LhfStatus lhfcUpdate (LhfcHifHdl hif, const LhfcMatrixHdl A)
Update the A matrix in HIF.
Parameters
[out] hif A HIF instance
[in] A A new matrix
Note
This function will not call factorization on A.
See also
lhfcRefactorize
Definition at line 1092 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::empty(), LHF_MISMATCHED_SIZES, LHF_SUCCESS, and hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows().
lhfcWrapMatrix()
LhfStatus lhfcWrapMatrix (LhfcMatrixHdl mat, const size_t n, const LhfIndPtr * indptr, const LhfInt * indices, const float _Complex * vals)
Wrap external data into a single-precision complex sparse matrix.
Parameters
[out] mat Matrix that holds the external data
[in] n Size the squared matrix
[in] indptr Index pointer array
[in] indices Index list
[in] vals Numerical value array
Definition at line 1012 of file libhifir.cpp.
References LHF_NULL_OBJ, and LHF_SUCCESS.