HIFIR: LIBHIFIR C Interfaces
LIBHIFIR C Interfaces
Modules
Double-Precision Routines in LIBHIFIR
Single-Precision Routines in LIBHIFIR
Double-Precision Complex Routines in LIBHIFIR
Single-Precision Complex Routines in LIBHIFIR
Mixed-Precision Routines in LIBHIFIR
Macros
#define LIBHIFIR_INT_SIZE 32
#define LIBHIF_INDPTR_SIZE 64
Typedefs
typedef int32_t LhfInt
Integer type used in index arrays in sparse matrice and HIF.
typedef ptrdiff_t LhfIndPtr
Integer type used in ind_start arrays in sparse matrice and HIF.
typedef enum LhfStatus LhfStatus
typedef enum LhfOperationType LhfOperationType
Enumerations
enum {
LHF_DROPTOL_L = 0, LHF_DROPTOL_U, LHF_COND_D, LHF_COND,
LHF_ALPHA_L, LHF_ALPHA_U, LHF_VERBOSE, LHF_REORDER,
LHF_SYMMPRELVLS, LHF_THREADS, LHF_RRQR_COND, LHF_PIVOT,
LHF_BETA, LHF_ISSYMM, LHF_NOPRE, LHF_NZP_THRES,
LHF_DENSE_THRES, LHF_NUMBER_PARAMS
}
enum {
LHF_VERBOSE_NULL = 0, LHF_VERBOSE_INFO = 1, LHF_VERBOSE_PRE = 2, LHF_VERBOSE_FAC = 4,
LHF_VERBOSE_PRE_TIME = 8, LHF_VERBOSE_MEM = 16
}
enum { LHF_REORDER_OFF = 0, LHF_REORDER_AUTO, LHF_REORDER_AMD, LHF_REORDER_RCM }
enum { LHF_PIVOTING_OFF = 0, LHF_PIVOTING_ON, LHF_PIVOTING_AUTO }
enum LhfStatus {
LHF_SUCCESS = 0, LHF_NULL_OBJ, LHF_MISMATCHED_SIZES, LHF_BAD_PREC,
LHF_HIFIR_ERROR
}
Return status.
enum LhfOperationType { LHF_S = 0, LHF_SH, LHF_M, LHF_MH }
Operation tags for the apply functions.
Functions
void lhfGetVersions (int versions[])
Get versions of the C++ HIFIR package.
void lhfEnableWarning (void)
Enable warning.
void lhfDisableWarning (void)
Disable warning.
const char * lhfGetErrorMsg (void)
Get global error message if the return status is LHF_HIFIR_ERROR.
LhfStatus lhfSetDefaultParams (double params[])
Initialize parameters with default options.
LhfStatus lhfSetDroptol (const double droptol, double params[])
Set unified droptol for both L and U factors.
LhfStatus lhfSetAlpha (const double alpha, double params[])
Set unified fill factors for both L and U factors.
LhfStatus lhfSetKappa (const double kappa, double params[])
Set unified inverse-norm threshold for L, U, and D factors.
LhfStatus lhfQueryMmFile (const char *fname, int *is_sparse, int *is_real, size_t *nrows, size_t *ncols, size_t *nnz)
Query information of a MatrixMarket file.
Variables
static const int LHF_DEFAULT_RANK = -2
Detailed Description
Macro Definition Documentation
LIBHIF_INDPTR_SIZE
#define LIBHIF_INDPTR_SIZE 64
Definition at line 67 of file libhifir.h.
LIBHIFIR_INT_SIZE
#define LIBHIFIR_INT_SIZE 32
Definition at line 48 of file libhifir.h.
Typedef Documentation
LhfIndPtr
LhfIndPtr
Integer type used in ind_start arrays in sparse matrice and HIF.
Note
The default value is ptrdiff_t
Definition at line 80 of file libhifir.h.
LhfInt
LhfInt
Integer type used in index arrays in sparse matrice and HIF.
Note
The default value is int
Definition at line 61 of file libhifir.h.
LhfOperationType
typedef enum LhfOperationType LhfOperationType
LhfStatus
typedef enum LhfStatus LhfStatus
Enumeration Type Documentation
anonymous enum
anonymous enum
We use an anonymous enum to group parameter positions in an array. The first thing one needs to do is to create a double array of length LHF_NUMBER_PARAMSs.
double params[LHF_NUMBER_PARAMS];
lhfSetDefaultParams(params);
params[LHF_DROPTOL_L] = params[LHF_DROPTOL_U] = 3.0;
Enumerator
LHF_DROPTOL_L
Drop tolerance for L factor
LHF_DROPTOL_U
Drop tolerance for U factor
LHF_COND_D
Conditioning threshold for diagonal
LHF_COND
Conditioning threshold for L and U factors
LHF_ALPHA_L
Scalability-oriented dropping factor for L
LHF_ALPHA_U
Scalability-oriented dropping factor for U
LHF_VERBOSE
Verbose level
LHF_REORDER
Reorder option
LHF_SYMMPRELVLS
Option for tuning symmetric preprocessing levels
LHF_THREADS
Option for choosing nthreads for Schur computation
LHF_RRQR_COND
Condition number threshold used in the final RRQR
LHF_PIVOT
Pivoting option
LHF_BETA
Option for the threshold used in preventing bad scaling factors from equlibriation in preprocessing.
LHF_ISSYMM
Flag to tunning on symmetric/Hermitian input
LHF_NOPRE
Option to turn on/off preprocessing
LHF_NZP_THRES
Nonzero pattern symmetry threshold for symmetric preprocessing
LHF_DENSE_THRES
Dense size threshold for the Schur complement
LHF_NUMBER_PARAMS
Total number of parameters
Definition at line 96 of file libhifir.h.
anonymous enum
anonymous enum
Enumerator
LHF_VERBOSE_NULL
LHF_VERBOSE_INFO
LHF_VERBOSE_PRE
LHF_VERBOSE_FAC
LHF_VERBOSE_PRE_TIME
LHF_VERBOSE_MEM
Definition at line 120 of file libhifir.h.
anonymous enum
anonymous enum
Enumerator
LHF_REORDER_OFF
LHF_REORDER_AUTO
LHF_REORDER_AMD
LHF_REORDER_RCM
Definition at line 130 of file libhifir.h.
anonymous enum
anonymous enum
Enumerator
LHF_PIVOTING_OFF
LHF_PIVOTING_ON
LHF_PIVOTING_AUTO
Definition at line 138 of file libhifir.h.
LhfOperationType
enum LhfOperationType
Operation tags for the apply functions.
Enumerator
LHF_S
Standard triangular solve
LHF_SH
Hermitian/transpose solve
LHF_M
Multilevel matrix-vector product
LHF_MH
Hermitian/transpose matrix-vector product
Definition at line 160 of file libhifir.h.
LhfStatus
enum LhfStatus
Return status.
Enumerator
LHF_SUCCESS
Successful return
LHF_NULL_OBJ
Calling functions on NULL objects
LHF_MISMATCHED_SIZES
Mismatched sizes
LHF_BAD_PREC
Improper use of a preconditioner
LHF_HIFIR_ERROR
Internal HIFIR error, call lhfGetErrorMsg
Definition at line 148 of file libhifir.h.
Function Documentation
lhfDisableWarning()
void lhfDisableWarning (void)
Disable warning.
Definition at line 227 of file libhifir.cpp.
References hif::warn_flag().
lhfEnableWarning()
void lhfEnableWarning (void)
Enable warning.
Definition at line 224 of file libhifir.cpp.
References hif::warn_flag().
lhfGetErrorMsg()
const char* lhfGetErrorMsg (void)
Get global error message if the return status is LHF_HIFIR_ERROR.
Definition at line 230 of file libhifir.cpp.
References libhifir_impl::error_msgs.
lhfGetVersions()
void lhfGetVersions (int versions[])
Get versions of the C++ HIFIR package.
Parameters
[out] versions A length-three array storing global, major, and minor versions
Definition at line 217 of file libhifir.cpp.
lhfQueryMmFile()
LhfStatus lhfQueryMmFile (const char * fname, int * is_sparse, int * is_real, size_t * nrows, size_t * ncols, size_t * nnz)
Query information of a MatrixMarket file.
Parameters
[in] fname File name of a matrix market file
[out] is_sparse Sparse/dense tag
[out] is_real Real/complex tag
[out] nrows Number of rows
[out] ncols Number of columns
[out] nnz Number of nonzeros
If the file stores a dense array, then nrows stores the length of the array, and both ncols and nnz are set to zero.
See also
lhfdReadSparse, lhfdReadVector, lhfsReadSparse, lhfsReadVector, lhfzReadSparse, lhfzReadVector, lhfcReadSparse, lhfcReadVector
Definition at line 277 of file libhifir.cpp.
References LHF_NULL_OBJ, LHF_SUCCESS, hif::internal::mm_read_dense_size(), hif::internal::mm_read_firstline(), and hif::internal::mm_read_sparse_size().
lhfSetAlpha()
LhfStatus lhfSetAlpha (const double alpha, double params[])
Set unified fill factors for both L and U factors.
Parameters
[in] alpha Fill factor value
[out] params Parameter array of legnth LHF_NUMBER_PARAMS
See also
lhfSetDefaultParams
Definition at line 266 of file libhifir.cpp.
References LHF_ALPHA_L, LHF_ALPHA_U, and LHF_SUCCESS.
lhfSetDefaultParams()
LhfStatus lhfSetDefaultParams (double params[])
Initialize parameters with default options.
Parameters
[out] params Parameter array of legnth LHF_NUMBER_PARAMS
See also
lhfSetDroptol, lhfSetAlpha
Definition at line 238 of file libhifir.cpp.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::beta, hif::DEFAULT_PARAMS, hif_Options::dense_thres, hif_Options::is_symm, hif_Options::kappa, hif_Options::kappa_d, LHF_ALPHA_L, LHF_ALPHA_U, LHF_BETA, LHF_COND, LHF_COND_D, LHF_DENSE_THRES, LHF_DROPTOL_L, LHF_DROPTOL_U, LHF_ISSYMM, LHF_NOPRE, LHF_NZP_THRES, LHF_PIVOT, LHF_REORDER, LHF_RRQR_COND, LHF_SUCCESS, LHF_SYMMPRELVLS, LHF_THREADS, LHF_VERBOSE, hif_Options::no_pre, hif_Options::nzp_thres, hif_Options::pivot, hif_Options::reorder, hif_Options::rrqr_cond, hif_Options::symm_pre_lvls, hif_Options::tau_L, hif_Options::tau_U, hif_Options::threads, and hif_Options::verbose.
lhfSetDroptol()
LhfStatus lhfSetDroptol (const double droptol, double params[])
Set unified droptol for both L and U factors.
Parameters
[in] droptol Drop tolerance value
[out] params Parameter array of legnth LHF_NUMBER_PARAMS
See also
lhfSetDefaultParams
Definition at line 260 of file libhifir.cpp.
References LHF_DROPTOL_L, LHF_DROPTOL_U, and LHF_SUCCESS.
lhfSetKappa()
LhfStatus lhfSetKappa (const double kappa, double params[])
Set unified inverse-norm threshold for L, U, and D factors.
Parameters
[in] kappa Inverse-norm threshold value
[out] params Parameter array of legnth LHF_NUMBER_PARAMS
See also
lhfSetDefaultParams
Definition at line 271 of file libhifir.cpp.
References LHF_COND, LHF_COND_D, and LHF_SUCCESS.
Variable Documentation
LHF_DEFAULT_RANK
const int LHF_DEFAULT_RANK = -2 static
Default numerical rank in apply routines
Definition at line 167 of file libhifir.h.
Referenced by lhfcApply(), lhfczApply(), lhfdApply(), lhfsApply(), lhfsdApply(), and lhfzApply().