HIFIR: Multilevel Factorization
Multilevel Factorization
Algorithms
Classes
class hif::internal::CompressedTypeTrait< CsType1, CsType2 >
Core component to filter CCS and CRS types.
Functions
std::tuple< double, double, double, double, double, double > hif::internal::determine_fac_pars (const Options &opts, const int lvl)
adjust parameters based on levels
template<class CcsType , class ScalingType , class PermType >
Array< typename CcsType::value_type > hif::internal::extract_perm_diag (const ScalingType &s, const CcsType A, const ScalingType &t, const typename CcsType::size_type m, const PermType &p, const PermType &q, const typename CcsType::size_type m0=0)
extract permutated diagonal
template<class CrsType , class ScalingType , class PermType >
CrsType::other_type hif::internal::extract_E (const ScalingType &s, const CrsType &A, const ScalingType &t, const typename CrsType::size_type m, const PermType &p, const PermType &q)
extract the E part
template<class CcsType , class ScalingType , class PermType , class BufferType >
CcsType hif::internal::extract_F (const ScalingType &s, const CcsType &A, const ScalingType &t, const typename CcsType::size_type m, const PermType &p, const PermType &q, BufferType &buf)
extract the F part
template<class L_Type , class U_Type , class PosArray >
void hif::internal::compress_tails (U_Type &U, L_Type &L, const PosArray &U_start, const PosArray &L_start, const typename PosArray::size_type m, const typename PosArray::size_type dfrs)
compress offsets to have a compact L and U
void hif::internal::print_post_flag (const int flag)
print out information regarding handling Schur complement
template<class MatType , class OtherType >
double hif::internal::compute_pattern_symm_ratio (const MatType &A, const OtherType &AT)
Determine pattern symmetry.
template<bool IsSymm, class CsType , class CroutStreamer , class PrecsType , class IntArray >
CsType hif::level_factorize (const CsType &A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options &opts, const CroutStreamer &Crout_info, PrecsType &precs, IntArray &row_sizes, IntArray &col_sizes, typename CsType::size_type *stats, const int schur_threads=1, int *auto_pivot_tag=nullptr)
perform partial incomplete LU for a level
template<class CsType , class CroutStreamer , class PrecsType , class IntArray >
CsType hif::pivot_level_factorize (const CsType &A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options &opts, const CroutStreamer &Crout_info, PrecsType &precs, IntArray &row_sizes, IntArray &col_sizes, typename CsType::size_type *stats, const int schur_threads=1)
perform partial incomplete LU for a level with thresholding pivoting
template<class CsType , class CroutStreamer , class PrecsType , class IntArray >
CsType hif::symm_level_factorize (const CsType &A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options &opts, const CroutStreamer &Crout_info, PrecsType &precs, IntArray &row_sizes, typename CsType::size_type *stats, const int schur_threads=1)
perform partial incomplete LU for a level
Detailed Description
Function Documentation
compress_tails()
template<class L_Type , class U_Type , class PosArray > void hif::internal::compress_tails (U_Type & U, L_Type & L, const PosArray & U_start, const PosArray & L_start, const typename PosArray::size_type m, const typename PosArray::size_type dfrs) inline
compress offsets to have a compact L and U
Template Parameters
L_Type storage for L, see CCS
U_Type storage for U, see CRS
PosArray array for storing starting positions, see Array
Parameters
[in,out] U uncompressed U part
[in,out] L uncompressed L part
[in] U_start starting positions of the offset of U
[in] L_start starting positions of the offset of L
[in] m leading block size
[in] dfrs total number of deferrals
Definition at line 435 of file factor.hpp.
compute_pattern_symm_ratio()
template<class MatType , class OtherType > double hif::internal::compute_pattern_symm_ratio (const MatType & A, const OtherType & AT) inline
Determine pattern symmetry.
Template Parameters
MatType Matrix type, either CRS or CCS
OtherType Opposite of MatType, e.g., if MatType is CRS, then this type is CCS
Parameters
[in] A Input matrix A
[in] AT Transpose of A
Returns
The pattern symmetry ratio
Definition at line 499 of file factor.hpp.
determine_fac_pars()
std::tuple<double, double, double, double, double, double> hif::internal::determine_fac_pars (const Options & opts, const int lvl) inline
adjust parameters based on levels
Parameters
[in] opts control parameters, i.e. Options
[in] lvl levels
Returns
refined parameters
Definition at line 80 of file factor.hpp.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::kappa, hif_Options::kappa_d, hif_Options::rf_par, hif_Options::tau_L, and hif_Options::tau_U.
Referenced by hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
extract_E()
template<class CrsType , class ScalingType , class PermType > CrsType::other_type hif::internal::extract_E (const ScalingType & s, const CrsType & A, const ScalingType & t, const typename CrsType::size_type m, const PermType & p, const PermType & q) inline
extract the E part
Template Parameters
CrsType input crs matrix, see CRS
ScalingType scaling vector type, see Array
PermType permutation matrix type, see BiPermMatrix
Parameters
[in] s row scaling vector
[in] A input matrix in crs format
[in] t column scaling vector
[in] m leading block size (final)
[in] p row permutation vector
[in] q column permutation vector
Returns
The E part in CCS format
See also
extract_F
This routine is to extract the E part after Crout update. Essentially, this routine is to perform:
Definition at line 185 of file factor.hpp.
References hif::DATA_UNDEF, and hif::error().
extract_F()
template<class CcsType , class ScalingType , class PermType , class BufferType > CcsType hif::internal::extract_F (const ScalingType & s, const CcsType & A, const ScalingType & t, const typename CcsType::size_type m, const PermType & p, const PermType & q, BufferType & buf) inline
extract the F part
Template Parameters
CcsType input ccs matrix, see CCS
ScalingType scaling vector type, see Array
PermType permutation matrix type, see BiPermMatrix
BufferType work space array, can be Array or std::vector
Parameters
[in] s row scaling vector
[in] A input matrix in CCS format
[in] t column scaling vector
[in] m leading block size
[in] p row permutation vector
[in] q column permutation vector
buf work space
Returns
The F part in ccs storage
See also
extract_E
Note that unlike extracting the E part, this routine takes CCS as input, and with the permutation vectors, we need a value buffer space as an intermidiate storage to store the values so that is will make sorting much easier. The buffer space is a dense array, and can be passed in from that of l or ut (if squared systems).
This routine, essentially, is to compute:
Definition at line 288 of file factor.hpp.
References hif::DATA_UNDEF, and hif::error().
extract_perm_diag()
template<class CcsType , class ScalingType , class PermType > Array<typename CcsType::value_type> hif::internal::extract_perm_diag (const ScalingType & s, const CcsType A, const ScalingType & t, const typename CcsType::size_type m, const PermType & p, const PermType & q, const typename CcsType::size_type m0 = 0) inline
extract permutated diagonal
Template Parameters
CcsType input ccs matrix, see CCS
ScalingType scaling vector type, see Array
PermType permutation matrix type, see BiPermMatrix
Parameters
[in] s row scaling vector
[in] A input matrix in CCS format
[in] t column scaling vector
[in] m leading block size
[in] p row permutation vector
[in] q column permutation vector
[in] m0 actual extrated size, default is m
Returns
permutated diagonal of A
This routine, essentially, is to compute:
This routine is used before Crout update to extract the initial diagonal entries.
Definition at line 130 of file factor.hpp.
References hif::DATA_UNDEF, and hif::error().
level_factorize()
template<bool IsSymm, class CsType , class CroutStreamer , class PrecsType , class IntArray > CsType hif::level_factorize (const CsType & A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options & opts, const CroutStreamer & Crout_info, PrecsType & precs, IntArray & row_sizes, IntArray & col_sizes, typename CsType::size_type * stats, const int schur_threads = 1, int * auto_pivot_tag = nullptr) inline
perform partial incomplete LU for a level
Template Parameters
IsSymm if true, then assume a symmetric leading block
CsType input compressed storage, either CRS or CCS
CroutStreamer information streamer for Crout update
PrecsType multilevel preconditioner type, Precs and Prec
IntArray integer array for storing sizes
Parameters
[in] A input for this level
[in] m0 initial leading block size
[in] N reference global size for determining Schur sparsity
[in] opts control parameters
[in] Crout_info information streamer, API same as hif_info
[in,out] precs list of preconditioner, newly computed components will be pushed back to the list.
[in,out] row_sizes local row nnz of user input
[in,out] col_sizes local column nnz of user input
[in,out] stats hierarchical stats
[in] schur_threads (optional) threads usedin Schur-related computations
[out] auto_pivot_tag (optional) pivoting tag for PIVOT_AUTO
Returns
Schur complement for next level (if needed), in the same type as that of the input, i.e. CsType
Definition at line 553 of file factor.hpp.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::c_d, hif::DATA_UNDEF, hif::Crout::deferred_step(), hif::Crout::defers(), hif_Options::dense_thres, hif::internal::determine_fac_pars(), hif::error(), hif_Options::fat_schur_1st, hif::Timer< Clock, RepType >::finish(), hif::Crout::increment_defer_counter(), hif::info(), hif_Options::no_pre, hif_Options::nzp_thres, hif::Crout::operator++(), hif_Options::pivot, hif::PIVOTING_AUTO, hif::internal::print_post_flag(), hif_Options::rho, hif::Timer< Clock, RepType >::start(), hif_Options::symm_pre_lvls, and hif::Timer< Clock, RepType >::time().
pivot_level_factorize()
template<class CsType , class CroutStreamer , class PrecsType , class IntArray > CsType hif::pivot_level_factorize (const CsType & A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options & opts, const CroutStreamer & Crout_info, PrecsType & precs, IntArray & row_sizes, IntArray & col_sizes, typename CsType::size_type * stats, const int schur_threads = 1) inline
perform partial incomplete LU for a level with thresholding pivoting
Template Parameters
CsType input compressed storage, either CRS or CCS
CroutStreamer information streamer for Crout update
PrecsType multilevel preconditioner type, Precs and Prec
IntArray integer array for storing sizes
Parameters
[in] A input for this level
[in] m0 initial leading block size
[in] N reference global size for determining Schur sparsity
[in] opts control parameters
[in] Crout_info information streamer, API same as hif_info
[in,out] precs list of preconditioner, newly computed components will be pushed back to the list.
[in,out] row_sizes local row nnz of user input
[in,out] col_sizes local column nnz of user input
[in,out] stats hierarchical stats
[in] schur_threads threads usedin Schur-related computations
Returns
Schur complement for next level (if needed), in the same type as that of the input, i.e. CsType
See also
level_factorize
Definition at line 65 of file pivot_factor.hpp.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::c_d, hif::DATA_UNDEF, hif::Crout::deferred_step(), hif::Crout::defers(), hif_Options::dense_thres, hif::internal::determine_fac_pars(), hif::error(), hif_Options::fat_schur_1st, hif::Timer< Clock, RepType >::finish(), hif_Options::gamma, hif::Crout::increment_defer_counter(), hif::info(), hif_Options::no_pre, hif::Crout::operator++(), hif::internal::print_post_flag(), hif_Options::rho, hif::Timer< Clock, RepType >::start(), hif_Options::symm_pre_lvls, and hif::Timer< Clock, RepType >::time().
print_post_flag()
void hif::internal::print_post_flag (const int flag) inline
print out information regarding handling Schur complement
Definition at line 462 of file factor.hpp.
Referenced by hif::level_factorize(), hif::pivot_level_factorize(), and hif::symm_level_factorize().
symm_level_factorize()
template<class CsType , class CroutStreamer , class PrecsType , class IntArray > CsType hif::symm_level_factorize (const CsType & A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options & opts, const CroutStreamer & Crout_info, PrecsType & precs, IntArray & row_sizes, typename CsType::size_type * stats, const int schur_threads = 1) inline
perform partial incomplete LU for a level
Template Parameters
CsType input compressed storage, either CRS or CCS
CroutStreamer information streamer for Crout update
PrecsType multilevel preconditioner type, Precs and Prec
IntArray integer array for storing sizes
Parameters
[in] A input for this level
[in] m0 initial leading block size
[in] N reference global size for determining Schur sparsity
[in] opts control parameters
[in] Crout_info information streamer, API same as hif_info
[in,out] precs list of preconditioner, newly computed components will be pushed back to the list.
[in,out] row_sizes local row nnz of user input
[in,out] stats hierarchical stats
[in] schur_threads threads usedin Schur-related computations
Returns
Schur complement for next level (if needed), in the same type as that of the input, i.e. CsType
Definition at line 126 of file symm_factor.hpp.
References hif_Options::alpha_L, hif_Options::c_d, hif::DATA_UNDEF, hif::Crout::deferred_step(), hif::Crout::defers(), hif_Options::dense_thres, hif::internal::determine_fac_pars(), hif::error(), hif_Options::fat_schur_1st, hif::Timer< Clock, RepType >::finish(), hif::Crout::increment_defer_counter(), hif::info(), hif_Options::no_pre, hif::Crout::operator++(), hif::internal::print_post_flag(), hif_Options::rho, hif_Options::spd, hif::Timer< Clock, RepType >::start(), and hif::Timer< Clock, RepType >::time().