HIFIR: Preprocessing
Preprocessing
Classes
class hif::amd::AMD< Int >
kernels for approxmiated minimum degree orderingThis class contains only static member functions, which are extracted and template-ized from original SuiteSparse AMD implementation.
class hif::EqlDriver< ValueType, IndexType >
driver class wrapped around eql::Equilibrator
class hif::eql::Equilibrator< _Integer, _Value, _Real, _Container >
object for equilibrating a CRS/CCS matrixAs to the container, besides it must be array, the following interfaces are needed:
class hif::rcm::RCM< _Integer >
reversed Cuthill-Mckee ordering for reducing bandwidth
Functions
template<class CrsType , class ScalingType >
void hif::scale_eye (CrsType &B, ScalingType &rs, ScalingType &cs, const bool ensure_fortran_index=true)
do not perform a priori scaling
template<bool IsSymm, class CrsType , class ScalingType >
void hif::scale_extreme_values (CrsType &B, ScalingType &rs, ScalingType &cs, const bool ensure_fortran_index=true)
scale based on extreme values, do it asynchronously
template<bool IsSymm, class PermType , class CrsType , class ScalingType >
void hif::iterative_scale_p (const PermType &p, CrsType &A, ScalingType &rs, ScalingType &cs, const double tol=1e-10, const typename CrsType::size_type max_iters=5, const bool ensure_fortran_index=true)
iterative scaling based on Jacobi operation
template<bool IsSymm, class CrsType , class ScalingType >
void hif::iterative_scale (CrsType &A, ScalingType &rs, ScalingType &cs, const double tol=1e-10, const typename CrsType::size_type max_iters=5, const bool ensure_fortran_index=true)
iterative scaling based on Jacobi operation
template<bool IsSymm, class CcsType , class CrsType , class ScalingArray , class PermType >
CcsType::size_type hif::do_preprocessing (const CcsType &A, const CrsType &A_crs, const typename CcsType::size_type m0, const typename CcsType::size_type level, const Options &opt, ScalingArray &s, ScalingArray &t, PermType &p, PermType &q)
routine to perform preprocessing for improving the quality of input
template<typename _Integer >
void hif::eql::detail::set_default_pars (_Integer *pars)
template<typename _Integer , typename _Real >
void hif::eql::detail::kernel (_Integer, const _Integer *, const _Integer *, const _Real *, _Integer *, _Integer *, _Integer *, _Integer *, _Integer *, _Integer *, _Integer *, _Real *, _Real *)
template<typename _Integer , typename _ValReal , typename _Real >
void hif::eql::detail::compute (const _Integer n, const _Integer ne, const _Integer *indptr, const _Integer *indices, const _ValReal *vals, _Integer *no, _Integer *cperm, _Integer liwork, _Integer *iwork, _Integer lwork, _Real *work, const _Integer *pars, _Integer *info)
template<typename _Integer , typename _Real >
void hif::eql::detail::kernel_ (const _Integer j, const _Integer n, _Integer *q, _Real *d__, _Integer *l, const bool flag)
template<typename _Integer , typename _Real >
void hif::eql::detail::kernel__ (_Integer *ql, const _Integer n, _Integer *q, _Real *d__, _Integer *l, const bool flag)
template<typename _Integer , typename _Real >
void hif::eql::detail::kernel___ (_Integer *pos_, _Integer *qlen, const _Integer n, _Integer *q, _Real *d__, _Integer *l, const bool flag)
template<typename _Integer , typename _Real >
void hif::eql::detail::cleanup (const _Integer n, _Integer *num, _Integer *iperm, _Integer *jperm, const _Integer *irn, _Integer *out, const _Real *a, _Real *d__, _Real *u)
template<class PermType , class ScalingArray >
void hif::internal::fix_poor_scaling (const typename ScalingArray::size_type m0, const typename ScalingArray::size_type level, const PermType &p, const PermType &q, ScalingArray &s, ScalingArray &t, const double beta=1e3)
fix poorly scaled row and column weights due to MC64
template<bool IsSymm, class CcsType , class CrsType , class PermType , class BufType >
CcsType::size_type hif::internal::defer_tiny_diags (const CcsType &A, const CrsType &A_crs, const typename CcsType::size_type m0, PermType &p, PermType &q, BufType &work_p, BufType &work_q)
defer any zero diags to the end
template<class CcsType , class CrsType , class PermType >
CcsType hif::internal::compute_leading_block (const CcsType &A, const CrsType &A_crs, const typename CcsType::size_type m, const PermType &p, const PermType &q, const bool apat=false)
permute the matrix for asymmetric cases
template<bool IsSymm, class CcsType , class CrsType , class ScalingArray , class PermType >
std::pair< CCS< typename CcsType::value_type, typename CcsType::index_type >, typename CcsType::size_type > hif::do_maching (const CcsType &A, const CrsType &A_crs, const typename CcsType::size_type m0, const typename CcsType::size_type level, const Options &opts, ScalingArray &s, ScalingArray &t, PermType &p, PermType &q)
compute the matching for preprocessing
template<typename _Integer >
int hif::rcm::detail::rootls_ (const _Integer root, const _Integer *xadj, const _Integer *adjncy, std::vector< bool > &mask, _Integer *nlvl, _Integer *xls, _Integer *ls)
template<typename _Integer >
int hif::rcm::detail::fnroot_ (_Integer *root, const _Integer *xadj, const _Integer *adjncy, std::vector< bool > &mask, _Integer *nlvl, _Integer *xls, _Integer *ls)
template<typename _Integer >
int hif::rcm::detail::degree_ (const _Integer root, _Integer *xadj, const _Integer *adjncy, std::vector< bool > &mask, _Integer *deg, _Integer *ccsize, _Integer *ls)
template<typename _Integer >
int hif::rcm::detail::rcm_ (const _Integer root, _Integer *xadj, const _Integer *adjncy, std::vector< bool > &mask, _Integer *perm, _Integer *ccsize, _Integer *deg)
template<typename _Integer >
int hif::rcm::detail::genrcm_ (const _Integer neqns, _Integer *xadj, const _Integer *adjncy, _Integer *perm, std::vector< bool > &mask, _Integer *xls)
template<bool IsSymm, class CcsType >
Array< typename CcsType::index_type > hif::run_amd (const CcsType &B, const Options &opt)
apply approximated mimimum degree ordering
template<class CcsType >
CcsType::iarray_type hif::run_rcm (const CcsType &B, const Options &opt)
apply reversed Cuthill-Mckee ordering
Detailed Description
Function Documentation
cleanup()
template<typename _Integer , typename _Real > void hif::eql::detail::cleanup (const _Integer n, _Integer * num, _Integer * iperm, _Integer * jperm, const _Integer * irn, _Integer * out, const _Real * a, _Real * d__, _Real * u)
Definition at line 342 of file equilibrate.hpp.
compute()
template<typename _Integer , typename _ValReal , typename _Real > void hif::eql::detail::compute (const _Integer n, const _Integer ne, const _Integer * indptr, const _Integer * indices, const _ValReal * vals, _Integer * no, _Integer * cperm, _Integer liwork, _Integer * iwork, _Integer lwork, _Real * work, const _Integer * pars, _Integer * info) inline
Definition at line 66 of file equilibrate.hpp.
compute_leading_block()
template<class CcsType , class CrsType , class PermType > CcsType hif::internal::compute_leading_block (const CcsType & A, const CrsType & A_crs, const typename CcsType::size_type m, const PermType & p, const PermType & q, const bool apat = false) inline
permute the matrix for asymmetric cases
Template Parameters
CcsType ccs storage for intermidiate matrix after matching
CrsType crs storage, see CRS
PermType permutation matrix, see BiPermMatrix
Parameters
[in] A input matrix after performing matching
[in] A_crs input matrix with crs type
[in] m leading block size that must no larger than size(A)
[in] p row permutation matrix
[in] q column permutation matrix
[in] apat if true, then compute default is false
Note
It's worth noting that p must be bi-directional mapping
If apat is true, then q must be bi-directional mapping
Definition at line 199 of file matching_scaling.hpp.
References hif::DATA_UNDEF.
defer_tiny_diags()
template<bool IsSymm, class CcsType , class CrsType , class PermType , class BufType > CcsType::size_type hif::internal::defer_tiny_diags (const CcsType & A, const CrsType & A_crs, const typename CcsType::size_type m0, PermType & p, PermType & q, BufType & work_p, BufType & work_q) inline
defer any zero diags to the end
Template Parameters
IsSymm if true, then assume a symmetric leading block
CcsType ccs storage for input matrix
CrsType crs storage for the input matrix
PermType permutation matrix, see BiPermMatrix
BufType buffer used to stored deferred entries
Parameters
[in] A input matrix
[in] A_crs input matrix of CRS storage
[in] m0 initial leading block size
[in,out] p row permutation matrix
[in,out] q column permutation matrix
[out] work_p workspace
[out] work_q workspace
Returns
actual leading block with no zero entries, <= m0
For asymmetric cases, where the whole matrix is stored, thus we need binary search to locate the diagonal entries. For symmetric cases, on the other side, since only the lower part is stored, we just need to test the first entry of each column.
Definition at line 99 of file matching_scaling.hpp.
degree_()
template<typename _Integer > int hif::rcm::detail::degree_ (const _Integer root, _Integer * xadj, const _Integer * adjncy, std::vector< bool > & mask, _Integer * deg, _Integer * ccsize, _Integer * ls) inline
Definition at line 142 of file rcm.hpp.
do_maching()
template<bool IsSymm, class CcsType , class CrsType , class ScalingArray , class PermType > std::pair< CCS<typename CcsType::value_type, typename CcsType::index_type>, typename CcsType::size_type> hif::do_maching (const CcsType & A, const CrsType & A_crs, const typename CcsType::size_type m0, const typename CcsType::size_type level, const Options & opts, ScalingArray & s, ScalingArray & t, PermType & p, PermType & q) inline
compute the matching for preprocessing
Template Parameters
IsSymm if true, then assume a symmetric leading block
CcsType ccs storage for intermidiate matrix after matching
ScalingArray scaling array for row and column, see Array
PermType permutation matrix, see BiPermMatrix
Parameters
[in] A input matrix in CCS order
[in] A_crs the CRS version of A
[in] m0 leading block size
[in] level current factorization level
[in] opts control parameters, see Options
[out] s row scaling vector
[out] t column scaling vector
[out] p row permutation vector
[out] q column permutation vector
Returns
A pair of CCS matrix in C-index and the actual leading block size, which is no larger than m0.
Definition at line 351 of file matching_scaling.hpp.
References hif_Options::beta, hif::DATA_UNDEF, hif::Timer< Clock, RepType >::finish(), hif::info(), hif_Options::pre_scale, hif_Options::reorder, hif::REORDER_OFF, hif::REORDER_RCM, hif::Timer< Clock, RepType >::start(), hif::Timer< Clock, RepType >::time(), and hif_Options::verbose.
do_preprocessing()
template<bool IsSymm, class CcsType , class CrsType , class ScalingArray , class PermType > CcsType::size_type hif::do_preprocessing (const CcsType & A, const CrsType & A_crs, const typename CcsType::size_type m0, const typename CcsType::size_type level, const Options & opt, ScalingArray & s, ScalingArray & t, PermType & p, PermType & q) inline
routine to perform preprocessing for improving the quality of input
Template Parameters
IsSymm if true, the assume the leading block is symmetric
CcsType input matrix type, see CCS
ScalingArray array type for scaling vectors, see Array
PermType permutation type, see BiPermMatrix
Parameters
[in] A input matrix
[in] A_crs CRS format of input A
[in] m0 leading block size
[in] level current factorization level
[in] opt control parameters
[out] s row scaling vector
[out] t column scaling vector
[out] p row permutation
[out] q column permutation
Returns
The actual leading block size, no larger than m0
Notice that, in general, the preprocessing involves two steps: 1) perform matching/scaling to improve the diagonal dominance and conditioning, and 2) perform reordering to improve the sparsity of LU decomposition.
Definition at line 68 of file driver.hpp.
References hif::error(), hif::Timer< Clock, RepType >::finish(), hif::info(), hif_Options::reorder, hif::REORDER_AMD, hif::REORDER_AUTO, hif::REORDER_NULL, hif::REORDER_OFF, hif::Timer< Clock, RepType >::start(), and hif::Timer< Clock, RepType >::time().
fix_poor_scaling()
template<class PermType , class ScalingArray > void hif::internal::fix_poor_scaling (const typename ScalingArray::size_type m0, const typename ScalingArray::size_type level, const PermType & p, const PermType & q, ScalingArray & s, ScalingArray & t, const double beta = 1e3) inline
fix poorly scaled row and column weights due to MC64
Template Parameters
PermType permutation matrix, see BiPermMatrix
ScalingArray scaling array type, see Array
Parameters
[in] m0 leading block size
[in] level current factorization level
[in] p row permutation matrix
[in] q column permutation matrix
[in,out] s row scaling
[in,out] t column scaling
[in] beta (optional) threshold for determining bad scaling factors
Definition at line 60 of file matching_scaling.hpp.
fnroot_()
template<typename _Integer > int hif::rcm::detail::fnroot_ (_Integer * root, const _Integer * xadj, const _Integer * adjncy, std::vector< bool > & mask, _Integer * nlvl, _Integer * xls, _Integer * ls) inline
Definition at line 102 of file rcm.hpp.
genrcm_()
template<typename _Integer > int hif::rcm::detail::genrcm_ (const _Integer neqns, _Integer * xadj, const _Integer * adjncy, _Integer * perm, std::vector< bool > & mask, _Integer * xls) inline
Definition at line 256 of file rcm.hpp.
iterative_scale()
template<bool IsSymm, class CrsType , class ScalingType > void hif::iterative_scale (CrsType & A, ScalingType & rs, ScalingType & cs, const double tol = 1e-10, const typename CrsType::size_type max_iters = 5, const bool ensure_fortran_index = true) inline
iterative scaling based on Jacobi operation
Template Parameters
IsSymm if true, then assume the input type is symmetric
CrsType crs matrix type, see CRS
ScalingType scaling array type, see Array
Parameters
[in,out] A input and output operator
[out] rs row scaling
[out] cs column scaling
[in] tol termination tolerance, default is 1e-10
[in] max_iters maximum number of iterations
[in] ensure_fortran_index if true (default), then the index values in B will be advanced by 1
References : D. Ruiz and B. Ucar, A Symmetry Preserving Algorithm for Matrix Scaling, SIAM J. MATRIX ANAL. APPL. 2014
Definition at line 270 of file a_priori_scaling.hpp.
iterative_scale_p()
template<bool IsSymm, class PermType , class CrsType , class ScalingType > void hif::iterative_scale_p (const PermType & p, CrsType & A, ScalingType & rs, ScalingType & cs, const double tol = 1e-10, const typename CrsType::size_type max_iters = 5, const bool ensure_fortran_index = true) inline
iterative scaling based on Jacobi operation
Template Parameters
IsSymm if true, then assume the input type is symmetric
PermType user-defined row permutation (or symmetric if IsSymm is true.)
ScalingType scaling array type, see Array
CrsType crs matrix type, see CRS
Parameters
[in] p user permutation with operator[] returns permutation
[in,out] A input and output operator
[out] rs row scaling
[out] cs column scaling
[in] tol termination tolerance, default is 1e-10
[in] max_iters maximum number of iterations
[in] ensure_fortran_index if true (default), then the index values in B will be advanced by 1
References : D. Ruiz and B. Ucar, A Symmetry Preserving Algorithm for Matrix Scaling, SIAM J. MATRIX ANAL. APPL. 2014
Definition at line 161 of file a_priori_scaling.hpp.
kernel()
template<typename _Integer , typename _Real > void hif::eql::detail::kernel (_Integer n, const _Integer * ip, const _Integer * irn, const _Real * a, _Integer * iperm, _Integer * num, _Integer * jperm, _Integer * out, _Integer * pr, _Integer * q, _Integer * l, _Real * u, _Real * d__) inline
Definition at line 380 of file equilibrate.hpp.
kernel_()
template<typename _Integer , typename _Real > void hif::eql::detail::kernel_ (const _Integer j, const _Integer n, _Integer * q, _Real * d__, _Integer * l, const bool flag) inline
Definition at line 162 of file equilibrate.hpp.
kernel__()
template<typename _Integer , typename _Real > void hif::eql::detail::kernel__ (_Integer * ql, const _Integer n, _Integer * q, _Real * d__, _Integer * l, const bool flag) inline
Definition at line 200 of file equilibrate.hpp.
kernel___()
template<typename _Integer , typename _Real > void hif::eql::detail::kernel___ (_Integer * pos_, _Integer * qlen, const _Integer n, _Integer * q, _Real * d__, _Integer * l, const bool flag) inline
Definition at line 256 of file equilibrate.hpp.
rcm_()
template<typename _Integer > int hif::rcm::detail::rcm_ (const _Integer root, _Integer * xadj, const _Integer * adjncy, std::vector< bool > & mask, _Integer * perm, _Integer * ccsize, _Integer * deg) inline
Definition at line 192 of file rcm.hpp.
rootls_()
template<typename _Integer > int hif::rcm::detail::rootls_ (const _Integer root, const _Integer * xadj, const _Integer * adjncy, std::vector< bool > & mask, _Integer * nlvl, _Integer * xls, _Integer * ls) inline
Definition at line 56 of file rcm.hpp.
run_amd()
template<bool IsSymm, class CcsType > Array<typename CcsType::index_type> hif::run_amd (const CcsType & B, const Options & opt) inline
apply approximated mimimum degree ordering
Template Parameters
IsSymm if true, then assume symmetric pattern input
CcsType ccs sparse storage, see CCS
Parameters
[in] B matrix with pattern given
[in] opt options
Returns
symmetric permutation so that PAP' satisties AMD property
Definition at line 53 of file reordering.hpp.
References hif::DATA_UNDEF, and hif::error().
run_rcm()
template<class CcsType > CcsType::iarray_type hif::run_rcm (const CcsType & B, const Options & opt) inline
apply reversed Cuthill-Mckee ordering
Template Parameters
CcsType ccs sparse storage, see CCS
Parameters
[in] B matrix with pattern given
[in] opt options
Returns
symmetric permutation so that PAP' satisties RCM property
Definition at line 104 of file reordering.hpp.
scale_extreme_values()
template<bool IsSymm, class CrsType , class ScalingType > void hif::scale_extreme_values (CrsType & B, ScalingType & rs, ScalingType & cs, const bool ensure_fortran_index = true) inline
scale based on extreme values, do it asynchronously
Template Parameters
IsSymm if true, then assume the input type is symmetric
CrsType crs matrix type, see CRS
ScalingType scaling array type, see Array
Parameters
[in,out] B input and output matrix
[out] rs row scaling
[out] cs column scaling
[in] ensure_fortran_index if true (default), then the index values in B will be advanced by 1
This function performs a single step of asynchronous scaling (Gauss-Seidel) scaling, thus the row will be scaled before column scaling computes the local extreme values.
Definition at line 86 of file a_priori_scaling.hpp.
scale_eye()
template<class CrsType , class ScalingType > void hif::scale_eye (CrsType & B, ScalingType & rs, ScalingType & cs, const bool ensure_fortran_index = true) inline
do not perform a priori scaling
Template Parameters
CrsType crs matrix type, see CRS
ScalingType scaling array type, see Array
Parameters
[in,out] B input and output matrix
[out] rs row scaling
[out] cs column scaling
[in] ensure_fortran_index if true (default), then the index values in B will be advanced by 1
Notice that rs and cs will be set to be 1.
Definition at line 57 of file a_priori_scaling.hpp.
set_default_pars()
template<typename _Integer > void hif::eql::detail::set_default_pars (_Integer * pars) inline
Definition at line 53 of file equilibrate.hpp.