HIFIR: Algorithms
Algorithms
Modules
Crout Update
Dynamic Deferring
Inverse-based Threshold
Scalability-oriented Threshold
Schur Complements
Small Scale Solver
Preconditioner Solver
Multilevel Factorization
Iterative Refinement
Functions
template<class CsType , class IArray , class OArray , typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type hif::mt::multiply_nt (const CsType &A, const IArray &x, OArray &y)
matrix vector in parallel with openmp
template<class CsType , class Vx , class Vy , typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type hif::mt::multiply_nt_low (const CsType &A, const Vx *x, Vy *y)
matrix vector in parallel with openmp
template<class CsType , class InType , class OutType , std::size_t Nrhs, typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type hif::mt::multiply_mrhs_nt (const CsType &A, const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y)
matrix vector in parallel with openmp for multiple RHS
template<std::size_t Nrhs, class CsType , class Vx , class Vy , typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type hif::mt::multiply_mrhs_nt_low (const CsType &A, const Vx *x, Vy *y)
matrix vector in parallel with openmp for multiple RHS
template<class CsType , class IArray , class OArray , typename T = void>
void hif::multiply (const CsType &A, const IArray &x, OArray &y, const bool tran=false)
matrix-vector product
template<class IArray , class OArray , typename T = void>
void hif::multiply (const std::function< void(const void *, const typename IArray::size_type, const char, void *, const char, const bool)> &Afunc, const IArray &x, OArray &y, const bool tran=false)
matrix-vector product with std::function
Detailed Description
Function Documentation
multiply() [1/2]
template<class CsType , class IArray , class OArray , typename T = void> void hif::multiply (const CsType & A, const IArray & x, OArray & y, const bool tran = false) inline
matrix-vector product
Template Parameters
CsType compressed storage type, e.g., CRS
IArray input array type
OArray output array type
Parameters
[in] A input matrix
[in] x input array
[out] y output array
[in] tran (optional) transpose/Hermitian flag, default is false
Definition at line 52 of file mv_helper.hpp.
multiply() [2/2]
template<class IArray , class OArray , typename T = void> void hif::multiply (const std::function< void(const void *, const typename IArray::size_type, const char, void *, const char, const bool)> & Afunc, const IArray & x, OArray & y, const bool tran = false) inline
matrix-vector product with std::function
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] Afunc input matrix-like operator
[in] x input array
[out] y output array
[in] tran (optional) transpose/Hermitian flag, default is false
Definition at line 65 of file mv_helper.hpp.
multiply_mrhs_nt()
template<class CsType , class InType , class OutType , std::size_t Nrhs, typename T = void> std::enable_if<CsType::ROW_MAJOR, T>::type hif::mt::multiply_mrhs_nt (const CsType & A, const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y) inline
matrix vector in parallel with openmp for multiple RHS
Template Parameters
CsType compressed storage type, e.g. CRS
InType input data type
OutType output data type
Nrhs number of RHS
Parameters
[in] A input matrix
[in] x input array
[out] y output array
Definition at line 127 of file mt_mv.hpp.
References hif::mt::get_nthreads(), and hif::mt::get_thread().
multiply_mrhs_nt_low()
template<std::size_t Nrhs, class CsType , class Vx , class Vy , typename T = void> std::enable_if<CsType::ROW_MAJOR, T>::type hif::mt::multiply_mrhs_nt_low (const CsType & A, const Vx * x, Vy * y) inline
matrix vector in parallel with openmp for multiple RHS
Template Parameters
Nrhs number of RHS
CsType compressed storage type, e.g. CRS
Vx other value type for x
Vy other value type for y
Parameters
[in] A input matrix
[in] x input array
[out] y output array
Note
Sizes must match
Definition at line 157 of file mt_mv.hpp.
References hif::mt::get_nthreads(), and hif::mt::get_thread().
multiply_nt()
template<class CsType , class IArray , class OArray , typename T = void> std::enable_if<CsType::ROW_MAJOR, T>::type hif::mt::multiply_nt (const CsType & A, const IArray & x, OArray & y) inline
matrix vector in parallel with openmp
Template Parameters
CsType compressed storage type, e.g. CRS
IArray input array type
OArray output array type
Parameters
[in] A input matrix
[in] x input array
[out] y output array
Note
Sizes must match
Definition at line 58 of file mt_mv.hpp.
References hif::mt::get_nthreads(), and hif::mt::get_thread().
multiply_nt_low()
template<class CsType , class Vx , class Vy , typename T = void> std::enable_if<CsType::ROW_MAJOR, T>::type hif::mt::multiply_nt_low (const CsType & A, const Vx * x, Vy * y) inline
matrix vector in parallel with openmp
Template Parameters
CsType compressed storage type, e.g. CRS
Vx other value type for x
Vy other value type for y
Parameters
[in] A input matrix
[in] x input array
[out] y output array
Note
Sizes must match
Definition at line 84 of file mt_mv.hpp.
References hif::mt::get_nthreads(), and hif::mt::get_thread().