HIFIR: Data Structures
Data Structures
Classes
class hif::Array< T >
Core data structure used in compressed storage.
class hif::PermMatrix< IndexType >
permutation matrix defined as the P(i) entry in original matrix is the i-th entry in the permutated one
class hif::BiPermMatrix< IndexType >
This is the bi-directional version, i.e. the inverse mapping is avail.
class hif::internal::AugmentedCore< IndexType, IndPtrType >
A group of forward link lists for CompressedStorage.
class hif::AugCRS< CrsType >
Augmented CRS data structure.
class hif::AugCCS< CcsType >
Augmented CCS data structure.
class hif::internal::CompressedStorage< ValueType, IndexType, IndPtrType >
Core of the compressed storage, including data and interfaces.
class hif::CRS< ValueType, IndexType, IndPtrType >
Compressed Row Storage (CRS) format for sparse matrices.
class hif::CCS< ValueType, IndexType, IndPtrType >
Compressed Column Storage (CCS) format for sparse matrices.
class hif::internal::StrideIterator< T >
Row-wise iterator.
class hif::DenseMatrix< ValueType >
Dense storage.
class hif::IndexValueArray< ValueType, IndexType >
class hif::SparseVector< ValueType, IndexType >
Enumerations
enum : unsigned char { hif::DATA_UNDEF = 0, hif::DATA_WRAP, hif::DATA_OWN }
Functions
template<class T >
void hif::steal_array_ownership (Array< T > &arr, typename Array< T >::pointer &data, typename Array< T >::size_type &size, typename Array< T >::size_type &cap)
try steal the array data ownership
template<class ValueType >
Array< ValueType > hif::wrap_array (const typename Array< ValueType >::size_type n, ValueType *data)
wrap mutable external data
template<class ValueType >
Array< ValueType > hif::wrap_const_array (const typename Array< ValueType >::size_type n, const ValueType *data)
wrap immutable external data
template<class ValueArray , class IndexArray , class IndPtrArray >
void hif::internal::convert_storage (const IndPtrArray &i_ind_start, const IndexArray &i_indices, const ValueArray &i_vals, IndPtrArray &o_ind_start, IndexArray &o_indices, ValueArray &o_vals)
convert from one type to another type, e.g. ccs->crs
template<class ValueType , class IndexType , class IndPtrType >
CRS< ValueType, IndexType > hif::wrap_const_crs (const typename CRS< ValueType, IndexType, IndPtrType >::size_type nrows, const typename CRS< ValueType, IndexType, IndPtrType >::size_type ncols, const IndPtrType *row_start, const IndexType *col_ind, const ValueType *vals, bool check=true)
wrap user data for CRS
template<class ValueType , class IndexType , class IndPtrType >
CCS< ValueType, IndexType, IndPtrType > hif::wrap_const_ccs (const typename CCS< ValueType, IndexType, IndPtrType >::size_type nrows, const typename CCS< ValueType, IndexType, IndPtrType >::size_type ncols, const IndPtrType *col_start, const IndexType *row_ind, const ValueType *vals, bool check=true)
wrap user data for CCS
template<class ExportCSType , class CSCopiedType >
void hif::export_compressed_data (const CSCopiedType &A, typename ExportCSType::ippointer ind_start, typename ExportCSType::ipointer indices, typename ExportCSType::pointer vals)
Export data.
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum : unsigned char
Enumerator
DATA_UNDEF
data type undefined
DATA_WRAP
wrapping external data
DATA_OWN
data type owned
Definition at line 59 of file Array.hpp.
Function Documentation
convert_storage()
template<class ValueArray , class IndexArray , class IndPtrArray > void hif::internal::convert_storage (const IndPtrArray & i_ind_start, const IndexArray & i_indices, const ValueArray & i_vals, IndPtrArray & o_ind_start, IndexArray & o_indices, ValueArray & o_vals) inline
convert from one type to another type, e.g. ccs->crs
Template Parameters
ValueArray numerical value array type
IndexArray index array type
IndPtrArray index pointer array
Parameters
[in] i_ind_start input index start array
[in] i_indices input index array
[in] i_vals input value array
[out] o_ind_start output index start array
[out] o_indices output index array
[out] o_vals output values
Warning
o_indices should be initialized properly with value 0 or 1
Both o_{indices,vals} should be allocated properly
Note
Work with both Array and std::vector
Definition at line 749 of file CompressedStorage.hpp.
References hif::error().
export_compressed_data()
template<class ExportCSType , class CSCopiedType > void hif::export_compressed_data (const CSCopiedType & A, typename ExportCSType::ippointer ind_start, typename ExportCSType::ipointer indices, typename ExportCSType::pointer vals) inline
Export data.
Template Parameters
ExportCSType compressed format for exporting data
CSCopiedType compressed format for being copied
Parameters
[in] A sparse matrix being copied
[out] ind_start starting position array in compressed format
[out] indices index array in compressed format
[out] vals value array in compressed format, same length as indices
Warning
The user must query the sizes and allocate the buffers beforehand
Definition at line 2708 of file CompressedStorage.hpp.
steal_array_ownership()
template<class T > void hif::steal_array_ownership (Array< T > & arr, typename Array< T >::pointer & data, typename Array< T >::size_type & size, typename Array< T >::size_type & cap) inline
try steal the array data ownership
Template Parameters
T value type
Parameters
[in,out] arr input and output array
[out] data pointer to the internal database
[out] size array size
[out] cap array capacity
Note
If arr can't be stole, nullptr is assigned to data
Warning
Only works for DATA_OWN status
Manually calling delete[] may be needed
Not designed using in MT
Definition at line 479 of file Array.hpp.
References hif::DATA_OWN, and hif::DATA_UNDEF.
wrap_array()
template<class ValueType > Array<ValueType> hif::wrap_array (const typename Array< ValueType >::size_type n, ValueType * data) inline
wrap mutable external data
Template Parameters
ValueType data type, e.g., double
Parameters
[in] n length of the array
[in] data pointer to the external data
See also
wrap_const_array
Definition at line 506 of file Array.hpp.
wrap_const_array()
template<class ValueType > Array<ValueType> hif::wrap_const_array (const typename Array< ValueType >::size_type n, const ValueType * data) inline
wrap immutable external data
Template Parameters
ValueType data type, e.g., double
Parameters
[in] n length of the array
[in] data pointer to the external data
See also
wrap_array
Definition at line 517 of file Array.hpp.
wrap_const_ccs()
template<class ValueType , class IndexType , class IndPtrType > CCS<ValueType, IndexType, IndPtrType> hif::wrap_const_ccs (const typename CCS< ValueType, IndexType, IndPtrType >::size_type nrows, const typename CCS< ValueType, IndexType, IndPtrType >::size_type ncols, const IndPtrType * col_start, const IndexType * row_ind, const ValueType * vals, bool check = true) inline
wrap user data for CCS
Template Parameters
ValueType value type, e.g. double
IndexType index type, e.g. int
IndPtrType index pointer type, default is std::ptrdiff_t
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] col_start data for column pointer, size of ncols + 1
[in] row_ind column indices
[in] vals numerical data
[in] check if true (default), then perform validation checking
Returns
a CRS matrix wrapped around user data.
Warning
It's the user's responsibility to maintain the external data
Definition at line 2656 of file CompressedStorage.hpp.
References hif::error(), and hif::warning().
wrap_const_crs()
template<class ValueType , class IndexType , class IndPtrType > CRS<ValueType, IndexType> hif::wrap_const_crs (const typename CRS< ValueType, IndexType, IndPtrType >::size_type nrows, const typename CRS< ValueType, IndexType, IndPtrType >::size_type ncols, const IndPtrType * row_start, const IndexType * col_ind, const ValueType * vals, bool check = true) inline
wrap user data for CRS
Template Parameters
ValueType value type, e.g. double
IndexType index type, e.g. int
IndPtrType index pointer type, default is std::ptrdiff_t
Parameters
[in] nrows number of rows
[in] ncols number of columns
[in] row_start data for row pointer, size of nrows + 1
[in] col_ind column indices
[in] vals numerical data
[in] check if true (default), then perform validation checking
Returns
a CRS matrix wrapped around user data.
Warning
It's the user's responsibility to maintain the external data
Definition at line 1757 of file CompressedStorage.hpp.
References hif::error(), and hif::warning().