HIFIR: Dynamic Deferring
Dynamic Deferring
Algorithms
Functions
template<class CsType , class IndPtrArray , class ListArray >
void hif::Crout::defer_entry (const size_type to_idx, const IndPtrArray &start, CsType &T, ListArray &list) const
defer an secondary entry
template<class CcsType , class IndPtrArray , class ListArray >
void hif::Crout::symm_defer_l (const size_type to_idx, const IndPtrArray &L_start, CcsType &L, ListArray &L_list, IndPtrArray &L_offsets) const
for symmetric leading block, we need to fix the offset positions while we do deferring
template<class CsType >
void hif::PivotCrout::defer_entry (const size_type to_idx, CsType &T) const
defer an secondary entry, i.e., rows in CCS and columns in CRS
Detailed Description
Function Documentation
defer_entry() [1/2]
template<class CsType > void hif::PivotCrout::defer_entry (const size_type to_idx, CsType & T) const inline
defer an secondary entry, i.e., rows in CCS and columns in CRS
Template Parameters
CsType either AugCRS (U) or AugCCS (L)
Parameters
[in] to_idx deferred destination
[in,out] T lower or upper factors
Definition at line 435 of file PivotCrout.hpp.
References hif::Crout::deferred_step().
defer_entry() [2/2]
template<class CsType , class IndPtrArray , class ListArray > void hif::Crout::defer_entry (const size_type to_idx, const IndPtrArray & start, CsType & T, ListArray & list) const inline
defer an secondary entry
Template Parameters
CsType either CRS (U) or CCS (L)
IndPtrArray index pointer array
ListArray "linked-list" array, see Array
Parameters
[in] to_idx deferred destination
[in] start starting positions
[in,out] T lower or upper factors
[in,out] list linked list of primary indices
Definition at line 681 of file Crout.hpp.
References hif::Crout::_step, and hif::Crout::deferred_step().
symm_defer_l()
template<class CcsType , class IndPtrArray , class ListArray > void hif::Crout::symm_defer_l (const size_type to_idx, const IndPtrArray & L_start, CcsType & L, ListArray & L_list, IndPtrArray & L_offsets) const inline
for symmetric leading block, we need to fix the offset positions while we do deferring
Template Parameters
CcsType CCS storage type for L
IndPtrArray index pointer array
ListArray "linked-list" array, see Array
Parameters
[in] to_idx deferred destination
[in] L_start starting positions
[in,out] L lower factor L
[in,out] L_list linked list of column indices
[out] L_offsets offsets of asymmetric potions
Definition at line 721 of file Crout.hpp.
References hif::Crout::_step, and hif::Crout::deferred_step().