HIFIR: HIF User Interfaces
HIF User Interfaces
Modules
Preprocessor macros
Classes
class hif::HIF< ValueType, IndexType, UserDenseFactor >
struct hif_Options
POD parameter controls.
class hif::NspFilter
filter attached to HIF for filtering null space componentsFlexible design of null space components filter. The default mode is constant filter, i.e., there is a constant mode in the system. Two ways to customize the filter, 1) override the NspFilter::user_filter function or 2) pass in a callback function.
Macros
#define HIF_GLOBAL_VERSION 0
HIF global version.
#define HIF_MAJOR_VERSION 1
HIF major version.
#define HIF_MINOR_VERSION 0
HIF minor version.
Typedefs
typedef HIF< double, int > hif::DefaultHIF
default HIF with double as value type and int as index
typedef struct hif_Options hif_Options
type wrapper
typedef struct hif_Options hif_Params
alias of hif_Options
typedef hif_Options hif::Options
type wrapper
typedef Options hif::Params
alias of Options
typedef std::shared_ptr< NspFilter > hif::NspFilterPtr
shared pointer of NspFilter, this should be used in user code
Enumerations
enum {
HIF_VERBOSE_NONE = 0, HIF_VERBOSE_INFO = 1, HIF_VERBOSE_PRE = HIF_VERBOSE_INFO << 1, HIF_VERBOSE_FAC = HIF_VERBOSE_PRE << 1,
HIF_VERBOSE_PRE_TIME = HIF_VERBOSE_FAC << 1, HIF_VERBOSE_MEM = HIF_VERBOSE_PRE_TIME << 1, HIF_VERBOSE_INFO2 = HIF_VERBOSE_MEM << 1
}
the verbose level for progress report
enum {
HIF_REORDER_OFF = 0, HIF_REORDER_AUTO = 1, HIF_REORDER_AMD = 2, HIF_REORDER_RCM = 3,
HIF_REORDER_NULL = 4
}
reordering method
enum { HIF_PIVOTING_OFF = 0, HIF_PIVOTING_ON = 1, HIF_PIVOTING_AUTO = 2 }
pivoting flag
enum : int {
hif::VERBOSE_NONE = ::HIF_VERBOSE_NONE, hif::VERBOSE_INFO = ::HIF_VERBOSE_INFO, hif::VERBOSE_PRE = ::HIF_VERBOSE_PRE, hif::VERBOSE_FAC = ::HIF_VERBOSE_FAC,
hif::VERBOSE_PRE_TIME = ::HIF_VERBOSE_PRE_TIME, hif::VERBOSE_MEM = ::HIF_VERBOSE_MEM, hif::VERBOSE_INFO2 = ::HIF_VERBOSE_INFO2
}
enum wrapper
enum : int {
hif::REORDER_OFF = ::HIF_REORDER_OFF, hif::REORDER_AUTO = ::HIF_REORDER_AUTO, hif::REORDER_AMD = ::HIF_REORDER_AMD, hif::REORDER_RCM = ::HIF_REORDER_RCM,
hif::REORDER_NULL = ::HIF_REORDER_NULL
}
enum wrapper for reordering methods
enum : int { hif::PIVOTING_OFF = ::HIF_PIVOTING_OFF, hif::PIVOTING_ON = ::HIF_PIVOTING_ON, hif::PIVOTING_AUTO = ::HIF_PIVOTING_AUTO }
enum wrapper for pivoting
Functions
template<class... Args>
NspFilterPtr hif::create_nsp_filter (Args &&... args)
construct NspFilterPtr
static hif_Options hif_get_default_options (void)
get the default controls
static hif_Params hif_get_default_params (void)
alias of hif_get_default_options
static void hif_enable_verbose (const int flag, hif_Options *opts)
enable verbose flag
static const char * hif_get_reorder_name (const hif_Options *opt)
get the string tag for reordering methods
std::string hif::get_reorder_name (const Options &opt)
get the reordering method name
void hif::enable_verbose (const int flag, Options &opts)
enable verbose flags
std::string hif::get_verbose (const Options &opt)
get the verbose name
Options hif::get_default_options ()
get the default configuration
Params hif::get_default_params ()
alias of get_default_options
std::string hif::opt_repr (const Options &opt)
represent an option control with C++ string
template<typename T >
bool hif::set_option_attr (const std::string &attr, const T v, Options &opt)
set Options attribute value from key value pairs
template<typename T >
bool hif::set_param_attr (const std::string &attr, const T v, Options &opt)
Set the param attributes/values.
template<class InStream >
InStream & operator>> (InStream &in_str, hif::Options &opt)
read control parameters from a standard input streamer
std::tuple< bool, bool, bool, bool, std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t > hif::query_info_bin (const char *filename)
query information of a binary file
std::tuple< bool, bool, bool, bool, std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t > hif::query_info_ascii (const char *filename)
query information of an ASCII file
std::string hif::version ()
get the version string representation during runtime
Variables
static const Params hif::DEFAULT_PARAMS = get_default_params()
global default parameters
Detailed Description
Macro Definition Documentation
HIF_GLOBAL_VERSION
#define HIF_GLOBAL_VERSION 0
HIF global version.
Definition at line 46 of file version.h.
HIF_MAJOR_VERSION
#define HIF_MAJOR_VERSION 1
HIF major version.
Definition at line 47 of file version.h.
HIF_MINOR_VERSION
#define HIF_MINOR_VERSION 0
HIF minor version.
Definition at line 48 of file version.h.
Typedef Documentation
DefaultHIF
hif::DefaultHIF
default HIF with double as value type and int as index
Definition at line 575 of file builder.hpp.
hif_Options
hif_Options
type wrapper
Definition at line 122 of file Options.h.
hif_Params
hif_Params
alias of hif_Options
Definition at line 128 of file Options.h.
NspFilterPtr
hif::NspFilterPtr
shared pointer of NspFilter, this should be used in user code
Definition at line 185 of file NspFilter.hpp.
Options
hif::Options
type wrapper
Definition at line 272 of file Options.h.
Params
hif::Params
alias of Options
Definition at line 278 of file Options.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
the verbose level for progress report
Enumerator
HIF_VERBOSE_NONE
mute
HIF_VERBOSE_INFO
general information
HIF_VERBOSE_PRE
preprocessing
HIF_VERBOSE_FAC
factorization update
HIF_VERBOSE_PRE_TIME
HIF_VERBOSE_MEM
pre time memory debug
HIF_VERBOSE_INFO2
more detailed than info
Definition at line 46 of file Options.h.
anonymous enum
anonymous enum
reordering method
Enumerator
HIF_REORDER_OFF
turn reordering off
HIF_REORDER_AUTO
use automaticaly reordering (default)
HIF_REORDER_AMD
use AMD ordering
HIF_REORDER_RCM
use RCM ordering (require BGL)
HIF_REORDER_NULL
ordering Null flag (internal checking)
Definition at line 59 of file Options.h.
anonymous enum
anonymous enum
pivoting flag
Enumerator
HIF_PIVOTING_OFF
perform deferring-only factorization
HIF_PIVOTING_ON
perform deferred Crout factor with pivoting
HIF_PIVOTING_AUTO
auto kernel (hybridizing between 0 and 1)
Definition at line 70 of file Options.h.
anonymous enum
anonymous enum : int
enum wrapper
Note
The prefix HIF is dropped
Enumerator
VERBOSE_NONE
mute
VERBOSE_INFO
general information
VERBOSE_PRE
preprocessing
VERBOSE_FAC
factorization update
VERBOSE_PRE_TIME
pre time
VERBOSE_MEM
memory debug
VERBOSE_INFO2
more detailed than info
Definition at line 235 of file Options.h.
anonymous enum
anonymous enum : int
enum wrapper for reordering methods
Note
The prefix HIF is dropped
Enumerator
REORDER_OFF
turn reordering off
REORDER_AUTO
use automaticaly reordering (default)
REORDER_AMD
use AMD ordering
REORDER_RCM
use RCM ordering (require BGL)
REORDER_NULL
ordering Null flag
Definition at line 249 of file Options.h.
anonymous enum
anonymous enum : int
enum wrapper for pivoting
Note
The prefix HIF is dropped
Enumerator
PIVOTING_OFF
PIVOTING_ON
PIVOTING_AUTO
Definition at line 262 of file Options.h.
Function Documentation
create_nsp_filter()
template<class... Args> NspFilterPtr hif::create_nsp_filter (Args &&... args) inline
construct NspFilterPtr
Definition at line 190 of file NspFilter.hpp.
enable_verbose()
void hif::enable_verbose (const int flag, Options & opts) inline
enable verbose flags
Parameters
[in] flag verbose options
[in,out] opts options
Examples:
demo_verbose.cpp.
Definition at line 292 of file Options.h.
References hif_enable_verbose().
get_default_options()
Options hif::get_default_options () inline
get the default configuration
Definition at line 304 of file Options.h.
References hif_get_default_options().
get_default_params()
Params hif::get_default_params () inline
alias of get_default_options
Definition at line 309 of file Options.h.
References hif_get_default_params().
get_reorder_name()
std::string hif::get_reorder_name (const Options & opt) inline
get the reordering method name
Definition at line 283 of file Options.h.
References hif_get_reorder_name().
get_verbose()
std::string hif::get_verbose (const Options & opt) inline
get the verbose name
Definition at line 596 of file Options.h.
References hif_Options::verbose, and hif::VERBOSE_NONE.
hif_enable_verbose()
static void hif_enable_verbose (const int flag, hif_Options * opts) static
enable verbose flag
Parameters
[in] flag verbose flag
[in,out] opts options
Definition at line 177 of file Options.h.
References HIF_VERBOSE_NONE, and hif_Options::verbose.
Referenced by hif::enable_verbose().
hif_get_default_options()
static hif_Options hif_get_default_options (void) static
get the default controls
Note
See the values of attributes in parentheses
Definition at line 134 of file Options.h.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::beta, hif_Options::c_d, hif_Options::c_h, hif_Options::check, hif_Options::dense_thres, hif_Options::fat_schur_1st, hif_Options::gamma, HIF_PIVOTING_AUTO, HIF_REORDER_AMD, HIF_VERBOSE_INFO, hif_Options::is_symm, hif_Options::kappa, hif_Options::kappa_d, hif_Options::mumps_blr, hif_Options::N, hif_Options::no_pre, hif_Options::nzp_thres, hif_Options::pivot, hif_Options::pre_scale, hif_Options::reorder, hif_Options::rf_par, hif_Options::rho, hif_Options::rrqr_cond, hif_Options::spd, hif_Options::symm_pre_lvls, hif_Options::tau_L, hif_Options::tau_U, hif_Options::threads, and hif_Options::verbose.
Referenced by hif::get_default_options(), and hif_get_default_params().
hif_get_default_params()
static hif_Params hif_get_default_params (void) static
alias of hif_get_default_options
Definition at line 168 of file Options.h.
References hif_get_default_options().
Referenced by hif::get_default_params().
hif_get_reorder_name()
static const char* hif_get_reorder_name (const hif_Options * opt) static
get the string tag for reordering methods
Parameters
[in] opt options
Returns
C-string of the method name
Definition at line 191 of file Options.h.
References HIF_REORDER_AMD, HIF_REORDER_AUTO, HIF_REORDER_OFF, HIF_REORDER_RCM, and hif_Options::reorder.
Referenced by hif::get_reorder_name().
operator>>()
template<class InStream > InStream& operator>> (InStream & in_str, hif::Options & opt) inline
read control parameters from a standard input streamer
Template Parameters
InStream input streamer, i.e. with input operator
Parameters
[in,out] in_str input streamer, e.g. std::cin
[out] opt control parameters
Returns
reference to in_str to enable chain reaction
Note
Read data in sequential order with default separators
Definition at line 564 of file Options.h.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::beta, hif_Options::c_d, hif_Options::c_h, hif_Options::check, hif_Options::dense_thres, hif_Options::fat_schur_1st, hif_Options::gamma, hif_Options::is_symm, hif_Options::kappa, hif_Options::kappa_d, hif_Options::mumps_blr, hif_Options::N, hif_Options::no_pre, hif_Options::nzp_thres, hif_Options::pre_scale, hif_Options::reorder, hif_Options::rf_par, hif_Options::rho, hif_Options::rrqr_cond, hif_Options::spd, hif_Options::symm_pre_lvls, hif_Options::tau_L, hif_Options::tau_U, hif_Options::threads, and hif_Options::verbose.
opt_repr()
std::string hif::opt_repr (const Options & opt) inline
represent an option control with C++ string
Parameters
[in] opt input option controls
Returns
string representation of opt
Definition at line 322 of file Options.h.
query_info_ascii()
std::tuple<bool, bool, bool, bool, std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t> hif::query_info_ascii (const char * filename) inline
query information of an ASCII file
Parameters
[in] filename binary filename
Returns
tuple of CRS/CCS order, C-index, double/float, is real, nrows, ncols, nnz, m
See also
query_info_bin
Definition at line 769 of file io.hpp.
References hif::error().
query_info_bin()
std::tuple<bool, bool, bool, bool, std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t> hif::query_info_bin (const char * filename) inline
query information of a binary file
Parameters
[in] filename binary filename
Returns
tuple of CRS/CCS order, C-index, double/float, is real, nrows, ncols, nnz, m
See also
query_info_ascii
Definition at line 380 of file io.hpp.
References hif::error(), hif::internal::is_little_endian(), hif::internal::read_general_info(), and hif::internal::read_matrix_sizes().
set_option_attr()
template<typename T > bool hif::set_option_attr (const std::string & attr, const T v, Options & opt) inline
set Options attribute value from key value pairs
Template Parameters
T value type, either double or int
Parameters
[in] attr attribute/member name
[in] v value
[out] opt output options
This function can be handy while initialing option parameters from string values. Notice that the keys (string values) are the same as the attribute variable names.
Definition at line 445 of file Options.h.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::beta, hif_Options::c_d, hif_Options::c_h, hif_Options::check, hif_Options::dense_thres, hif_Options::fat_schur_1st, hif_Options::gamma, hif_Options::is_symm, hif_Options::kappa, hif_Options::kappa_d, hif_Options::mumps_blr, hif_Options::N, hif_Options::no_pre, hif_Options::nzp_thres, hif_Options::pivot, hif_Options::pre_scale, hif_Options::reorder, hif_Options::rf_par, hif_Options::rho, hif_Options::rrqr_cond, hif_Options::spd, hif_Options::symm_pre_lvls, hif_Options::tau_L, hif_Options::tau_U, hif_Options::threads, and hif_Options::verbose.
set_param_attr()
template<typename T > bool hif::set_param_attr (const std::string & attr, const T v, Options & opt) inline
Set the param attributes/values.
Note
Alias of set_option_attr
Definition at line 544 of file Options.h.
version()
std::string hif::version () inline
get the version string representation during runtime
Returns
string representation of version
Definition at line 52 of file hifir.hpp.
Variable Documentation
DEFAULT_PARAMS
hif::DEFAULT_PARAMS = get_default_params() static
global default parameters
Examples:
demo_fgmres.cpp, demo_fgmres_sparsifier.cpp, demo_gmreshif.cpp, demo_params.cpp, demo_sparsifier.cpp, and demo_verbose.cpp.
Definition at line 315 of file Options.h.