HIFIR: File I/O
File I/O
Utilities
Functions
bool hif::internal::is_little_endian ()
check if the os is litter endian
constexpr std::size_t hif::internal::get_word_size ()
check the word size
template<class InStream >
std::tuple< bool, std::size_t, std::size_t, bool, bool, bool, bool > hif::internal::read_general_info (InStream &i_str)
read the general information
template<class InStream >
std::tuple< std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t > hif::internal::read_matrix_sizes (InStream &i_str)
read the matrix size information
template<class InStream >
void hif::internal::read_matrix_data_attrs (InStream &i_str, const std::size_t int_size, const std::size_t real_size, const std::uint64_t start_size, const std::uint64_t nnz, char *ind_start, char *indices, char *vals)
read matrix data attributes
template<class OutStream >
void hif::internal::write_general_info (OutStream &o_str, const std::size_t int_size, const bool is_row, const bool is_c, const bool is_double, const bool is_real)
write general information
template<class OutStream >
void hif::internal::write_matrix_sizes (OutStream &o_str, const std::uint64_t row, const std::uint64_t col, const std::uint64_t nnz, const std::uint64_t m)
write matrix size information
template<class OutStream >
void hif::internal::write_matrix_data_attrs (OutStream &o_str, const std::size_t int_size, const std::size_t real_size, const std::uint64_t start_size, const std::uint64_t nnz, const void *ind_start, const void *indices, const void *vals)
write matrix data attributes
template<class CsType >
std::enable_if< CsType::ROW_MAJOR >::type hif::write_bin (const char *filename, const CsType &A, const std::uint64_t m)
write a CRS matrix
template<class CsType , typename T = std::uint64_t>
std::enable_if<!CsType::ROW_MAJOR, T >::type hif::read_bin (const char *filename, CsType &A)
read data from file to a CCS matrix
template<bool IsRowMajor, class IndexArray , class ValueArray >
void hif::write_ascii (const char *fname, const IndexArray &ind_start, const typename IndexArray::size_type other_size, const IndexArray &indices, const ValueArray &vals, const typename IndexArray::size_type m)
write to ASCII file
template<class IndexArray , class ValueArray >
std::tuple< bool, bool, char, std::size_t, std::size_t, std::size_t, std::size_t > hif::read_ascii (const char *fname, IndexArray &ind_start, IndexArray &indices, ValueArray &vals)
read data from ASCII file
template<int TypeID, bool IsReal, class IndexType , class ValueType >
void hif::internal::mm_read_sparse_data (std::FILE *f, const std::size_t nnz, Array< IndexType > &rows, Array< IndexType > &cols, Array< ValueType > &vals)
Internal routine to read sparse data.
template<bool IsReal, class ValueType >
void hif::internal::mm_read_vector_data (std::FILE *f, const std::size_t n, Array< ValueType > &v)
Internal routine to read vector data.
void hif::internal::mm_read_firstline (std::FILE *f, bool &is_sparse, bool &is_real, int &type_id)
Internal routine to parse the first line.
void hif::internal::mm_read_sparse_size (std::FILE *f, std::size_t &nrows, std::size_t &ncols, std::size_t &nnz)
Internal routine to read sizes.
void hif::internal::mm_read_dense_size (std::FILE *f, std::size_t &nrows, std::size_t &ncols)
template<class IndexType , class ValueType >
void hif::read_mm_sparse (const char *filename, std::size_t &nrows, std::size_t &ncols, Array< IndexType > &rows, Array< IndexType > &cols, Array< ValueType > &vals)
Read a sparse matrix form a MatrixMarket file.
template<class ValueType >
void hif::read_mm_vector (const char *filename, Array< ValueType > &v)
Read vector from a MatrixMarket file.
template<class ValueType >
void hif::write_mm_vector (const char *filename, const Array< ValueType > &v)
Write a float-point vector to a MatrixMarket file.
template<bool IsRowMajor, class IndptrType , class IndexType , class ValueType >
void hif::write_mm_sparse (const char *filename, const std::size_t other_size, const Array< IndptrType > &ind_start, const Array< IndexType > &indices, const Array< ValueType > &vals)
Write a sparse matrix.
Detailed Description
Function Documentation
get_word_size()
constexpr std::size_t hif::internal::get_word_size () inline
check the word size
Definition at line 109 of file io.hpp.
Referenced by hif::internal::write_general_info().
is_little_endian()
bool hif::internal::is_little_endian () inline
check if the os is litter endian
Definition at line 102 of file io.hpp.
Referenced by hif::query_info_bin(), hif::read_bin(), and hif::internal::write_general_info().
mm_read_dense_size()
void hif::internal::mm_read_dense_size (std::FILE * f, std::size_t & nrows, std::size_t & ncols) inline
Definition at line 1122 of file io.hpp.
Referenced by hif::read_mm_vector().
mm_read_firstline()
void hif::internal::mm_read_firstline (std::FILE * f, bool & is_sparse, bool & is_real, int & type_id) inline
Internal routine to parse the first line.
Definition at line 1019 of file io.hpp.
References hif::error().
Referenced by hif::read_mm_sparse(), and hif::read_mm_vector().
mm_read_sparse_data()
template<int TypeID, bool IsReal, class IndexType , class ValueType > void hif::internal::mm_read_sparse_data (std::FILE * f, const std::size_t nnz, Array< IndexType > & rows, Array< IndexType > & cols, Array< ValueType > & vals) inline
Internal routine to read sparse data.
Definition at line 946 of file io.hpp.
References hif::error().
mm_read_sparse_size()
void hif::internal::mm_read_sparse_size (std::FILE * f, std::size_t & nrows, std::size_t & ncols, std::size_t & nnz) inline
Internal routine to read sizes.
Definition at line 1087 of file io.hpp.
Referenced by hif::read_mm_sparse().
mm_read_vector_data()
template<bool IsReal, class ValueType > void hif::internal::mm_read_vector_data (std::FILE * f, const std::size_t n, Array< ValueType > & v) inline
Internal routine to read vector data.
Definition at line 1002 of file io.hpp.
References hif::error().
read_ascii()
template<class IndexArray , class ValueArray > std::tuple<bool, bool, char, std::size_t, std::size_t, std::size_t, std::size_t> hif::read_ascii (const char * fname, IndexArray & ind_start, IndexArray & indices, ValueArray & vals) inline
read data from ASCII file
Template Parameters
IndexArray index array type, see Array
ValueArray value array type, see Array
Parameters
[in] fname file name for output
[in] ind_start index start array
[in] indices index array
[in] vals value array
Definition at line 824 of file io.hpp.
References hif::DATA_UNDEF, and hif::error().
read_bin()
template<class CsType , typename T = std::uint64_t> std::enable_if<!CsType::ROW_MAJOR, T >::type hif::read_bin (const char * filename, CsType & A) inline
read data from file to a CCS matrix
Template Parameters
CsType ccs type
Parameters
[in] filename file name
[out] A matrix to store data from file
See also
write_bin
Definition at line 569 of file io.hpp.
References hif::Array< T >::Array(), hif::Array< T >::cbegin(), hif::Array< T >::cend(), hif::Array< T >::data(), hif::DATA_UNDEF, hif::error(), hif::internal::is_little_endian(), hif::internal::read_general_info(), hif::internal::read_matrix_data_attrs(), hif::internal::read_matrix_sizes(), hif::Array< T >::status(), and hif::warning().
read_general_info()
template<class InStream > std::tuple<bool, std::size_t, std::size_t, bool, bool, bool, bool> hif::internal::read_general_info (InStream & i_str) inline
read the general information
Template Parameters
InStream input stream type, should be std::ifstream
Parameters
[in,out] i_str in-file streamer
Returns
a tuple of args, from left to right, endianness, word size, integer size, row-major flag, C index flag, double precision flag, real/complex flag.
See also
write_general_info
Definition at line 121 of file io.hpp.
Referenced by hif::query_info_bin(), and hif::read_bin().
read_matrix_data_attrs()
template<class InStream > void hif::internal::read_matrix_data_attrs (InStream & i_str, const std::size_t int_size, const std::size_t real_size, const std::uint64_t start_size, const std::uint64_t nnz, char * ind_start, char * indices, char * vals) inline
read matrix data attributes
Template Parameters
InStream input stream type, should be std::ifstream
Parameters
[in,out] i_str in-file streamer
[in] int_size integer size in bytes
[in] real_size value data type size in bytes
[in] start_size primary size, i.e. row for CRS and col for CCS
[in] nnz total number of nonzeros
[out] ind_start raw data of size at least int_size*(start_size+1)
[out] indices raw data of size at least int_size*nnz
[out] vals raw data of size at least real_size*nnz
See also
write_matrix_data_attrs
Definition at line 180 of file io.hpp.
Referenced by hif::read_bin().
read_matrix_sizes()
template<class InStream > std::tuple<std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t> hif::internal::read_matrix_sizes (InStream & i_str) inline
read the matrix size information
Template Parameters
InStream input stream type, should be std::ifstream
Parameters
[in,out] i_str in-file streamer
Returns
a tuple of args, from left to right, row size, column size, number of nonzeros, and leading symmetric block size.
See also
write_matrix_sizes
Be aware that we use the fixed size integer (std::uint64_t) to store size information.
Definition at line 158 of file io.hpp.
Referenced by hif::query_info_bin(), and hif::read_bin().
read_mm_sparse()
template<class IndexType , class ValueType > void hif::read_mm_sparse (const char * filename, std::size_t & nrows, std::size_t & ncols, Array< IndexType > & rows, Array< IndexType > & cols, Array< ValueType > & vals) inline
Read a sparse matrix form a MatrixMarket file.
Template Parameters
IndexType Index type
ValueType Value type
Parameters
[in] filename File name
[out] nrows Output number of rows
[out] ncols Output number of columns
[out] rows Output row indices
[out] cols Output column indices
[out] vals Output values
Regardless what storage does filename uses, we always output a general matrix. Also, note that matrix market use coordinate format (aka IJV), thus if you plan to use this routine directly, then you need to convert the coordinate data structures into CRS/CCS if necessary.
Definition at line 1181 of file io.hpp.
References hif::error(), hif::internal::mm_read_firstline(), and hif::internal::mm_read_sparse_size().
read_mm_vector()
template<class ValueType > void hif::read_mm_vector (const char * filename, Array< ValueType > & v) inline
Read vector from a MatrixMarket file.
Template Parameters
ValueType Value type
Parameters
[in] filename File name
[out] v Output vector
Note
We only read the first column is the file contains multiple columns
See also
read_mm_sparse
Definition at line 1232 of file io.hpp.
References hif::error(), hif::internal::mm_read_dense_size(), and hif::internal::mm_read_firstline().
write_ascii()
template<bool IsRowMajor, class IndexArray , class ValueArray > void hif::write_ascii (const char * fname, const IndexArray & ind_start, const typename IndexArray::size_type other_size, const IndexArray & indices, const ValueArray & vals, const typename IndexArray::size_type m) inline
write to ASCII file
Template Parameters
IsRowMajor flag to indicate CRS or CCS
IndexArray index array type, see Array
ValueArray value array type, see Array
Parameters
[in] fname file name for output
[in] ind_start index start array
[in] other_size column size for CRS, row size for CCS
[in] indices index array
[in] vals value array
[in] m leading symmetric block size
Definition at line 721 of file io.hpp.
References hif::error().
write_bin()
template<class CsType > std::enable_if<CsType::ROW_MAJOR>::type hif::write_bin (const char * filename, const CsType & A, const std::uint64_t m) inline
write a CRS matrix
Template Parameters
CsType Crs type, see CRS
Parameters
[in] filename file name
[in] A matrix for writing to file
[in] m leading symmetric block size
See also
read_bin
Definition at line 321 of file io.hpp.
References hif::error(), hif::internal::write_general_info(), hif::internal::write_matrix_data_attrs(), and hif::internal::write_matrix_sizes().
write_general_info()
template<class OutStream > void hif::internal::write_general_info (OutStream & o_str, const std::size_t int_size, const bool is_row, const bool is_c, const bool is_double, const bool is_real) inline
write general information
Template Parameters
OutStream output stream type, should be std::ofstream
Parameters
[in,out] o_str out-file streamer
[in] int_size integer size
[in] is_row row-major flag
[in] is_c C index flag
[in] is_double double precision flag
[in] is_real real/complex flag
See also
read_general_info
Definition at line 201 of file io.hpp.
References hif::internal::get_word_size(), and hif::internal::is_little_endian().
Referenced by hif::write_bin().
write_matrix_data_attrs()
template<class OutStream > void hif::internal::write_matrix_data_attrs (OutStream & o_str, const std::size_t int_size, const std::size_t real_size, const std::uint64_t start_size, const std::uint64_t nnz, const void * ind_start, const void * indices, const void * vals) inline
write matrix data attributes
Template Parameters
OutStream output stream type, should be std::ofstream
Parameters
[in,out] o_str out-file streamer
[in] int_size integer size
[in] real_size value data type size
[in] start_size primary size
[in] nnz total number of nonzeros
[in] ind_start opaque pointer to start positions
[in] indices opaque pointer to indices
[in] vals opaque pointer to value array
See also
read_matrix_data_attrs
Definition at line 252 of file io.hpp.
Referenced by hif::write_bin().
write_matrix_sizes()
template<class OutStream > void hif::internal::write_matrix_sizes (OutStream & o_str, const std::uint64_t row, const std::uint64_t col, const std::uint64_t nnz, const std::uint64_t m) inline
write matrix size information
Template Parameters
OutStream output stream type, should be std::ofstream
Parameters
[in,out] o_str out-file streamer
[in] row row size
[in] col column size
[in] nnz total number of nonzeros
[in] m leading symmetric block size
See also
read_matrix_sizes
Definition at line 230 of file io.hpp.
Referenced by hif::write_bin().
write_mm_sparse()
template<bool IsRowMajor, class IndptrType , class IndexType , class ValueType > void hif::write_mm_sparse (const char * filename, const std::size_t other_size, const Array< IndptrType > & ind_start, const Array< IndexType > & indices, const Array< ValueType > & vals) inline
Write a sparse matrix.
Template Parameters
IsRowMajor Boolean tag for row-major (CRS) or not (CCS)
IndptrType Index pionter type
IndexType Index type
ValueType Value type
Parameters
[in] filename Output file name
[in] other_size The size of the uncompressed axis, e.g., ncols for CRS
[in] ind_start Index pionter
[in] indices Index list
[in] vals Data values
For CRS, call this function as write_mm_sparse<true>("test.mm", ncols, rowptr, colind, vals). Similarly, for CCS, call this function as write_mm_sparse<false>("test.mm", nrows, colptr, rowind, vals).
Definition at line 1305 of file io.hpp.
References hif::error().
write_mm_vector()
template<class ValueType > void hif::write_mm_vector (const char * filename, const Array< ValueType > & v) inline
Write a float-point vector to a MatrixMarket file.
See also
read_mm_vector
Definition at line 1263 of file io.hpp.
References hif::error().