HIFIR: Schur Complements
Schur Complements
Algorithms
Functions
template<class IndPtrArray , class IntArray , class ValueArray , class BufArray , class IntBufArray >
void hif::internal::drop_offsets_kernel (const IndPtrArray &ref_indptr, const double alpha, IndPtrArray &indptr, IntArray &indices, ValueArray &vals, BufArray &buf, IntBufArray &ibuf)
drop L_E matrix or U_F matrix
template<class CrsType , class BufArray , class IntBufArray >
void hif::drop_L_E (const typename CrsType::iparray_type &ref_indptr, const double alpha, CrsType &L_E, BufArray &buf, IntBufArray &ibuf)
drop L_E
template<class CcsType , class BufArray , class IntBufArray >
void hif::drop_U_F (const typename CcsType::iparray_type &ref_indptr, const double alpha, CcsType &U_F, BufArray &buf, IntBufArray &ibuf)
drop U_F
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType >
void hif::compute_Schur_simple (const ScaleArray &s, const CrsType &A, const ScaleArray &t, const PermType &p, const PermType &q, const typename CrsType::size_type m, const CrsType &L_E, const DiagArray &d, const CrsType &U_F, CrsType &SC, SpVecType &buf)
compute the simple version of Schur complement
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType >
CrsType hif::compute_Schur_simple (const ScaleArray &s, const CrsType &A, const ScaleArray &t, const PermType &p, const PermType &q, const typename CrsType::size_type m, const CrsType &L_E, const DiagArray &d, const CrsType &U_F, SpVecType &buf)
compute the simple version of Schur complement
template<class CrsType , class CcsType , class BufArray , class IntBufArray >
void hif::mt::drop_L_E_and_U_F (const typename CrsType::iparray_type &ref_indptr_L, const double alpha_L, const typename CcsType::iparray_type &ref_indptr_U, const double alpha_U, CrsType &L_E, CcsType &U_F, BufArray &buf_L, IntBufArray &ibuf_L, BufArray &buf_U, IntBufArray &ibuf_U, const int nthreads)
drop L_E and U_F
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType >
CrsType hif::mt::compute_Schur_simple (const ScaleArray &s, const CrsType &A, const ScaleArray &t, const PermType &p, const PermType &q, const typename CrsType::size_type m, const CrsType &L_E, const DiagArray &d, const CrsType &U_F, SpVecType &buf0, const int nthreads)
compute the simple version of Schur complement in MT setting
Detailed Description
Function Documentation
compute_Schur_simple() [1/3]
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType > void hif::compute_Schur_simple (const ScaleArray & s, const CrsType & A, const ScaleArray & t, const PermType & p, const PermType & q, const typename CrsType::size_type m, const CrsType & L_E, const DiagArray & d, const CrsType & U_F, CrsType & SC, SpVecType & buf) inline
compute the simple version of Schur complement
Template Parameters
ScaleArray row/column scaling vector type, see Array
CrsType crs matrix used for input, see CRS
PermType permutation vector type, see BiPermMatrix
DiagArray diagonal vector type, see Array
SpVecType sparse vector buffer type, see SparseVector
Parameters
[in] s row scaling vector
[in] A input crs matrix
[in] t column scaling vector
[in] p row permutation vector
[in] q column permutation vector
[in] m leading block size of current level
[in] L_E lower part after Crout update
[in] d diagonal entry that contains the leading block
[in] U_F upper part after Crout update
[out] SC Schur complement of C version
[out] buf work space, can use directly passed in as from Crout bufs
Mathematically, this is to compute:
Where , . Notice that both and are lower and upper parts after computing Crout updates. Therefore, they are rectangle matrices if . Accessing can be efficiently achieved with U_start vector, which is given after Crout updates.
This computation involves sparse matrix multiplication, which is done in three steps: 1) determine the total number of nonzeros, 2) determine the index pattern (symbolic computation), and 3) fill in the numerical values.
Definition at line 214 of file Schur.hpp.
References hif::DATA_UNDEF, and hif::warning().
compute_Schur_simple() [2/3]
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType > CrsType hif::compute_Schur_simple (const ScaleArray & s, const CrsType & A, const ScaleArray & t, const PermType & p, const PermType & q, const typename CrsType::size_type m, const CrsType & L_E, const DiagArray & d, const CrsType & U_F, SpVecType & buf) inline
compute the simple version of Schur complement
Template Parameters
ScaleArray row/column scaling vector type, see Array
CrsType crs matrix used for input, see CRS
PermType permutation vector type, see BiPermMatrix
DiagArray diagonal vector type, see Array
SpVecType sparse vector buffer type, see SparseVector
Parameters
[in] s row scaling vector
[in] A input crs matrix
[in] t column scaling vector
[in] p row permutation vector
[in] q column permutation vector
[in] m leading block size of current level
[in] L_E lower part after Crout update
[in] d diagonal entry that contains the leading block
[in] U_F upper part after Crout update
[out] buf work space, can use directly passed in as from Crout bufs
Returns
simple version of Schur complement
Definition at line 382 of file Schur.hpp.
compute_Schur_simple() [3/3]
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType > CrsType hif::mt::compute_Schur_simple (const ScaleArray & s, const CrsType & A, const ScaleArray & t, const PermType & p, const PermType & q, const typename CrsType::size_type m, const CrsType & L_E, const DiagArray & d, const CrsType & U_F, SpVecType & buf0, const int nthreads) inline
compute the simple version of Schur complement in MT setting
Template Parameters
ScaleArray row/column scaling vector type, see Array
CrsType crs matrix used for input, see CRS
PermType permutation vector type, see BiPermMatrix
DiagArray diagonal vector type, see Array
SpVecType sparse vector buffer type, see SparseVector
Parameters
[in] s row scaling vector
[in] A input crs matrix
[in] t column scaling vector
[in] p row permutation vector
[in] q column permutation vector
[in] m leading block size of current level
[in] L_E lower part after Crout update
[in] d diagonal entry that contains the leading block
[in] U_F upper part after Crout update
[out] buf0 work space, can use directly passed in as from Crout bufs
[in] nthreads number of threads used, must be at least 1, not alerted
Returns
simple version of Schur complement
Definition at line 585 of file Schur.hpp.
References hif::mt::get_thread().
drop_L_E()
template<class CrsType , class BufArray , class IntBufArray > void hif::drop_L_E (const typename CrsType::iparray_type & ref_indptr, const double alpha, CrsType & L_E, BufArray & buf, IntBufArray & ibuf) inline
drop L_E
Template Parameters
CrsType crs storage type, see CRS
BufArray value buffer type
IntBufArray integer buffer type
Parameters
[in] ref_indptr reference starting array
[in] alpha drop space limiter threshold
[in,out] L_E in and out puts of L offset
[out] buf work space
[out] ibuf integer work space
Note
buffers can be got from Crout work spaces
See also
drop_U_F
Definition at line 135 of file Schur.hpp.
drop_L_E_and_U_F()
template<class CrsType , class CcsType , class BufArray , class IntBufArray > void hif::mt::drop_L_E_and_U_F (const typename CrsType::iparray_type & ref_indptr_L, const double alpha_L, const typename CcsType::iparray_type & ref_indptr_U, const double alpha_U, CrsType & L_E, CcsType & U_F, BufArray & buf_L, IntBufArray & ibuf_L, BufArray & buf_U, IntBufArray & ibuf_U, const int nthreads) inline
drop L_E and U_F
Template Parameters
CrsType crs storage type, see CRS
CcsType ccs storage type, see CCS
BufArray value buffer type
IntBufArray integer buffer type
Parameters
[in] ref_indptr_L reference starting array for L_E
[in] alpha_L drop space limiter threshold for L_E
[in] ref_indptr_U reference starting array for U_F
[in] alpha_U drop space limiter threshold for U_F
[in,out] L_E in and out puts of L offset
[in,out] U_F in and out puts of U offset
[out] buf_L work space for L_E
[out] ibuf_L integer work space for L_E
[out] buf_U work space for U_F
[out] ibuf_U workspace for U_F
[in] nthreads total threads used, must be at least 1, not alerted
Note
buffers can be got from Crout work spaces
Definition at line 422 of file Schur.hpp.
References hif::mt::get_thread().
drop_offsets_kernel()
template<class IndPtrArray , class IntArray , class ValueArray , class BufArray , class IntBufArray > void hif::internal::drop_offsets_kernel (const IndPtrArray & ref_indptr, const double alpha, IndPtrArray & indptr, IntArray & indices, ValueArray & vals, BufArray & buf, IntBufArray & ibuf) inline
drop L_E matrix or U_F matrix
Template Parameters
IndPtrArray index pointer array
IntArray integer array, see Array
ValueArray value array, see Array
BufArray value buffer array type
IntBufArray integer buffer array type
Parameters
[in] ref_indptr reference starting position array
[in] alpha drop space limiter threshold
[in,out] indptr in and out put index starting array
[in,out] indices in and out put index array
[in,out] vals in and out put values
[out] buf work space
[out] ibuf integer work space
Definition at line 61 of file Schur.hpp.
drop_U_F()
template<class CcsType , class BufArray , class IntBufArray > void hif::drop_U_F (const typename CcsType::iparray_type & ref_indptr, const double alpha, CcsType & U_F, BufArray & buf, IntBufArray & ibuf) inline
drop U_F
Template Parameters
CcsType ccs storage type, see CCS
BufArray value buffer type
IntBufArray integer buffer type
Parameters
[in] ref_indptr reference starting array
[in] alpha drop space limiter threshold
[in,out] U_F in and out puts of U offset
[out] buf work space
[out] ibuf integer work space
Note
buffers can be got from Crout work spaces
See also
drop_L_E
Definition at line 162 of file Schur.hpp.