HIFIR: Mixed-Precision Routines in LIBHIFIR
Mixed-Precision Routines in LIBHIFIR
LIBHIFIR C Interfaces
Functions
LhfStatus lhfsdUpdate (LhfsHifHdl hif, LhfdMatrixHdl A)
Update the A matrix in HIF (double precision)
LhfStatus lhfsdApply (const LhfsHifHdl hif, const LhfOperationType op, const double *b, const int nirs, const double *betas, const int rank, double *x, int *ir_status)
Apply a single preconditioner with a certian operation mode to obtain double solutions.
LhfStatus lhfsdSolve (const LhfsHifHdl hif, const double *b, double *x)
Triangular solve with midex double- and single-precisoin.
LhfStatus lhfczUpdate (LhfcHifHdl hif, LhfzMatrixHdl A)
Update the A matrix in HIF (complex double precision)
LhfStatus lhfczApply (const LhfcHifHdl hif, const LhfOperationType op, const double _Complex *b, const int nirs, const double *betas, const int rank, double _Complex *x, int *ir_status)
Apply a single preconditioner with a certian operation mode to obtain double solutions (complex arithmetic)
LhfStatus lhfczSolve (const LhfcHifHdl hif, const double _Complex *b, double _Complex *x)
Triangular solve with midex double- and single-precisoin (complex)
Detailed Description
Function Documentation
lhfczApply()
LhfStatus lhfczApply (const LhfcHifHdl hif, const LhfOperationType op, const double _Complex * b, const int nirs, const double * betas, const int rank, double _Complex * x, int * ir_status)
Apply a single preconditioner with a certian operation mode to obtain double solutions (complex arithmetic)
Parameters
[in] hif A complex single-precision HIF instance
[in] op Operation tag
[in] b The RHS vector
[in] nirs Number of iterative refinements
[in] betas Relative residual norm bounds for IR with op=solve
[in] rank Numerical rank
[out] x Computed solution vector
[out] ir_status (optional) If IR and betas is provided, then this records the number of actual IR (ir_status[0]) and the IR status (ir_status[1]).
This is the core function of HIF. A HIF instance can be applied in four different modes, namely triangular solve and its Hermitian/tranpose variant, as well as matrix-vector multiplication and its Hermitian/tranpose variant. For the triangular solve modes, nirs can be greater than one, which means iterative refinement is enabled. With IR enabled, if betas is provided, i.e., not NULL, then we will iterative until (1) res<=betas[0], (2) res>betas[1], or (3) it=nirs, and the actual iteratoin steps and return status are stored in ir_status if provided (i.e., not NULL). On the other side, if betas=NULL, then the a fixed amount of IR (nirs) are performed and ir_status is not accessed. Regarding rank, in general, it should use LHF_DEFAULT_RANK.
In addition, this function is for mixed-precision computation, in that a single-precision HIF is used to obtain double-precision solutions. Note that if iterative refinement is on (i.e., nirs>1 and op=solve), then A must be passed in separately via lhfczUpdate, because we need a double-precision matrix for iterations.
See also
lhfczSolve, lhfzApply, lhfcApply, lhfczUpdate
Definition at line 1247 of file libhifir.cpp.
References libhifir_impl::hifir(), LHF_DEFAULT_RANK, LHF_M, LHF_MH, LHF_MISMATCHED_SIZES, LHF_S, LHF_SH, LHF_SUCCESS, libhifir_impl::mmultiply(), hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows(), and libhifir_impl::solve().
lhfczSolve()
LhfStatus lhfczSolve (const LhfcHifHdl hif, const double _Complex * b, double _Complex * x)
Triangular solve with midex double- and single-precisoin (complex)
For the sake of convenience, we provide the following routine as it is the most commonly used interface. The following routine is equivalent to calling lhfczApply with op=LHF_S, nirs=1, and rank=LHF_DEFAULT_RANK.
See also
lhfczApply
Definition at line 1280 of file libhifir.cpp.
References LHF_SUCCESS, and libhifir_impl::solve().
lhfczUpdate()
LhfStatus lhfczUpdate (LhfcHifHdl hif, LhfzMatrixHdl A)
Update the A matrix in HIF (complex double precision)
Parameters
[out] hif A HIF instance (complex single-precision)
[in] A A new matrix (complex double-precision)
Note
This function will not call factorization on A.
This function will update the double-precision operator in hif.
See also
lhfczApply
Definition at line 1238 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::empty(), LHF_MISMATCHED_SIZES, LHF_SUCCESS, and hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows().
lhfsdApply()
LhfStatus lhfsdApply (const LhfsHifHdl hif, const LhfOperationType op, const double * b, const int nirs, const double * betas, const int rank, double * x, int * ir_status)
Apply a single preconditioner with a certian operation mode to obtain double solutions.
Parameters
[in] hif A single-precision HIF instance
[in] op Operation tag
[in] b The RHS vector
[in] nirs Number of iterative refinements
[in] betas Relative residual norm bounds for IR with op=solve
[in] rank Numerical rank
[out] x Computed solution vector
[out] ir_status (optional) If IR and betas is provided, then this records the number of actual IR (ir_status[0]) and the IR status (ir_status[1]).
This is the core function of HIF. A HIF instance can be applied in four different modes, namely triangular solve and its Hermitian/tranpose variant, as well as matrix-vector multiplication and its Hermitian/tranpose variant. For the triangular solve modes, nirs can be greater than one, which means iterative refinement is enabled. With IR enabled, if betas is provided, i.e., not NULL, then we will iterative until (1) res<=betas[0], (2) res>betas[1], or (3) it=nirs, and the actual iteratoin steps and return status are stored in ir_status if provided (i.e., not NULL). On the other side, if betas=NULL, then the a fixed amount of IR (nirs) are performed and ir_status is not accessed. Regarding rank, in general, it should use LHF_DEFAULT_RANK.
In addition, this function is for mixed-precision computation, in that a single-precision HIF is used to obtain double-precision solutions. Note that if iterative refinement is on (i.e., nirs>1 and op=solve), then A must be passed in separately via lhfsdUpdate, because we need a double-precision matrix for iterations.
See also
lhfsdSolve, lhfdApply, lhfsApply, lhfsdUpdate
Definition at line 1198 of file libhifir.cpp.
References libhifir_impl::hifir(), LHF_DEFAULT_RANK, LHF_M, LHF_MH, LHF_MISMATCHED_SIZES, LHF_S, LHF_SH, LHF_SUCCESS, libhifir_impl::mmultiply(), hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows(), and libhifir_impl::solve().
lhfsdSolve()
LhfStatus lhfsdSolve (const LhfsHifHdl hif, const double * b, double * x)
Triangular solve with midex double- and single-precisoin.
For the sake of convenience, we provide the following routine as it is the most commonly used interface. The following routine is equivalent to calling lhfsdApply with op=LHF_S, nirs=1, and rank=LHF_DEFAULT_RANK.
See also
lhfsdApply
Definition at line 1227 of file libhifir.cpp.
References LHF_SUCCESS, and libhifir_impl::solve().
lhfsdUpdate()
LhfStatus lhfsdUpdate (LhfsHifHdl hif, LhfdMatrixHdl A)
Update the A matrix in HIF (double precision)
Parameters
[out] hif A HIF instance (single-precision)
[in] A A new matrix (double-precision)
Note
This function will not call factorization on A.
This function will update the double-precision operator in hif.
See also
lhfsdApply
Definition at line 1189 of file libhifir.cpp.
References hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::empty(), LHF_MISMATCHED_SIZES, LHF_SUCCESS, and hif::HIF< ValueType, IndexType, IndPtrType, UserDenseFactor >::nrows().