HIFIR: Utilities
Utilities
Modules
Multithreading
File I/O
Classes
struct hif::ValueTypeTrait< T >
trait extract value type
class hif::Const< T >
constant values
struct hif::ValueTypeMixedTrait< T >
trait to determine mixed precision relationships
class hif::internal::SpVInternalExtractor< SpVecType >
advanced helper class for extract internal data attributes from SparseVector
struct hif::internal::StdoutStruct
struct wrapped around stdout
struct hif::internal::StderrStruct
struct wrapped around stderr
struct hif::internal::DummyStreamer
dummy streamer (empty functor)
struct hif::internal::DummyErrorStreamer
streamer with error/warning information for dummy usage
class hif::Timer< Clock, RepType >
C++11 standard timer implementation.
Macros
#define hif_verbose2(__LVL, __opt_tag) (__opt_tag & ::hif::VERBOSE_##__LVL)
return true if certain verbose level is defined
#define hif_verbose(__LVL, __opt) hif_verbose2(__LVL, __opt.verbose)
return true if certain verbose level is defined
#define hif_info(__msgs...) ::hif::info(__msgs)
general message streaming macro wrapper
#define hif_warning(__msgs...)
print warning message
#define hif_warning_if(__cond, __msgs...)
conditionally print message, __cond will be shown as prefix
#define hif_error(__msgs...) ::hif::error(nullptr, __HIF_FILE__, __HIF_FUNC__, __LINE__, __msgs)
print warning message and abort
#define hif_error_if(__cond, __msgs...)
conditionally print warning message and abort
#define hif_assert(__cond, __msgs...)
internal debugging assertion
#define hif_debug_code(__code)
code will only be translated on debug builds
#define LOAD_STACKTRACE(__ss, __limit)
Load stack trace on error aborts.Currently, this macro only works on *nix systems. It will load C++ symbols nicely to ostream __ss, thus can be later transferred to, e.g., HIF_STDERR.
Typedefs
typedef Timer hif::DefaultTimer
default timer used in this package
Enumerations
enum hif::ClockType { hif::TIMER_SYSTEM_CLOCK, hif::TIMER_HIRES_CLOCK }
clock type used in application
enum hif::ClockUnit { hif::TIMER_SECONDS = 0, hif::TIMER_MILLISECONDS, hif::TIMER_MICROSECONDS, hif::TIMER_NANOSECONDS }
time period units
Functions
template<class Iter , class ValueType >
std::pair< bool, Iter > hif::find_sorted (Iter first, Iter last, const ValueType &v)
apply binary search on a sorted array
template<class ArrayType >
void hif::rotate_left (const typename ArrayType::size_type n, const typename ArrayType::size_type src, ArrayType &v)
rotate a subset of vector, s.t. src appears to the left most pos
template<class ArrayType >
void hif::rotate_right (const typename ArrayType::size_type n, const typename ArrayType::size_type src, ArrayType &v)
rotate a subset of vector, s.t. src appears to the right most pos
template<class T , class ArrayType >
T * hif::ensure_type_consistency (const ArrayType &v, const bool copy_if_needed=true)
ensure consistent between data types of T and input array
void hif::info (std::string msg,...)
common information streaming, dump msg to HIF_STDOUT
void hif::warning (const char *prefix, const char *file, const char *func, const unsigned line, std::string msg,...)
warning information streaming, dump to HIF_STDERR
void hif::error (const char *prefix, const char *file, const char *func, const unsigned line, std::string msg,...)
error information streaming, dump to HIF_STDERR
template<class T >
std::enable_if< std::is_floating_point< T >::value, T >::type hif::conjugate (const T &v)
conjugate helper function
template<class ArrayType , class Iteratable >
ArrayType::value_type hif::inner (const ArrayType &v1, const Iteratable &v2)
compute the dot product
template<class ArrayType >
ValueTypeTrait< typename ArrayType::value_type >::value_type hif::norm2_sq (const ArrayType &v)
compute the norm 2 square
template<class ArrayType >
ValueTypeTrait< typename ArrayType::value_type >::value_type hif::norm2 (const ArrayType &v)
compute the Euclidean norm of a given vector
template<class ArrayType >
void hif::normalize (ArrayType &v)
normalize an array
template<class ArrayType , class Iter >
void hif::normalize2 (const ArrayType &v, Iter &w)
normalize an array and save the result to another array
Detailed Description
Macro Definition Documentation
hif_assert
#define hif_assert (__cond, __msgs...)
internal debugging assertion
Definition at line 220 of file log.hpp.
hif_debug_code
#define hif_debug_code (__code)
code will only be translated on debug builds
Definition at line 221 of file log.hpp.
hif_error
#define hif_error (__msgs...) ::hif::error(nullptr, __HIF_FILE__, __HIF_FUNC__, __LINE__, __msgs)
print warning message and abort
See also
hif::error
Definition at line 193 of file log.hpp.
hif_error_if
#define hif_error_if (__cond, __msgs...)
Value:
if (__cond)                                                            \
  ::hif::error("invalid condition " #__cond, __HIF_FILE__, __HIF_FUNC__, \
               __LINE__, __msgs)
conditionally print warning message and abort
See also
hif::error
Definition at line 200 of file log.hpp.
hif_info
#define hif_info (__msgs...) ::hif::info(__msgs)
general message streaming macro wrapper
See also
hif::info
Examples:
demo_fgmres.cpp, demo_fgmres_sparsifier.cpp, demo_gmreshif.cpp, demo_hifir.cpp, demo_multiply.cpp, and demo_sparsifier.cpp.
Definition at line 152 of file log.hpp.
hif_verbose
#define hif_verbose (__LVL, __opt) hif_verbose2(__LVL, __opt.verbose)
return true if certain verbose level is defined
Note
__LVL must be upper case and align with the enumerators
This macro is for algorithm implementation thus available only in C++
if (hif_verbose(INFO, opt)) ...;
Definition at line 594 of file Options.h.
hif_verbose2
#define hif_verbose2 (__LVL, __opt_tag) (__opt_tag & ::hif::VERBOSE_##__LVL)
return true if certain verbose level is defined
Note
__LVL must be upper case and align with the enumerators
This macro is for algorithm implementation thus available only in C++
Definition at line 581 of file Options.h.
hif_warning
#define hif_warning (__msgs...)
Value:
do {                                                                       \
    if (::hif::warn_flag())                                                  \
      ::hif::warning(nullptr, __HIF_FILE__, __HIF_FUNC__, __LINE__, __msgs); \
  } while (false)
print warning message
See also
hif::warning
Definition at line 172 of file log.hpp.
hif_warning_if
#define hif_warning_if (__cond, __msgs...)
Value:
do {                                                              \
    if (::hif::warn_flag() && (__cond))                             \
      ::hif::warning("condition " #__cond " alerted", __HIF_FILE__, \
                     __HIF_FUNC__, __LINE__, __msgs);               \
  } while (false)
conditionally print message, __cond will be shown as prefix
See also
hif::warning
Definition at line 182 of file log.hpp.
LOAD_STACKTRACE
#define LOAD_STACKTRACE (__ss, __limit)
Value:
do {                                                         \
      __ss << "stack trace is not available on the platform.\n"; \
    } while (false)
Load stack trace on error aborts.Currently, this macro only works on *nix systems. It will load C++ symbols nicely to ostream __ss, thus can be later transferred to, e.g., HIF_STDERR.
Definition at line 93 of file stacktrace.hpp.
Typedef Documentation
DefaultTimer
hif::DefaultTimer
default timer used in this package
Definition at line 168 of file Timer.hpp.
Enumeration Type Documentation
ClockType
enum hif::ClockType
clock type used in application
Enumerator
TIMER_SYSTEM_CLOCK
using system clock
TIMER_HIRES_CLOCK
using high resolution clock, may be alias of system
Definition at line 40 of file Timer.hpp.
ClockUnit
enum hif::ClockUnit
time period units
Enumerator
TIMER_SECONDS
default second
TIMER_MILLISECONDS
milli second
TIMER_MICROSECONDS
micro second
TIMER_NANOSECONDS
nano second
Definition at line 48 of file Timer.hpp.
Function Documentation
conjugate()
template<class T > std::enable_if<std::is_floating_point<T>::value, T>::type hif::conjugate (const T & v) inline
conjugate helper function
Template Parameters
T abstract value type, real type
Parameters
[in] v value input
Returns
conceputally, the return is the "conjugate" of v
Definition at line 62 of file math.hpp.
ensure_type_consistency()
template<class T , class ArrayType > T* hif::ensure_type_consistency (const ArrayType & v, const bool copy_if_needed = true) inline
ensure consistent between data types of T and input array
Template Parameters
T desired data type
ArrayType array container type, see Array
Parameters
[in] v input array
[in] copy_if_needed if true (default), then copy the values
This helper function simply checks if sizeof(T) equals to that of ArrayType::value_type, if not, then allocate new array with the same size of v. Notice that the above condition should be used to deallocate the memory.
Definition at line 162 of file common.hpp.
error()
void hif::error (const char * prefix, const char * file, const char * func, const unsigned line, std::string msg, ...) inline
error information streaming, dump to HIF_STDERR
Parameters
[in] prefix prefix message, omitted if passed as nullptr
[in] file filename, i.e. FILE
[in] func function name, i.e. func
[in] line line number, i.e. LINE
[in] msg message string
See also
hif_error, hif_error_if
Definition at line 125 of file log.hpp.
Referenced by hif::NspFilter::_const_filter(), hif::Array< index_type >::at(), hif::AugCRS< CrsType >::build_aug(), hif::AugCCS< CcsType >::build_aug(), hif::internal::CompressedStorage< value_type, index_type >::check_validity(), hif::internal::convert_storage(), hif::EqlDriver< ValueType, IndexType >::do_matching(), hif::do_preprocessing(), hif::Prec< ValueType, IndexType, UserDenseFactor >::export_sparse_data(), hif::internal::extract_E(), hif::internal::extract_F(), hif::internal::extract_perm_diag(), hif::LUP< ValueType >::factorize(), hif::SYEIG< ValueType >::factorize(), hif::HIF< ValueType, IndexType, UserDenseFactor >::factorize(), hif::NspFilter::filter(), hif::level_factorize(), hif::internal::mm_read_firstline(), hif::internal::mm_read_sparse_data(), hif::internal::mm_read_vector_data(), hif::CRS< value_type, index_type >::multiply_mrhs_nt(), hif::IntervalCRS< ValueType, IndexType, IntervalType >::multiply_nt(), hif::CRS< value_type, index_type >::multiply_nt(), hif::pivot_level_factorize(), hif::HIF< ValueType, IndexType, UserDenseFactor >::prec(), hif::query_info_ascii(), hif::query_info_bin(), hif::read_ascii(), hif::read_bin(), hif::read_mm_sparse(), hif::read_mm_vector(), hif::run_amd(), hif::CRS< value_type, index_type >::scale_diag_left(), hif::CCS< ValueType, IndexType >::scale_diag_left(), hif::CRS< value_type, index_type >::scale_diag_right(), hif::CCS< ValueType, IndexType >::scale_diag_right(), hif::LUP< ValueType >::solve(), hif::LUP< ValueType >::solve_mrhs(), hif::HIF< ValueType, IndexType, UserDenseFactor >::stats(), hif::symm_level_factorize(), hif::wrap_const_ccs(), hif::wrap_const_crs(), hif::write_ascii(), hif::write_bin(), hif::write_mm_sparse(), and hif::write_mm_vector().
find_sorted()
template<class Iter , class ValueType > std::pair<bool, Iter> hif::find_sorted (Iter first, Iter last, const ValueType & v) inline
apply binary search on a sorted array
Template Parameters
Iter iterator type
ValueType value type that can be casted to the derefence of Iter
Parameters
[in] first starting iterator
[in] last ending iterator
[in] v target value
Returns
pair<bool, Iter> that the first indicates if or not we find v, while the second is the location
Definition at line 59 of file common.hpp.
info()
void hif::info (std::string msg, ...) inline
common information streaming, dump msg to HIF_STDOUT
Parameters
[in] msg message string
See also
hif_info top level macro wrapper
Examples:
demo_hifir.cpp.
Definition at line 79 of file log.hpp.
Referenced by hif::do_maching(), hif::do_preprocessing(), hif::QRCP< ValueType >::factorize(), hif::SYEIG< ValueType >::factorize(), hif::HIF< ValueType, IndexType, UserDenseFactor >::factorize(), hif::level_factorize(), hif::internal::StdoutStruct::operator()(), hif::pivot_level_factorize(), hif::Prec< ValueType, IndexType, UserDenseFactor >::report_status_ef(), hif::Prec< ValueType, IndexType, UserDenseFactor >::report_status_lu(), and hif::symm_level_factorize().
inner()
template<class ArrayType , class Iteratable > ArrayType::value_type hif::inner (const ArrayType & v1, const Iteratable & v2) inline
compute the dot product
Template Parameters
ArrayType array type, see, for instance, Array
Iteratable iteratable type for second array
Parameters
[in] v1 first array input
[in] v2 second array input
Returns
dot product of v1 and v2
Definition at line 83 of file math.hpp.
norm2()
template<class ArrayType > ValueTypeTrait<typename ArrayType::value_type>::value_type hif::norm2 (const ArrayType & v) inline
compute the Euclidean norm of a given vector
Template Parameters
ArrayType array type, see, for instance, Array
Parameters
[in] v array input
Definition at line 112 of file math.hpp.
Referenced by compute_error(), and compute_relres().
norm2_sq()
template<class ArrayType > ValueTypeTrait<typename ArrayType::value_type>::value_type hif::norm2_sq (const ArrayType & v) inline
compute the norm 2 square
Template Parameters
ArrayType array type, see, for instance, Array
Parameters
[in] v array input
Definition at line 97 of file math.hpp.
normalize()
template<class ArrayType > void hif::normalize (ArrayType & v) inline
normalize an array
Template Parameters
ArrayType array type, see, for instance, Array
Parameters
[in,out] v array input, upon output, it will be normalized
Definition at line 144 of file math.hpp.
normalize2()
template<class ArrayType , class Iter > void hif::normalize2 (const ArrayType & v, Iter & w) inline
normalize an array and save the result to another array
Template Parameters
ArrayType array type, see, for instance, Array
Iter Iterator type
Parameters
[in] v array input
[out] w iterator output
Definition at line 158 of file math.hpp.
rotate_left()
template<class ArrayType > void hif::rotate_left (const typename ArrayType::size_type n, const typename ArrayType::size_type src, ArrayType & v) inline
rotate a subset of vector, s.t. src appears to the left most pos
Template Parameters
ArrayType input and output array type
Parameters
[in] n local size of how many items will be shifted
[in] src index in global range
[in,out] v input and output array
Note
Complexity:
See also
rotate_right
Definition at line 76 of file common.hpp.
rotate_right()
template<class ArrayType > void hif::rotate_right (const typename ArrayType::size_type n, const typename ArrayType::size_type src, ArrayType & v) inline
rotate a subset of vector, s.t. src appears to the right most pos
Template Parameters
ArrayType input and output array type
Parameters
[in] n local size of how many items will be shifted
[in] src index in global range
[in,out] v input and output array
Note
Complexity:
See also
rotate_left
For right rotation, we need to use reverse_iterator
Definition at line 92 of file common.hpp.
warning()
void hif::warning (const char * prefix, const char * file, const char * func, const unsigned line, std::string msg, ...) inline
warning information streaming, dump to HIF_STDERR
Parameters
[in] prefix prefix message, omitted if passed as nullptr
[in] file filename
[in] func function name, i.e. func
[in] line line number, i.e. LINE
[in] msg message string
See also
hif_warning, hif_warning_if
Definition at line 92 of file log.hpp.
Referenced by hif::PivotCrout::apply_thres_pivot(), hif::compute_Schur_simple(), hif::DenseMatrix< value_type >::copy_sparse(), hif::EqlDriver< ValueType, IndexType >::do_matching(), hif::LUP< ValueType >::factorize(), hif::QRCP< ValueType >::factorize(), hif::SYEIG< ValueType >::factorize(), hif::mt::multiply_mrhs_nt(), hif::mt::multiply_mrhs_nt_low(), hif::mt::multiply_nt(), hif::mt::multiply_nt_low(), hif::read_bin(), hif::wrap_const_ccs(), and hif::wrap_const_crs().