HIFIR: hif Namespace Reference
hif Namespace Reference
Namespaces
amd
eql
internal
mt
rcm
Classes
class Array
Core data structure used in compressed storage.
class AugCCS
Augmented CCS data structure.
class AugCRS
Augmented CRS data structure.
class BiPermMatrix
This is the bi-directional version, i.e. the inverse mapping is avail.
class CCS
Compressed Column Storage (CCS) format for sparse matrices.
class Const
constant values
class Crout
Crout update in deferred fashionThe idea of this class is to implement Crout kernels that wrap around a common factor—step. In this case, the class Crout is as simple (in terms of data size) as an integer. It also supports implicitly casting to integer as well as increment operations (both suffix and prefix versions). The whole disign can be demonstrate by the following C++ pseudocode:
class CRS
Compressed Row Storage (CRS) format for sparse matrices.
class DenseMatrix
Dense storage.
class EqlDriver
driver class wrapped around eql::Equilibrator
class HIF
class IndexValueArray
class IntervalCCS
Interval-based CCS representation.
class IntervalCRS
Interval-based CRS representation.
struct is_interval_cs
Trait for determining interval compressed storage.
struct is_interval_cs< Cs, decltype(std::declval< Cs >().nitrvs(), void())>
Trait for determining interval compressed storage.
class IterRefine
Iterative refinement operator.
class Lapack
class LUP
LU with partial pivoting for small scale solver.
class NspFilter
filter attached to HIF for filtering null space componentsFlexible design of null space components filter. The default mode is constant filter, i.e., there is a constant mode in the system. Two ways to customize the filter, 1) override the NspFilter::user_filter function or 2) pass in a callback function.
class PermMatrix
permutation matrix defined as the P(i) entry in original matrix is the i-th entry in the permutated one
class PivotCrout
Crout update in deferred fashion with pivotingThe idea of this class is to implement Crout kernels that wrap around a common factor—step. In this case, the class Crout is as simple (in terms of data size) as an integer. It also supports implicitly casting to integer as well as increment operations (both suffix and prefix versions). The whole disign can be demonstrate by the following C++ pseudocode:
class Prec
A single level preconditioner.
class QRCP
QR with column pivoting for small scale solver.
class SmallScaleSolverTrait
Trait for selecting backend solver types.
class SparseVector
class SYEIG
Symmetric eigen-decompsition for small scale solver.
class Timer
C++11 standard timer implementation.
struct using_interval_from_classical
helper trait to define interval type from classical
struct ValueTypeMixedTrait
trait to determine mixed precision relationships
struct ValueTypeTrait
trait extract value type
Typedefs
template<class ValueType , class IndexType , template< class > class UserDenseFactor = DefaultDenseSolver>
using Precs = std::list< Prec< ValueType, IndexType, UserDenseFactor > >
multilevel preconditioners
typedef HIF< double, int > DefaultHIF
default HIF with double as value type and int as index
template<class ValueType , class IndexType >
using CSR = CRS< ValueType, IndexType >
Alias of CRS.
template<class ValueType , class IndexType >
using CSC = CCS< ValueType, IndexType >
Alias of CCS.
typedef std::shared_ptr< NspFilter > NspFilterPtr
shared pointer of NspFilter, this should be used in user code
typedef hif_Options Options
type wrapper
typedef Options Params
alias of Options
typedef Timer DefaultTimer
default timer used in this package
Enumerations
enum : unsigned char { DATA_UNDEF = 0, DATA_WRAP, DATA_OWN }
enum : int {
VERBOSE_NONE = ::HIF_VERBOSE_NONE, VERBOSE_INFO = ::HIF_VERBOSE_INFO, VERBOSE_PRE = ::HIF_VERBOSE_PRE, VERBOSE_FAC = ::HIF_VERBOSE_FAC,
VERBOSE_PRE_TIME = ::HIF_VERBOSE_PRE_TIME, VERBOSE_MEM = ::HIF_VERBOSE_MEM, VERBOSE_INFO2 = ::HIF_VERBOSE_INFO2
}
enum wrapper
enum : int {
REORDER_OFF = ::HIF_REORDER_OFF, REORDER_AUTO = ::HIF_REORDER_AUTO, REORDER_AMD = ::HIF_REORDER_AMD, REORDER_RCM = ::HIF_REORDER_RCM,
REORDER_NULL = ::HIF_REORDER_NULL
}
enum wrapper for reordering methods
enum : int { PIVOTING_OFF = ::HIF_PIVOTING_OFF, PIVOTING_ON = ::HIF_PIVOTING_ON, PIVOTING_AUTO = ::HIF_PIVOTING_AUTO }
enum wrapper for pivoting
enum ClockType { TIMER_SYSTEM_CLOCK, TIMER_HIRES_CLOCK }
clock type used in application
enum ClockUnit { TIMER_SECONDS = 0, TIMER_MILLISECONDS, TIMER_MICROSECONDS, TIMER_NANOSECONDS }
time period units
Functions
template<bool IsSymm, class CsType , class CroutStreamer , class PrecsType , class IntArray >
CsType level_factorize (const CsType &A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options &opts, const CroutStreamer &Crout_info, PrecsType &precs, IntArray &row_sizes, IntArray &col_sizes, typename CsType::size_type *stats, const int schur_threads=1, int *auto_pivot_tag=nullptr)
perform partial incomplete LU for a level
template<class CsType , class CroutStreamer , class PrecsType , class IntArray >
CsType pivot_level_factorize (const CsType &A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options &opts, const CroutStreamer &Crout_info, PrecsType &precs, IntArray &row_sizes, IntArray &col_sizes, typename CsType::size_type *stats, const int schur_threads=1)
perform partial incomplete LU for a level with thresholding pivoting
template<class PrecItr , class RhsType , class SolType , class WorkType >
void prec_prod (PrecItr prec_itr, const RhsType &b, const std::size_t last_dim, SolType &y, WorkType &work)
Given multilevel preconditioner and rhs, compute the matrix-vector.
template<class PrecItr , class RhsType , class SolType , class WorkType >
void prec_prod_tran (PrecItr prec_itr, const RhsType &b, const std::size_t last_dim, SolType &y, WorkType &work)
Given multilevel preconditioner and rhs, compute the matrix-vector.
template<class PrecItr , class RhsType , class SolType , class WorkType >
void prec_solve (PrecItr prec_itr, const RhsType &b, const std::size_t last_dim, SolType &y, WorkType &work)
Given multilevel preconditioner and rhs, solve the solution.
template<class PrecItr , class RhsValueType , class SolValueType , class WorkValueType , std::size_t Nrhs>
void prec_solve_mrhs (PrecItr prec_itr, const Array< std::array< RhsValueType, Nrhs >> &b, const std::size_t last_dim, Array< std::array< SolValueType, Nrhs >> &y, Array< std::array< WorkValueType, Nrhs >> &work)
Given multilevel preconditioner and mutiple RHS, solve the solution.
template<class PrecItr , class RhsType , class SolType , class WorkType >
void prec_solve_tran (PrecItr prec_itr, const RhsType &b, const std::size_t last_dim, SolType &y, WorkType &work)
Given multilevel preconditioner and rhs, solve the solution transpose.
template<class PrecItr >
std::size_t compute_prec_work_space (PrecItr first, PrecItr last)
compute the safe buffer size for prec_solve
template<class CrsType , class BufArray , class IntBufArray >
void drop_L_E (const typename CrsType::iarray_type &ref_indptr, const double alpha, CrsType &L_E, BufArray &buf, IntBufArray &ibuf)
drop L_E
template<class CcsType , class BufArray , class IntBufArray >
void drop_U_F (const typename CcsType::iarray_type &ref_indptr, const double alpha, CcsType &U_F, BufArray &buf, IntBufArray &ibuf)
drop U_F
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType >
void compute_Schur_simple (const ScaleArray &s, const CrsType &A, const ScaleArray &t, const PermType &p, const PermType &q, const typename CrsType::size_type m, const CrsType &L_E, const DiagArray &d, const CrsType &U_F, CrsType &SC, SpVecType &buf)
compute the simple version of Schur complement
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType >
CrsType compute_Schur_simple (const ScaleArray &s, const CrsType &A, const ScaleArray &t, const PermType &p, const PermType &q, const typename CrsType::size_type m, const CrsType &L_E, const DiagArray &d, const CrsType &U_F, SpVecType &buf)
compute the simple version of Schur complement
template<class CsType , class CroutStreamer , class PrecsType , class IntArray >
CsType symm_level_factorize (const CsType &A, const typename CsType::size_type m0, const typename CsType::size_type N, const Options &opts, const CroutStreamer &Crout_info, PrecsType &precs, IntArray &row_sizes, typename CsType::size_type *stats, const int schur_threads=1)
perform partial incomplete LU for a level
template<class KappaType , class SpVecType >
void apply_num_dropping (const double tau, const KappaType kappa, SpVecType &v)
apply numerical dropping based on dropping tolerance
template<class SpVecType >
void apply_space_dropping (const typename SpVecType::size_type nnz, const double alpha, SpVecType &v, const typename SpVecType::size_type start_size=0u)
apply space limitation dropping
template<class T >
void steal_array_ownership (Array< T > &arr, typename Array< T >::pointer &data, typename Array< T >::size_type &size, typename Array< T >::size_type &cap)
try steal the array data ownership
template<class ValueType >
Array< ValueType > wrap_array (const typename Array< ValueType >::size_type n, ValueType *data)
wrap mutable external data
template<class ValueType >
Array< ValueType > wrap_const_array (const typename Array< ValueType >::size_type n, const ValueType *data)
wrap immutable external data
template<class ValueType , class IndexType >
CRS< ValueType, IndexType > wrap_const_crs (const typename CRS< ValueType, IndexType >::size_type nrows, const typename CRS< ValueType, IndexType >::size_type ncols, const IndexType *row_start, const IndexType *col_ind, const ValueType *vals, bool check=true)
wrap user data for CRS
template<class ValueType , class IndexType >
CCS< ValueType, IndexType > wrap_const_ccs (const typename CCS< ValueType, IndexType >::size_type nrows, const typename CCS< ValueType, IndexType >::size_type ncols, const IndexType *col_start, const IndexType *row_ind, const ValueType *vals, bool check=true)
wrap user data for CCS
template<class ExportCSType , class CSCopiedType >
void export_compressed_data (const CSCopiedType &A, typename ExportCSType::ipointer ind_start, typename ExportCSType::ipointer indices, typename ExportCSType::pointer vals)
Export data.
template<class... Args>
NspFilterPtr create_nsp_filter (Args &&... args)
construct NspFilterPtr
std::string get_reorder_name (const Options &opt)
get the reordering method name
void enable_verbose (const int flag, Options &opts)
enable verbose flags
std::string get_verbose (const Options &opt)
get the verbose name
Options get_default_options ()
get the default configuration
Params get_default_params ()
alias of get_default_options
std::string opt_repr (const Options &opt)
represent an option control with C++ string
template<typename T >
bool set_option_attr (const std::string &attr, const T v, Options &opt)
set Options attribute value from key value pairs
template<typename T >
bool set_param_attr (const std::string &attr, const T v, Options &opt)
Set the param attributes/values.
template<class CrsType , class ScalingType >
void scale_eye (CrsType &B, ScalingType &rs, ScalingType &cs, const bool ensure_fortran_index=true)
do not perform a priori scaling
template<bool IsSymm, class CrsType , class ScalingType >
void scale_extreme_values (CrsType &B, ScalingType &rs, ScalingType &cs, const bool ensure_fortran_index=true)
scale based on extreme values, do it asynchronously
template<bool IsSymm, class PermType , class CrsType , class ScalingType >
void iterative_scale_p (const PermType &p, CrsType &A, ScalingType &rs, ScalingType &cs, const double tol=1e-10, const typename CrsType::size_type max_iters=5, const bool ensure_fortran_index=true)
iterative scaling based on Jacobi operation
template<bool IsSymm, class CrsType , class ScalingType >
void iterative_scale (CrsType &A, ScalingType &rs, ScalingType &cs, const double tol=1e-10, const typename CrsType::size_type max_iters=5, const bool ensure_fortran_index=true)
iterative scaling based on Jacobi operation
template<bool IsSymm, class CcsType , class CrsType , class ScalingArray , class PermType >
CcsType::size_type do_preprocessing (const CcsType &A, const CrsType &A_crs, const typename CcsType::size_type m0, const typename CcsType::size_type level, const Options &opt, ScalingArray &s, ScalingArray &t, PermType &p, PermType &q)
routine to perform preprocessing for improving the quality of input
template<bool IsSymm, class CcsType , class CrsType , class ScalingArray , class PermType >
std::pair< CCS< typename CcsType::value_type, typename CcsType::index_type >, typename CcsType::size_type > do_maching (const CcsType &A, const CrsType &A_crs, const typename CcsType::size_type m0, const typename CcsType::size_type level, const Options &opts, ScalingArray &s, ScalingArray &t, PermType &p, PermType &q)
compute the matching for preprocessing
template<bool IsSymm, class CcsType >
Array< typename CcsType::index_type > run_amd (const CcsType &B, const Options &opt)
apply approximated mimimum degree ordering
template<class CcsType >
CcsType::iarray_type run_rcm (const CcsType &B, const Options &opt)
apply reversed Cuthill-Mckee ordering
template<class Iter , class ValueType >
std::pair< bool, Iter > find_sorted (Iter first, Iter last, const ValueType &v)
apply binary search on a sorted array
template<class ArrayType >
void rotate_left (const typename ArrayType::size_type n, const typename ArrayType::size_type src, ArrayType &v)
rotate a subset of vector, s.t. src appears to the left most pos
template<class ArrayType >
void rotate_right (const typename ArrayType::size_type n, const typename ArrayType::size_type src, ArrayType &v)
rotate a subset of vector, s.t. src appears to the right most pos
template<class T , class ArrayType >
T * ensure_type_consistency (const ArrayType &v, const bool copy_if_needed=true)
ensure consistent between data types of T and input array
template<class IndPtrType , class IndexType , class ValueType >
void convert_coo2cs (const std::size_t primary_size, const std::size_t secondary_size, const Array< IndexType > &pidx, const Array< IndexType > &sids, const Array< ValueType > &coovals, Array< IndPtrType > &ind_start, Array< IndexType > &indices, Array< ValueType > &vals)
Convert a coordinate sparse format to compressed storage.
template<class CsType >
std::enable_if< CsType::ROW_MAJOR >::type write_bin (const char *filename, const CsType &A, const std::uint64_t m)
write a CRS matrix
template<class CsType >
std::enable_if<!CsType::ROW_MAJOR >::type write_bin (const char *filename, const CsType &A, const std::uint64_t m)
write a CCS matrix
std::tuple< bool, bool, bool, bool, std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t > query_info_bin (const char *filename)
query information of a binary file
template<class CsType , typename T = std::uint64_t>
std::enable_if<!CsType::ROW_MAJOR, T >::type read_bin (const char *filename, CsType &A)
read data from file to a CCS matrix
template<class CsType , typename T = std::uint64_t>
std::enable_if< CsType::ROW_MAJOR, T >::type read_bin (const char *filename, CsType &A)
read data from file to a CRS matrix
template<bool IsRowMajor, class IndexArray , class ValueArray >
void write_ascii (const char *fname, const IndexArray &ind_start, const typename IndexArray::size_type other_size, const IndexArray &indices, const ValueArray &vals, const typename IndexArray::size_type m)
write to ASCII file
std::tuple< bool, bool, bool, bool, std::uint64_t, std::uint64_t, std::uint64_t, std::uint64_t > query_info_ascii (const char *filename)
query information of an ASCII file
template<class IndexArray , class ValueArray >
std::tuple< bool, bool, char, std::size_t, std::size_t, std::size_t, std::size_t > read_ascii (const char *fname, IndexArray &ind_start, IndexArray &indices, ValueArray &vals)
read data from ASCII file
template<class IndexType , class ValueType >
void read_mm_sparse (const char *filename, std::size_t &nrows, std::size_t &ncols, Array< IndexType > &rows, Array< IndexType > &cols, Array< ValueType > &vals)
Read a sparse matrix form a MatrixMarket file.
template<class ValueType >
void read_mm_vector (const char *filename, Array< ValueType > &v)
Read vector from a MatrixMarket file.
template<class ValueType >
void write_mm_vector (const char *filename, const Array< ValueType > &v)
Write a float-point vector to a MatrixMarket file.
template<bool IsRowMajor, class IndptrType , class IndexType , class ValueType >
void write_mm_sparse (const char *filename, const std::size_t other_size, const Array< IndptrType > &ind_start, const Array< IndexType > &indices, const Array< ValueType > &vals)
Write a sparse matrix.
void info (std::string msg,...)
common information streaming, dump msg to HIF_STDOUT
void warning (const char *prefix, const char *file, const char *func, const unsigned line, std::string msg,...)
warning information streaming, dump to HIF_STDERR
bool warn_flag (const int flag=-1)
set/get warning flag
void error (const char *prefix, const char *file, const char *func, const unsigned line, std::string msg,...)
error information streaming, dump to HIF_STDERR
template<class T >
std::enable_if< std::is_floating_point< T >::value, T >::type conjugate (const T &v)
conjugate helper function
template<class T >
std::enable_if<!std::is_floating_point< T >::value, T >::type conjugate (const T &v)
conjugate helper function
template<class ArrayType , class Iteratable >
ArrayType::value_type inner (const ArrayType &v1, const Iteratable &v2)
compute the dot product
template<class ArrayType >
ValueTypeTrait< typename ArrayType::value_type >::value_type norm2_sq (const ArrayType &v)
compute the norm 2 square
template<class ArrayType >
ValueTypeTrait< typename ArrayType::value_type >::value_type norm2 (const ArrayType &v)
compute the Euclidean norm of a given vector
template<class ArrayType >
void normalize (ArrayType &v)
normalize an array
template<class ArrayType , class Iter >
void normalize2 (const ArrayType &v, Iter &w)
normalize an array and save the result to another array
template<class CsType , class IArray , class OArray , typename T = void>
void multiply (const CsType &A, const IArray &x, OArray &y, const bool tran=false)
matrix-vector product
template<class IArray , class OArray , typename T = void>
void multiply (const std::function< void(const void *, const typename IArray::size_type, const char, void *, const char, const bool)> &Afunc, const IArray &x, OArray &y, const bool tran=false)
matrix-vector product with std::function
std::string version ()
get the version string representation during runtime
Variables
static const Params DEFAULT_PARAMS = get_default_params()
global default parameters
Typedef Documentation
CSC
template<class ValueType , class IndexType > using hif::CSC = typedef CCS<ValueType, IndexType>
Alias of CCS.
Definition at line 2672 of file CompressedStorage.hpp.
CSR
template<class ValueType , class IndexType > using hif::CSR = typedef CRS<ValueType, IndexType>
Alias of CRS.
Definition at line 1753 of file CompressedStorage.hpp.
Function Documentation
conjugate()
template<class T > std::enable_if<!std::is_floating_point<T>::value, T>::type hif::conjugate (const T & v) inline
conjugate helper function
Template Parameters
T abstract value type, complex type
Parameters
[in] v value input
Returns
conceputally, the return is the "conjugate" of v
Definition at line 72 of file math.hpp.
convert_coo2cs()
template<class IndPtrType , class IndexType , class ValueType > void hif::convert_coo2cs (const std::size_t primary_size, const std::size_t secondary_size, const Array< IndexType > & pidx, const Array< IndexType > & sids, const Array< ValueType > & coovals, Array< IndPtrType > & ind_start, Array< IndexType > & indices, Array< ValueType > & vals) inline
Convert a coordinate sparse format to compressed storage.
Template Parameters
IndPtrType Index pointer data type
IndexType Index data type
ValueType Value data type
Parameters
[in] primary_size Size in the compressed axis, e.g., nrows for CRS
[in] secondary_size Size in the uncompressed axis, e.g., ncols for CRS
[in] pidx Primary index list, e.g., rows for CRS
[in] sids Secondary index list, e.g., cols for CRS
[in] coovals Coo format values
[out] ind_start Index pointer
[out] indices Index list
[out] vals Values corresponding to indices
For CRS, call this function as convert_coo2crs(nrows, ncols, rows, cols, coovals, rowptr, colind, vals). For CCS, call this function as convert_coo2crs(ncols, nrows, cols, rows, coovals, colptr, rowind, vals).
Definition at line 55 of file coo2compress.hpp.
References DATA_UNDEF.
read_bin()
template<class CsType , typename T = std::uint64_t> std::enable_if<CsType::ROW_MAJOR, T>::type hif::read_bin (const char * filename, CsType & A) inline
read data from file to a CRS matrix
Template Parameters
CsType crs type
Parameters
[in] filename file name
[out] A matrix to store data from file
See also
write_bin
Definition at line 425 of file io.hpp.
References hif::Array< T >::Array(), hif::Array< T >::cbegin(), hif::Array< T >::cend(), hif::Array< T >::data(), DATA_UNDEF, error(), hif::internal::is_little_endian(), hif::internal::read_general_info(), hif::internal::read_matrix_data_attrs(), hif::internal::read_matrix_sizes(), hif::Array< T >::status(), and warning().
warn_flag()
bool hif::warn_flag (const int flag = -1) inline
set/get warning flag
Parameters
[in] flag warning flag
Definition at line 110 of file log.hpp.
Referenced by hif::HIF< ValueType, IndexType, UserDenseFactor >::factorize(), and hif::internal::StderrStruct::operator()().
write_bin()
template<class CsType > std::enable_if<!CsType::ROW_MAJOR>::type hif::write_bin (const char * filename, const CsType & A, const std::uint64_t m) inline
write a CCS matrix
Template Parameters
CsType Ccs type, see CCS
Parameters
[in] filename file name
[in] A matrix for writing to file
[in] m leading symmetric block size
See also
read_bin
Definition at line 350 of file io.hpp.
References error(), hif::internal::write_general_info(), hif::internal::write_matrix_data_attrs(), and hif::internal::write_matrix_sizes().