HIFIR: libhifir_impl Namespace Reference
libhifir_impl Namespace Reference
Functions
template<class PrecType >
static void get_factor_stats (const PrecType &M, std::size_t stats[])
static hif::Params create_params (const double params[])
template<class ValueType , class MatHdlType >
static LhfStatus mm_read_sparse (const char *fname, MatHdlType mat)
template<class PrecType , class MatHdlType >
static void factorize (PrecType &M, const MatHdlType mat, const double params[])
template<class PrecType , class ValueType >
static void solve (PrecType &M, const ValueType *b, ValueType *x, const bool trans=false)
template<class PrecType , class ValueType >
static void mmultiply (PrecType &M, const ValueType *b, ValueType *x, const bool trans=false)
template<class PrecType , class MatHdlType , class ValueType >
static void hifir (const PrecType &M, const MatHdlType A, const ValueType *b, const int nirs, const double *betas, const bool trans, const int rank, ValueType *x, int *ir_status)
Variables
static std::string error_msgs [2]
Function Documentation
create_params()
static hif::Params libhifir_impl::create_params (const double params[]) inline static
Definition at line 74 of file libhifir.cpp.
References hif_Options::alpha_L, hif_Options::alpha_U, hif_Options::beta, hif_Options::dense_thres, hif::get_default_params(), hif_Options::is_symm, hif_Options::kappa, hif_Options::kappa_d, LHF_ALPHA_L, LHF_ALPHA_U, LHF_BETA, LHF_COND, LHF_COND_D, LHF_DENSE_THRES, LHF_DROPTOL_L, LHF_DROPTOL_U, LHF_ISSYMM, LHF_NOPRE, LHF_NZP_THRES, LHF_PIVOT, LHF_REORDER, LHF_RRQR_COND, LHF_SYMMPRELVLS, LHF_THREADS, LHF_VERBOSE, hif_Options::no_pre, hif_Options::nzp_thres, hif_Options::pivot, hif_Options::reorder, hif_Options::rrqr_cond, hif_Options::symm_pre_lvls, hif_Options::tau_L, hif_Options::tau_U, hif_Options::threads, and hif_Options::verbose.
Referenced by factorize().
factorize()
template<class PrecType , class MatHdlType > static void libhifir_impl::factorize (PrecType & M, const MatHdlType mat, const double params[]) inline static
Definition at line 130 of file libhifir.cpp.
References create_params().
Referenced by lhfcRefactorize(), lhfcSetup(), lhfdRefactorize(), lhfdSetup(), lhfsRefactorize(), lhfsSetup(), lhfzRefactorize(), and lhfzSetup().
get_factor_stats()
template<class PrecType > static void libhifir_impl::get_factor_stats (const PrecType & M, std::size_t stats[]) inline static
Definition at line 57 of file libhifir.cpp.
Referenced by lhfcGetStats(), lhfdGetStats(), lhfsGetStats(), and lhfzGetStats().
hifir()
template<class PrecType , class MatHdlType , class ValueType > static void libhifir_impl::hifir (const PrecType & M, const MatHdlType A, const ValueType * b, const int nirs, const double * betas, const bool trans, const int rank, ValueType * x, int * ir_status) inline static
Definition at line 172 of file libhifir.cpp.
Referenced by lhfcApply(), lhfczApply(), lhfdApply(), lhfsApply(), lhfsdApply(), and lhfzApply().
mm_read_sparse()
template<class ValueType , class MatHdlType > static LhfStatus libhifir_impl::mm_read_sparse (const char * fname, MatHdlType mat) inline static
Definition at line 98 of file libhifir.cpp.
References LHF_MISMATCHED_SIZES, and LHF_SUCCESS.
Referenced by lhfcReadSparse(), lhfdReadSparse(), lhfsReadSparse(), and lhfzReadSparse().
mmultiply()
template<class PrecType , class ValueType > static void libhifir_impl::mmultiply (PrecType & M, const ValueType * b, ValueType * x, const bool trans = false) inline static
Definition at line 161 of file libhifir.cpp.
Referenced by lhfcApply(), lhfczApply(), lhfdApply(), lhfsApply(), lhfsdApply(), and lhfzApply().
solve()
template<class PrecType , class ValueType > static void libhifir_impl::solve (PrecType & M, const ValueType * b, ValueType * x, const bool trans = false) inline static
Definition at line 149 of file libhifir.cpp.
Referenced by lhfcApply(), lhfcSolve(), lhfczApply(), lhfczSolve(), lhfdApply(), lhfdSolve(), lhfsApply(), lhfsdApply(), lhfsdSolve(), lhfsSolve(), lhfzApply(), and lhfzSolve().
Variable Documentation
error_msgs
std::string libhifir_impl::error_msgs[2] static
Definition at line 53 of file libhifir.cpp.
Referenced by lhfGetErrorMsg().