HIFIR: hif::mt Namespace Reference
hif::mt Namespace Reference
Functions
template<class CrsType , class CcsType , class BufArray , class IntBufArray >
void drop_L_E_and_U_F (const typename CrsType::iarray_type &ref_indptr_L, const double alpha_L, const typename CcsType::iarray_type &ref_indptr_U, const double alpha_U, CrsType &L_E, CcsType &U_F, BufArray &buf_L, IntBufArray &ibuf_L, BufArray &buf_U, IntBufArray &ibuf_U, const int nthreads)
drop L_E and U_F
template<class ScaleArray , class CrsType , class PermType , class DiagArray , class SpVecType >
CrsType compute_Schur_simple (const ScaleArray &s, const CrsType &A, const ScaleArray &t, const PermType &p, const PermType &q, const typename CrsType::size_type m, const CrsType &L_E, const DiagArray &d, const CrsType &U_F, SpVecType &buf0, const int nthreads)
compute the simple version of Schur complement in MT setting
int get_nthreads (const int threads=std::numeric_limits< int >::max())
get number of threads
int get_thread ()
get "my" thread id
std::pair< std::size_t, std::size_t > uniform_partition (const std::size_t n, const int threads, const int thread)
uniform partition
template<class CsType , class IArray , class OArray , typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type multiply_nt (const CsType &A, const IArray &x, OArray &y)
matrix vector in parallel with openmp
template<class CsType , class Vx , class Vy , typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type multiply_nt_low (const CsType &A, const Vx *x, Vy *y)
matrix vector in parallel with openmp
template<class CsType , class IArray , class OArray , typename T = void>
std::enable_if<!CsType::ROW_MAJOR, T >::type multiply_nt (const CsType &A, const IArray &x, OArray &y)
CCS API compatibility.
template<class CsType , class Vx , class Vy , typename T = void>
std::enable_if<!CsType::ROW_MAJOR, T >::type multiply_nt_low (const CsType &A, const Vx *x, Vy *y)
CCS API compatibility.
template<class CsType , class InType , class OutType , std::size_t Nrhs, typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type multiply_mrhs_nt (const CsType &A, const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y)
matrix vector in parallel with openmp for multiple RHS
template<std::size_t Nrhs, class CsType , class Vx , class Vy , typename T = void>
std::enable_if< CsType::ROW_MAJOR, T >::type multiply_mrhs_nt_low (const CsType &A, const Vx *x, Vy *y)
matrix vector in parallel with openmp for multiple RHS
template<class CsType , class InType , class OutType , std::size_t Nrhs, typename T = void>
std::enable_if<!CsType::ROW_MAJOR, T >::type multiply_mrhs_nt (const CsType &A, const Array< std::array< InType, Nrhs >> &x, Array< std::array< OutType, Nrhs >> &y)
matrix vector in parallel with openmp for multiple RHS for CCS
template<std::size_t Nrhs, class CsType , class Vx , class Vy , typename T = void>
std::enable_if<!CsType::ROW_MAJOR, T >::type multiply_mrhs_nt_low (const CsType &A, const Vx *x, Vy *y)
matrix vector in parallel with openmp for multiple RHS for CCS
template<class IArray , class OArray >
void multiply_nt (const std::function< void(const void *, const typename IArray::size_type, const char, void *, const char, const bool)> &Afunc, const IArray &x, OArray &y)
use user functor for computing "matrix"-vector product
Function Documentation
multiply_mrhs_nt()
template<class CsType , class InType , class OutType , std::size_t Nrhs, typename T = void> std::enable_if<!CsType::ROW_MAJOR, T>::type hif::mt::multiply_mrhs_nt (const CsType & A, const Array< std::array< InType, Nrhs >> & x, Array< std::array< OutType, Nrhs >> & y) inline
matrix vector in parallel with openmp for multiple RHS for CCS
Definition at line 176 of file mt_mv.hpp.
References hif::warning().
multiply_mrhs_nt_low()
template<std::size_t Nrhs, class CsType , class Vx , class Vy , typename T = void> std::enable_if<!CsType::ROW_MAJOR, T>::type hif::mt::multiply_mrhs_nt_low (const CsType & A, const Vx * x, Vy * y) inline
matrix vector in parallel with openmp for multiple RHS for CCS
Definition at line 186 of file mt_mv.hpp.
References hif::warning().
multiply_nt() [1/2]
template<class CsType , class IArray , class OArray , typename T = void> std::enable_if<!CsType::ROW_MAJOR, T>::type hif::mt::multiply_nt (const CsType & A, const IArray & x, OArray & y) inline
CCS API compatibility.
Definition at line 101 of file mt_mv.hpp.
References hif::warning().
multiply_nt() [2/2]
template<class IArray , class OArray > void hif::mt::multiply_nt (const std::function< void(const void *, const typename IArray::size_type, const char, void *, const char, const bool)> & Afunc, const IArray & x, OArray & y) inline
use user functor for computing "matrix"-vector product
Template Parameters
IArray input array type
OArray output array type
Parameters
[in] Afunc callable functor
[in] x array to multiply with
[out] y y=A*x
Definition at line 209 of file mt_mv.hpp.
multiply_nt_low()
template<class CsType , class Vx , class Vy , typename T = void> std::enable_if<!CsType::ROW_MAJOR, T>::type hif::mt::multiply_nt_low (const CsType & A, const Vx * x, Vy * y) inline
CCS API compatibility.
Definition at line 109 of file mt_mv.hpp.
References hif::warning().